// @ts-nocheck
import * as T from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { select } from 'd3-selection';
import { scaleLinear } from 'd3-scale';
import { Simulation, DT, GOAL, clamp } from './simulation.mjs';
import { createAssets, makeSpace } from './visuals';
import {SoftwareRenderer} from './software-renderer';
import { SalvageAudio } from './audio.mjs';
export class Game {
 constructor(host,map,onUpdate,onPause){
 this.host=host;this.map=map;this.onUpdate=onUpdate;this.onPause=onPause;this.sim=new Simulation();this.audio=new SalvageAudio();this.running=false;this.paused=false;this.muted=false;this.quality='high';this.keys={};this.pointer={x:0,y:0,down:false,active:false};this.touchMove={x:0,z:0};this.touchAim={x:0,z:-1,active:false};this.gamepadActive=false;this.gamepadButtons={};this.zoom=1;this.aim=0;this.lastInput='keyboard';this.clock=0;this.accumulator=0;this.last=performance.now();this.hudTime=0;this.cleanup=[];this.shake=0;
 this.scene=new T.Scene();this.scene.background=new T.Color(0x06121e);
 try{this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{this.renderer=new SoftwareRenderer();}this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;host.appendChild(this.renderer.domElement);
 this.camera=new T.OrthographicCamera(-60,60,45,-45,.1,1700);this.camera.position.set(0,92,77);this.target=new T.Vector3(0,0,14);this.camera.lookAt(this.target);
 this.scene.add(new T.HemisphereLight(0xaadfff,0x283441,2.2));const sun=new T.DirectionalLight(0xffd9a2,4.5);sun.position.set(-60,80,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;sun.shadow.camera.near=1;sun.shadow.camera.far=280;sun.shadow.bias=-.001;sun.shadow.normalBias=.08;this.sun=sun;this.scene.add(sun,sun.target);const fill=new T.DirectionalLight(0x57baff,2);fill.position.set(50,12,-40);this.scene.add(fill);
 if(!this.renderer.software){const pmrem=new T.PMREMGenerator(this.renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);this.scene.environment=env.texture;this.scene.environmentIntensity=.55;room.dispose();pmrem.dispose();this.env=env;}
 this.assets=createAssets(this.scene);makeSpace(this.scene);
 this.world=new T.Group();this.scene.add(this.world);for(const r of this.sim.rocks){const mesh=this.assets.rock(r.r,r.id);mesh.position.set(r.x,-.6,r.z);mesh.rotation.set(.1,r.angle,.2);this.world.add(mesh);}for(let i=0;i<65;i++){const rock=this.assets.rock(1+(i%4),i+50);rock.position.set(Math.sin(i*42.2)*220,-18-(i%8)*3,-i*10+70);rock.rotation.set(i,i*.72,.2);this.world.add(rock);}
 this.tug=this.assets.tug();this.wreck=this.assets.wreck();this.scene.add(this.tug,this.wreck);this.station=this.assets.station();this.station.position.set(GOAL.x,0,GOAL.z);this.scene.add(this.station);
 // A sparse beacon trail gives movement a visible reference without a ground plane.
 for(let i=0;i<24;i++){const g=new T.Group();const z=-20-i*20;const ring=new T.Mesh(new T.RingGeometry(.4,.5,12),new T.MeshBasicMaterial({color:0x62cddd,transparent:true,opacity:.3,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(0,-3,z);g.add(ring);this.world.add(g);}
 const ropeGeo=new T.BufferGeometry();ropeGeo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(25*3),3));this.rope=new T.Line(ropeGeo,new T.LineBasicMaterial({color:0xc4e6d5}));this.scene.add(this.rope);
 this.enemyModels=new Map();this.bulletMesh=new T.InstancedMesh(new T.BoxGeometry(.14,.14,2.1),new T.MeshBasicMaterial({color:0xffffff}),160);this.bulletMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.bulletMesh.frustumCulled=false;this.scene.add(this.bulletMesh);this.dummy=new T.Object3D();
 this.particles=[];const partGeo=new T.BufferGeometry();partGeo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(1000*3),3));partGeo.setAttribute('color',new T.Float32BufferAttribute(new Float32Array(1000*3),3));this.particleMesh=new T.Points(partGeo,new T.PointsMaterial({size:1.3,map:this.assets.glowTexture,vertexColors:true,transparent:true,blending:T.AdditiveBlending,depthWrite:false,opacity:.9}));this.particleMesh.frustumCulled=false;this.scene.add(this.particleMesh);this.rings=[];
 this.crosshair=new T.Group();const crossMat=new T.MeshBasicMaterial({color:0xb8eff2,transparent:true,opacity:.85,side:T.DoubleSide});const cr=new T.Mesh(new T.RingGeometry(.65,.72,32),crossMat);cr.rotation.x=-Math.PI/2;this.crosshair.add(cr);for(const s of [-1,1]){const a=new T.Mesh(new T.BoxGeometry(.08,.06,.48),crossMat);a.position.z=s*1.05;this.crosshair.add(a);const b=new T.Mesh(new T.BoxGeometry(.48,.06,.08),crossMat);b.position.x=s*1.05;this.crosshair.add(b);}this.scene.add(this.crosshair);
 if(!this.renderer.software){this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new T.Vector2(800,600),.48,.55,1.05);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());}
 this.raycaster=new T.Raycaster();this.plane=new T.Plane(new T.Vector3(0,1,0),-1);this.aimPoint=new T.Vector3();
 this.initMap();this.bind();this.resize();this.frame=this.frame.bind(this);this.raf=requestAnimationFrame(this.frame);this.emit();
 }
 listen(target,event,fn,options){target.addEventListener(event,fn,options);this.cleanup.push(()=>target.removeEventListener(event,fn,options));}
 bind(){
 this.listen(window,'resize',()=>this.resize());
 this.listen(window,'keydown',e=>{if(e.defaultPrevented)return;if(e.code==='Escape'&&document.querySelector('[data-slot=dialog-content]'))return;if(e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape','Tab'].includes(e.code)&&this.running)e.preventDefault();if(e.repeat&&['KeyE','KeyF','Escape','KeyP'].includes(e.code))return;this.keys[e.code]=true;this.lastInput='keyboard';this.gamepadActive=false;if(e.code==='Escape'||e.code==='KeyP'){if(this.running&&(!this.paused||e.code==='KeyP'))this.pause(!this.paused);}if(!this.running||this.paused)return;if(e.code==='KeyE')this.sim.toggleTow();if(e.code==='KeyF')this.sim.winch();});
 this.listen(window,'keyup',e=>this.keys[e.code]=false);
 this.listen(this.renderer.domElement,'pointermove',e=>{if(e.pointerType!=='mouse')return;const r=this.host.getBoundingClientRect();this.pointer.x=(e.clientX-r.left)/r.width*2-1;this.pointer.y=-(e.clientY-r.top)/r.height*2+1;this.pointer.active=true;this.lastInput='keyboard';this.gamepadActive=false;});
 this.listen(this.renderer.domElement,'pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0){this.pointer.down=true;this.audio.start();}});
 this.listen(window,'pointerup',()=>this.pointer.down=false);this.listen(window,'pointercancel',()=>this.clearInput());
 this.listen(this.renderer.domElement,'contextmenu',e=>e.preventDefault());this.listen(this.renderer.domElement,'wheel',e=>{e.preventDefault();this.zoom=clamp(this.zoom+Math.sign(e.deltaY)*.06,.8,1.35);this.resize();},{passive:false});
 this.listen(window,'blur',()=>{this.clearInput();if(this.running)this.pause(true);});this.listen(document,'visibilitychange',()=>{if(document.hidden){this.clearInput();if(this.running)this.pause(true);}});
 this.listen(window,'gamepaddisconnected',()=>{this.clearInput();this.gamepadActive=false;});
 const context=document.modelContext;if(context?.registerTool){const controller=new AbortController();this.cleanup.push(()=>controller.abort());try{Promise.resolve(context.registerTool({name:'read_salvage_run',description:'Read the current Wreck Run mission status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(args)=>{if(args&&Object.keys(args).length)throw new Error('No parameters accepted');return {...this.sim.snapshot,paused:this.paused,started:this.running};}},{signal:controller.signal})).catch(()=>{});}catch{}}
 }
 clearInput(){this.keys={};this.pointer.down=false;this.touchMove={x:0,z:0};this.touchAim.active=false;this.touchBoost=false;this.touchBrake=false;this.gamepadButtons={};this.gamepadSuppressed=true;}
 async start(practice=false){this.sim.reset(practice);this.running=true;this.paused=false;this.clearInput();this.target.set(0,0,14);this.particles=[];this.rings.forEach(r=>this.scene.remove(r.mesh));this.rings=[];await this.audio.start();this.audio.setMuted(this.muted);this.emit();}
 pause(value){this.paused=value;this.clearInput();this.accumulator=0;this.onPause(value);if(!value)this.audio.start();this.emit();}
 mute(value){this.muted=value;this.audio.setMuted(value);}
 setQuality(value){this.quality=value;this.renderer.shadowMap.enabled=value==='high';this.renderer.setPixelRatio(Math.min(devicePixelRatio,value==='high'?1.75:1));this.resize();}
 resize(){const width=this.host.clientWidth,height=this.host.clientHeight,aspect=width/height;const vertical=Math.max(86,74/aspect)*this.zoom;this.camera.left=-vertical*aspect/2;this.camera.right=vertical*aspect/2;this.camera.top=vertical/2;this.camera.bottom=-vertical/2;this.camera.updateProjectionMatrix();this.renderer.setSize(width,height);this.composer?.setSize(width,height);this.aspect=aspect;}
 input(){
 let x=(this.keys.KeyD||this.keys.ArrowRight?1:0)-(this.keys.KeyA||this.keys.ArrowLeft?1:0)+this.touchMove.x,z=(this.keys.KeyS||this.keys.ArrowDown?1:0)-(this.keys.KeyW||this.keys.ArrowUp?1:0)+this.touchMove.z;
 let fire=this.pointer.down,boost=!!this.keys.ShiftLeft||!!this.keys.ShiftRight||!!this.touchBoost,brake=!!this.keys.Space||!!this.touchBrake;
 const pads=navigator.getGamepads?.()||[];const pad=Array.from(pads).find(Boolean);this.controller=pad?.id||null;
 if(pad){const dead=(a,b)=>{const l=Math.hypot(a,b);if(l<.17)return [0,0];const k=clamp((l-.17)/.83,0,1)/l;return [a*k,b*k];};const [lx,ly]=dead(pad.axes[0]||0,pad.axes[1]||0),[rx,ry]=dead(pad.axes[2]||0,pad.axes[3]||0);if(Math.hypot(lx,ly,rx,ry)>.1||pad.buttons.some(b=>b.pressed))this.gamepadActive=true;
 if(this.gamepadSuppressed&&!pad.buttons.some(b=>b.pressed)&&Math.hypot(lx,ly,rx,ry)<.1)this.gamepadSuppressed=false;
 if(this.gamepadActive&&!this.gamepadSuppressed){x=lx;z=ly;if(Math.hypot(rx,ry)>.1)this.aim=Math.atan2(rx,-ry);fire=pad.buttons[7]?.value>.2;boost=pad.buttons[6]?.value>.2;brake=pad.buttons[1]?.pressed;this.lastInput='controller';}
 for(const [i,action]of [[0,()=>this.sim.toggleTow()],[2,()=>this.sim.winch()],[9,()=>{if(this.running)this.pause(!this.paused);} ]]){const v=pad.buttons[i]?.pressed;if(v&&!this.gamepadButtons[i]&&!this.gamepadSuppressed&&(i===9||(this.running&&!this.paused&&this.sim.state==='playing')))action();this.gamepadButtons[i]=v;}}
 if(this.touchAim.active){this.aim=Math.atan2(this.touchAim.x,-this.touchAim.z);fire=true;this.lastInput='touch';}
 else if(this.pointer.active&&!this.gamepadActive){this.raycaster.setFromCamera(new T.Vector2(this.pointer.x,this.pointer.y),this.camera);this.raycaster.ray.intersectPlane(this.plane,this.aimPoint);this.aim=Math.atan2(this.aimPoint.x-this.sim.player.x,-(this.aimPoint.z-this.sim.player.z));}
 else if(!this.gamepadActive&&Math.hypot(x,z)>.1)this.aim=Math.atan2(x,-z);
 return {x,z,fire,aim:this.aim,boost,brake};
 }
 emit(){this.onUpdate({...this.sim.snapshot,started:this.running,paused:this.paused,controller:!!this.controller,input:this.lastInput,software:!!this.renderer.software});}
 initMap(){if(!this.map)return;this.mapRoot=select(this.map).attr('viewBox','0 0 140 160');this.mapRoot.append('rect').attr('x',1).attr('y',1).attr('width',138).attr('height',158).attr('fill','none').attr('stroke','#406071').attr('opacity',.4);this.mapRoot.append('path').attr('d','M70 12V148').attr('stroke','#426272').attr('stroke-dasharray','2 5');this.mapRoot.append('circle').attr('cx',70).attr('cy',13).attr('r',7).attr('fill','none').attr('stroke','#6af0de');this.mapObjects=this.mapRoot.append('g');}
 updateMap(){if(!this.mapObjects)return;const sx=scaleLinear().domain([-120,120]).range([8,132]),sz=scaleLinear().domain([-500,70]).range([9,151]);const data=[{id:'tug',...this.sim.player,color:'#b4edff',r:3.3},{id:'wreck',...this.sim.wreck,color:'#f7bf6e',r:3.8},...this.sim.enemies.map(e=>({...e,color:'#ff765e',r:2.5}))];this.mapObjects.selectAll('circle').data(data,d=>d.id).join('circle').attr('cx',d=>sx(d.x)).attr('cy',d=>sz(d.z)).attr('r',d=>d.r).attr('fill',d=>d.color);}
 burst(x,z,color,count=18,force=8){for(let i=0;i<count&&this.particles.length<950;i++){const a=Math.random()*6.28,v=Math.random()*force,life=.3+Math.random()*.8;this.particles.push({x,y:1+Math.random()*2,z,vx:Math.sin(a)*v,vy:(Math.random()-.2)*4,vz:Math.cos(a)*v,life,max:life,color:new T.Color(color)});}}
 event(e){const pan=clamp(((e.x??this.sim.player.x)-this.sim.player.x)/40,-1,1);const name=e.type==='impact'?'hit':e.type==='rockHit'?'cargoHit':e.type;this.audio.event(name,pan);
 if(['hit','cargoHit','impact','rockHit','explosion'].includes(e.type)){const big=e.type==='explosion';this.burst(e.x,e.z,big?0xff923e:e.type==='cargoHit'?0xffb966:0xadebff,big?70:14,big?20:8);this.shake=Math.max(this.shake,big?.85:e.type==='hit'?.6:.14);if(big){const mesh=new T.Mesh(new T.RingGeometry(.92,1,64),new T.MeshBasicMaterial({color:0xffbb66,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending}));mesh.rotation.x=-Math.PI/2;mesh.position.set(e.x,1,e.z);this.scene.add(mesh);this.rings.push({mesh,life:.6});}}
 }
 render(dt,input){
 const s=this.sim,p=s.player,w=s.wreck;this.clock+=dt;
 this.tug.position.set(p.x,.35,p.z);this.tug.rotation.y=-p.angle;this.tug.rotation.z=clamp(p.vx*.01,-.12,.12);this.tug.userData.turret.rotation.y=-this.aim+p.angle;
 this.wreck.position.set(w.x,.2,w.z);this.wreck.rotation.y=w.angle;this.wreck.rotation.z=Math.sin(this.clock*.8)*.018;
 const moving=this.running&&!this.paused&&s.state==='playing',power=moving?clamp(Math.hypot(input.x,input.z),0,1):.1;
 this.tug.userData.engines.forEach((e,i)=>{e.scale.y=.24+power*(s.boosting?2.4:1.2)+Math.sin(this.clock*50+i)*.04;});
 if(moving&&power>.1&&Math.random()<dt*65){const a=-p.angle,ex=Math.sin(a)*3.8,ez=Math.cos(a)*3.8;this.particles.push({x:p.x+ex,y:.9,z:p.z+ez,vx:-p.vx*.3,vy:0,vz:-p.vz*.3,life:.38,max:.38,color:new T.Color(s.boosting?0xc4ffff:0x37bcff)});}
 const pos=this.rope.geometry.attributes.position;const dx=w.x-p.x,dz=w.z-p.z,d=Math.hypot(dx,dz)||1;const endx=w.x-dx/d*8,endz=w.z-dz/d*8;for(let i=0;i<25;i++){const t=i/24,sag=Math.sin(t*Math.PI)*(1-s.tension)*2;pos.setXYZ(i,p.x+(endx-p.x)*t,.55-sag*.18,p.z+(endz-p.z)*t+sag);}pos.needsUpdate=true;this.rope.geometry.computeBoundingSphere();this.rope.visible=s.attached;this.rope.material.color.set(s.tension>.8?0xffb35c:0xc2dacf);
 const ids=new Set(s.enemies.map(e=>e.id));for(const [id,model]of this.enemyModels){if(!ids.has(id)){this.scene.remove(model,model.userData.line);this.enemyModels.delete(id);}}
 for(const e of s.enemies){let model=this.enemyModels.get(e.id);if(!model){model=this.assets.raider(e.kind==='heavy');const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineDashedMaterial({color:0xff8061,dashSize:1.3,gapSize:1,transparent:true,opacity:.6}));model.userData.line=line;this.scene.add(model,line);this.enemyModels.set(e.id,model);}model.position.set(e.x,.4,e.z);model.rotation.y=-e.angle;const line=model.userData.line;line.visible=e.charge>0&&this.running;const lp=line.geometry.attributes.position;lp.setXYZ(0,e.x,1,e.z);lp.setXYZ(1,e.x+Math.sin(e.aim)*65,1,e.z-Math.cos(e.aim)*65);lp.needsUpdate=true;line.geometry.computeBoundingSphere();line.computeLineDistances();line.material.opacity=e.locked?.95:.3+(1-e.charge)*.4;model.userData.engines.forEach(a=>a.scale.y=.55+Math.random()*.1);}
 this.bulletMesh.count=Math.min(160,s.bullets.length);for(let i=0;i<this.bulletMesh.count;i++){const b=s.bullets[i];this.dummy.position.set(b.x,1.45,b.z);this.dummy.rotation.set(0,Math.atan2(b.vx,b.vz),0);this.dummy.updateMatrix();this.bulletMesh.setMatrixAt(i,this.dummy.matrix);this.bulletMesh.setColorAt(i,new T.Color(b.enemy?0xff7243:0x9ef8ff));}this.bulletMesh.instanceMatrix.needsUpdate=true;if(this.bulletMesh.instanceColor)this.bulletMesh.instanceColor.needsUpdate=true;
 const part=this.particleMesh.geometry.attributes.position,col=this.particleMesh.geometry.attributes.color;for(let i=this.particles.length-1;i>=0;i--){const a=this.particles[i];if(!this.paused){a.life-=dt;a.x+=a.vx*dt;a.z+=a.vz*dt;a.y+=a.vy*dt;}if(a.life<=0)this.particles.splice(i,1);}this.particles.forEach((a,i)=>{part.setXYZ(i,a.x,a.y,a.z);const fade=a.life/a.max;col.setXYZ(i,a.color.r*fade,a.color.g*fade,a.color.b*fade);});part.needsUpdate=true;col.needsUpdate=true;this.particleMesh.geometry.setDrawRange(0,this.particles.length);
 for(let i=this.rings.length-1;i>=0;i--){const r=this.rings[i];if(!this.paused)r.life-=dt;r.mesh.scale.setScalar(1+(1-r.life/.6)*22);r.mesh.material.opacity=Math.max(0,r.life/.6)*.6;if(r.life<=0){this.scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();this.rings.splice(i,1);}}
 const cx=p.x*.65+w.x*.35,cz=p.z*.65+w.z*.35;this.target.lerp(new T.Vector3(cx,0,cz),1-Math.exp(-dt*3));const shake=this.shake;this.shake*=Math.exp(-dt*10);this.camera.position.set(this.target.x+(Math.random()-.5)*shake,this.target.y+100,this.target.z+68+(Math.random()-.5)*shake);this.camera.lookAt(this.target);this.sun.position.set(this.target.x-60,80,this.target.z+15);this.sun.target.position.copy(this.target);
 if(this.pointer.active&&!this.gamepadActive&&!this.touchAim.active)this.crosshair.position.copy(this.aimPoint);else this.crosshair.position.set(p.x+Math.sin(this.aim)*22,1,p.z-Math.cos(this.aim)*22);this.crosshair.visible=this.running&&!this.paused;
 this.station.children[0].material.emissiveIntensity=1.4+Math.sin(this.clock*2)*.4;
 const danger=s.enemies.reduce((v,e)=>Math.max(v,clamp(1-Math.hypot(e.x-p.x,e.z-p.z)/80,0,1)),0);this.audio.update({thrust:power,boost:s.boosting,tension:s.tension,danger,speed:Math.min(1,Math.hypot(p.vx,p.vz)/20),paused:!moving});
 if(this.quality==='high'&&this.composer)this.composer.render();else this.renderer.render(this.scene,this.camera);
 }
 frame(now){const dt=Math.min((now-this.last)/1000,.05);this.last=now;const input=this.input();if(this.running&&!this.paused&&this.sim.state==='playing'){this.accumulator+=dt;while(this.accumulator>=DT){this.sim.update(DT,input);this.accumulator-=DT;}for(const e of this.sim.events)this.event(e);this.sim.events=[];}else this.accumulator=0;this.render(dt,input);this.hudTime+=dt;if(this.hudTime>.1){this.hudTime=0;this.emit();this.updateMap();}this.raf=requestAnimationFrame(this.frame);}
 dispose(){cancelAnimationFrame(this.raf);this.cleanup.forEach(fn=>fn());this.audio.dispose();this.mapRoot?.selectAll('*').remove();const geos=new Set(),mats=new Set();this.scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m));});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());this.env?.dispose();this.composer?.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
