// Serializable, turn-based simulation. View animations never create or move cargo.
import {WORLDS,GENERATOR_VERSION,CLUSTER_SEED,siteInfo,regionById,regions,landingSites,longitudeDelta,tileAtAxial} from './world.js';
export {WORLDS} from './world.js';
import {PROJECTS,REGIONAL_PROJECTS} from './catalog.js';
export {PROJECTS,REGIONAL_PROJECTS} from './catalog.js';
import {surfaceOccupants} from './occupancy.js';
import {initialCity,cityForecast,advanceCity,recordCityFreight,GROWTH_POLICIES} from './city.js';
export const SAVE_KEY='first-light-expeditions-v1';
export const KITS={survey:{name:'Survey instruments',short:'Survey',cost:6,description:'Map the destination and return. The ship can then serve a cargo route.'},mine:{name:'Extraction outpost',short:'Extract',cost:14,description:'A sealed mine, or automated propellant condensers on Nacre. Includes 24 local construction materials.'},habitat:{name:'Settlement kit',short:'Settle',cost:16,description:'A founding habitat for twelve settlers with 24 local construction materials.'},greenhouse:{name:'Greenhouse kit',short:'Grow',cost:18,description:'An enclosed farm produces 3 provisions per season; growers can produce more.'},supply:{name:'Supply delivery',short:'Supply',cost:4,description:'Deliver provisions, 16 construction materials and 4 propellant. The transport joins the local fleet.'}};
export const PRESETS={scout:{name:'Wayfinder',fuel:2,cargo:1,power:'solar',engine:'efficient'},pioneer:{name:'Pioneer',fuel:2,cargo:3,power:'reactor',engine:'boost'},carrier:{name:'Longshore',fuel:2,cargo:2,power:'solar',engine:'efficient'}};
export const DEFAULT_DESIGN={...PRESETS.scout};
export const FOCUSES={balanced:{name:'Build community',description:'Develop the settlement. The working economy attracts households when housing and reserves support them.'},agriculture:{name:'Grow provisions',description:'+2 provisions from the greenhouse; development pauses.'},industry:{name:'Run industry',description:'+2 extraction output and +1 construction work each season; development pauses.'},research:{name:'Field research',description:'+1 knowledge each supported season; development pauses.'}};
export const TECHNOLOGIES={propulsion:{name:'Deep-range drives',cost:9,description:'Future expeditions need 15% less transfer fuel.'},navigation:{name:'Navigation charts',cost:3,description:'New interstellar expeditions take one fewer season per leg.'},cargo:{name:'Compact life support',cost:4,description:'New expeditions carry 12 provisions per pod, up from 8.'}};
const copy=s=>structuredClone(s);
const log=(s,title,text,kind='info')=>{s.logs.unshift({turn:s.turn,title,text,kind});s.logs=s.logs.slice(0,80);};
function milestone(s,key,title,text){if(s.chronicle.some(e=>e.key===key))return;s.chronicle.push({key,turn:s.turn,title,text});log(s,title,text,'discovery');}
export function initialState(seed){
 if(!seed){const base='fl-'+Math.random().toString(36).slice(2,10)+'-'+Date.now().toString(36);for(let n=0;n<8;n++){const candidate=base+(n?':'+n:'');try{for(const id of Object.keys(WORLDS))landingSites(id,candidate);seed=candidate;break;}catch{}}if(!seed)seed=CLUSTER_SEED;}
 return{version:7,universe:{seed,version:GENERATOR_VERSION},turn:0,materials:100,home:{provisions:80,propellant:30,components:8},surveys:Object.fromEntries(Object.keys(WORLDS).map(id=>[id,id==='hearth'])),colonies:{},stations:{},services:[],route:null,mission:null,fleet:[],chronicle:[],history:[],improvements:{},logs:[{turn:0,title:'The first light',text:'Survey Rook, then put the returning ship to work. Hearth keeps producing the supplies your program needs.',kind:'discovery'}],launched:0,won:false,policy:null,research:0,tech:{navigation:false,cargo:false,propulsion:false}};
}
export const facilityWorld=id=>id?.startsWith('orbit:')?id.slice(6):id;
export const facilityName=id=>id?.startsWith('orbit:')?(WORLDS[facilityWorld(id)]?.name+' orbital depot'):WORLDS[id]?.name||'Unknown';
export function inventory(s,id='hearth'){if(id==='hearth')return{materials:s.materials,provisions:s.home.provisions,propellant:s.home.propellant,components:s.home.components||0};if(id.startsWith('orbit:'))return s.stations[facilityWorld(id)]||{materials:0,provisions:0,propellant:0,components:0};const c=s.colonies[id];return{materials:c?.materials||0,provisions:c?.supplies||0,propellant:c?.propellant||0,components:c?.components||0};}
function changeStock(s,id,cargo,sign=1){if(id==='hearth'){s.materials+=sign*(cargo.materials||0);s.home.provisions+=sign*(cargo.provisions||0);s.home.propellant+=sign*(cargo.propellant||0);s.home.components=(s.home.components||0)+sign*(cargo.components||0);}else{const station=id.startsWith('orbit:'),c=station?s.stations[facilityWorld(id)]:s.colonies[id];if(!c)throw Error('The receiving facility is unavailable.');c.materials+=sign*(cargo.materials||0);c[station?'provisions':'supplies']+=sign*(cargo.provisions||0);c.propellant+=sign*(cargo.propellant||0);c.components=(c.components||0)+sign*(cargo.components||0);}}
const stocked=(s,id,cargo)=>Object.entries(cargo).every(([key,n])=>inventory(s,id)[key]>=n);
export function facilities(s){return['hearth',...Object.keys(s.colonies),...Object.keys(s.stations).filter(id=>!s.stations[id].building).map(id=>'orbit:'+id)];}
export const allServices=s=>[...(s.route?[s.route]:[]),...(s.services||[])];
export function validDesign(d){return d&&Number.isInteger(d.fuel)&&d.fuel>=1&&d.fuel<=3&&Number.isInteger(d.cargo)&&d.cargo>=1&&d.cargo<=3&&['solar','reactor'].includes(d.power)&&['efficient','boost'].includes(d.engine)&&typeof d.name==='string'&&d.name.length<=32;}
function travelBetween(a,b){a=facilityWorld(a);b=facilityWorld(b);return WORLDS[a].star===WORLDS[b].star?1:a==='hearth'?WORLDS[b].travel:Math.max(2,Math.ceil((WORLDS[a].travel+WORLDS[b].travel)/2));}
export function preview(state,design,destination,kit,site='coast',source='hearth'){
 const errors=[];
 if(!validDesign(design)||!WORLDS[destination]||destination==='hearth'||!KITS[kit]||!['coast','plateau'].includes(site)||!facilities(state).includes(source)||facilityWorld(source)===destination)return{errors:['Choose an available launch base, vessel and destination.'],ok:false,cost:0};
 const d=design,orbital=source.startsWith('orbit:'),base=Math.round((18+4*d.fuel+6*d.cargo+(d.power==='reactor'?10:0)+(d.engine==='boost'?8:0))*(orbital?.75:1));
 const cargoMaterials=['mine','habitat'].includes(kit)?24:kit==='supply'?16:0,cargoPropellant=kit==='survey'?0:4,cost=base+KITS[kit].cost+cargoMaterials;
 const distance=travelBetween(source,destination),travel=Math.max(1,distance-(distance>1&&d.engine==='boost'?1:0)-(distance>1&&state.tech.navigation?1:0));
 const perLeg=(distance===1?1:Math.min(3,1.25+distance*.25))*(d.engine==='boost'?1.35:1)*(state.tech.propulsion?.85:1)+(d.cargo-1)*.2;
 const fuelNeed=+(perLeg*(kit==='survey'?2:1)*(orbital?.85:1)).toFixed(1),fuelAvailable=d.fuel*2;
 const deployment=kit!=='survey'&&kit!=='supply'&&d.power==='solar'?1:0,supplies=kit==='survey'?0:d.cargo*(state.tech.cargo?12:8),stock=inventory(state,source),c=state.colonies[destination],w=WORLDS[destination];
 if(source!=='hearth'&&!orbital&&state.colonies[source].kind==='automated')errors.push('An automated site needs residential quarters and crew before launching expeditions.');
 if(source!=='hearth'&&!orbital&&state.colonies[source].shortages)errors.push('Restore this colony’s supplies before assembling an expedition.');
 if(orbital&&!state.stations[facilityWorld(source)].supported)errors.push('The depot crew needs provisions before assembly can proceed.');
 if(state.mission)errors.push('The expedition team is occupied until its current flight finishes.');
 if(cost>stock.materials)errors.push(`Need ${cost-stock.materials} more materials at ${facilityName(source)}.`);
 if(stock.provisions<supplies)errors.push(`Load ${supplies} provisions at the launch base.`);
 if(stock.propellant<fuelNeed+cargoPropellant)errors.push(`Need ${(fuelNeed+cargoPropellant).toFixed(1)} propellant at the launch base.`);
 if(fuelNeed>fuelAvailable)errors.push(`Transfer needs ${fuelNeed} fuel; this vessel carries ${fuelAvailable}. Add a tank or use the efficient drive.`);
 if(kit==='survey'&&state.surveys[destination])errors.push('This world is already surveyed.');
 if(kit!=='survey'&&!state.surveys[destination])errors.push('Survey this world before sending equipment or settlers.');
 if(kit==='mine'&&c?.mine)errors.push('Extraction is already operating here.');
 if(kit==='habitat'&&c)errors.push('A foothold already exists. Build residential quarters to expand it.');
 if(kit==='habitat'&&w.environment==='sealed')errors.push('Start with an extraction outpost here. Residential quarters can make it permanent later.');
 if(['greenhouse','supply'].includes(kit)&&!c)errors.push('Establish a foothold first.');
 if(kit==='mine'&&!c&&w.environment!=='sealed')errors.push('Establish a settlement before adding an extractor.');
 if(kit==='greenhouse'&&c?.greenhouse)errors.push('A greenhouse is already operating.');
 if(kit==='greenhouse'&&c?.kind==='automated')errors.push('Build residential quarters to bring a crew before adding a farm.');
 return{cost,base,travel,deployment,duration:travel*(kit==='survey'?2:1)+deployment,fuelNeed,fuelAvailable,supplies,cargoMaterials,cargoPropellant,cargoComponents:kit==='supply'?Math.min(2,stock.components):0,mass:Math.round(9+d.cargo*3+d.fuel*1.2+(d.power==='reactor'?4:1)),errors,ok:!errors.length};
}
export function launch(state,design,destination,kit,site='coast',source='hearth'){
 const p=preview(state,design,destination,kit,site,source);if(!p.ok)throw Error(p.errors[0]);const s=copy(state);changeStock(s,source,{materials:p.cost,provisions:p.supplies,propellant:p.fuelNeed+p.cargoPropellant,components:p.cargoComponents},-1);s.launched++;
 s.mission={id:s.launched,name:(design.name||'Wayfinder').trim()+' '+String(s.launched).padStart(2,'0'),design:{...design},source,destination,kit,site,regionId:siteInfo(destination,site,s.universe.seed).regionId,phase:'outbound',remaining:p.travel,elapsed:0,...p,started:s.turn};
 log(s,'Expedition underway',`${s.mission.name} leaves ${facilityName(source)} for ${WORLDS[destination].name}. ${KITS[kit].name} aboard.`,'launch');return s;
}
function finish(s,m,available=false){s.history.unshift({name:m.name,destination:m.destination,kit:m.kit,turn:s.turn});s.fleet.push({id:'hull-'+m.id,name:m.name,design:{...m.design},location:available?(m.kit==='survey'?m.source:m.destination):m.destination,status:available?'available':'founder',launched:m.started,flights:1});s.mission=null;}
function deploy(s,m){let c=s.colonies[m.destination];const first=!c,w=WORLDS[m.destination];
 if(!c){const automated=w.id==='nacre',kind=automated?'automated':w.environment==='sealed'?'outpost':'settlement';c={site:m.site,regionId:m.regionId,policy:null,city:initialCity(),population:automated?0:kind==='outpost'?6:12,capacity:12,kind,supplies:0,materials:0,propellant:0,components:0,development:0,mine:false,greenhouse:false,ore:0,founded:s.turn,founder:m.name,design:{...m.design,kit:m.kit},focus:'balanced',upgrades:{},project:null,shortages:0,people:automated?[]:[{name:['Mira Vale','Soren Pike','Ada Moss','Niko Reed'][s.launched%4],role:kind==='outpost'?'Crew chief':'Founding steward',arrived:s.turn}]};s.colonies[m.destination]=c;}
 c.supplies+=m.supplies;c.materials+=m.cargoMaterials||0;c.propellant+=m.cargoPropellant||0;c.components=(c.components||0)+(m.cargoComponents||0);if(m.kit==='mine')c.mine=true;if(m.kit==='greenhouse')c.greenhouse=true;c.ore=c.materials;
 if(first)milestone(s,'founded:'+m.destination,w.name+' · a foothold',`${m.name} founded ${siteInfo(m.destination,m.site,s.universe.seed).name}. ${c.population?c.population+' people':'Automated condensers'} and ${m.cargoMaterials} construction materials arrived.`);
 else log(s,KITS[m.kit].name+' delivered',`${m.name} unloaded at ${w.name}. Provisions and equipment are now in local storage.`,'build');finish(s,m,!first);
}
export function provisionUse(c,id){if(!c||c.kind==='automated')return 0;return Math.ceil(c.population/6)+(['sealed','hostile'].includes(WORLDS[id].environment)&&!c.upgrades.recycler?1:0);}
export function regionalAllowed(r,kind){return !!r&&!r.water&&!r.reserved&&(kind!=='extractor'||r.ore)&&(kind!=='garden'||r.fertile)&&(!REGIONAL_PROJECTS[kind]?.needs||r[REGIONAL_PROJECTS[kind].needs]);}
export function improvementYield(s,world=null){const out={food:0,materials:0,research:0,factories:0};for(const [rid,p]of Object.entries(s.improvements||{})){const id=rid.split(':')[0];if(world&&id!==world||p.ready>s.turn)continue;if(!regionById(id,rid,s.universe.seed))continue;if(['extractor','brickworks'].includes(p.kind))out.materials+=2;if(['batteryworks','solarworks'].includes(p.kind))out.factories++;if(p.kind==='beacon')out.research++;if(p.kind==='garden')out.food++;}return out;}
export function arrivingCargo(s,id){const out={materials:0,provisions:0,propellant:0,components:0};for(const r of allServices(s)){if(r.remaining!==1||r.waiting)continue;const dest=r.phase==='outbound'?r.destination:r.source;if(dest===id)for(const k of Object.keys(out))out[k]+=r.cargo[k]||0;}return out;}
export function colonyForecast(s,turn=s.turn+1,id='pelagos',includeArrivals=true){
 const c=s.colonies[id];if(!c)return null;const a=siteInfo(id,c.site,s.universe.seed),bonuses=improvementYield({...s,turn},id),focus=c.focus||'balanced',winter=turn%4===3,protectedPower=c.design.power==='reactor'||c.upgrades.battery||c.upgrades.shelter;
 const shops=(c.city?.plots||[]).filter(p=>p.kind==='market'&&!p.remaining).length;
 const potentialFood=(c.greenhouse?3+Math.floor(c.population/18)+(c.upgrades.garden?1:0)+(c.upgrades.arrays?1:0)+(focus==='agriculture'?2:0):0)+bonuses.food+(c.greenhouse?Math.ceil(shops/2):0),stormLoss=winter&&!protectedPower?Math.min(potentialFood,a.storm):0,food=potentialFood-stormLoss,usage=provisionUse(c,id),incoming=includeArrivals?arrivingCargo(s,id):{materials:0,provisions:0,propellant:0,components:0};
 const reserve=Math.max(0,c.supplies+incoming.provisions+food-usage),maintenance=c.kind==='automated'&&(turn%4===0||c.maintenanceDue)?1:0,fed=c.supplies+incoming.provisions+food>=usage&&c.materials+incoming.materials>=maintenance;
 const output=fed&&c.mine?a.mine+Math.floor(c.population/12)+(c.upgrades.workshop?2:0)+(focus==='industry'?2:0):0;
 const produced=fed?(id==='nacre'?0:output)+bonuses.materials+Math.floor(shops/2):0,components=fed?Math.min(bonuses.factories,Math.floor(Math.max(0,c.materials+incoming.materials+produced-maintenance))):0;
 const forecast={grossMaterials:produced,components,factoryDemand:bonuses.factories,winter,protectedPower,stormLoss,food,usage,balance:food-usage,reserve,fed,incoming,maintenance,materials:produced-components,propellant:fed&&id==='nacre'?3+(c.upgrades.workshop?2:0)+(focus==='industry'?2:0):0,research:fed?bonuses.research+(c.policy==='research'?1:0)+(focus==='research'?1+Math.floor(c.population/18):0):0,growth:fed&&focus==='balanced'&&c.kind!=='automated'?1:0,arrivals:0,work:fed?Math.max(1,Math.floor(c.population/12))+(focus==='industry'?1:0)+(c.city?.civic?1:0)+(c.upgrades.arrays?1:0):0};
 forecast.city=cityForecast(s,id,forecast,turn,includeArrivals);forecast.arrivals=forecast.city.arrivals;return forecast;
}
export function setGrowthPolicy(state,policy,id){if(!state.colonies[id]||!GROWTH_POLICIES[policy])throw Error('Choose a settlement growth policy.');if(state.colonies[id].city.policy===policy)return state;const s=copy(state);s.colonies[id].city.policy=policy;s.colonies[id].city.momentum=0;return s;}
export function setFocus(state,focus,id='pelagos'){const c=state.colonies[id];if(!c||!FOCUSES[focus])throw Error('Choose an available work priority.');if(focus==='agriculture'&&!c.greenhouse)throw Error('Deliver a greenhouse before assigning growers.');if(focus==='industry'&&!c.mine)throw Error('Deliver an extractor before assigning industrial crews.');const s=copy(state);s.colonies[id].focus=focus;return s;}
export function projectError(s,id,world){const c=s.colonies[world],p=PROJECTS[id];if(!c||!p)return'Choose a local project.';if(c.project)return'Finish or cancel the current project first.';if(c.upgrades[id])return'Already built.';if(id==='battery'&&c.design.power==='reactor')return'The reactor already protects power.';if(id==='garden'&&!c.greenhouse)return'Deliver a greenhouse first.';if(id==='workshop'&&!c.mine)return'Install extraction first.';if(id==='recycler'&&!['sealed','hostile'].includes(WORLDS[world].environment))return'Open-air habitats do not need this recycler.';if(c.materials<p.cost)return`Need ${p.cost-c.materials} more local materials.`;if((c.components||0)<(p.parts||0))return`Need ${p.parts-(c.components||0)} energy parts. Import them or build battery/solar works on a deposit.`;return null;}
export function startProject(state,id,world='pelagos'){const error=projectError(state,id,world);if(error)throw Error(error);const s=copy(state),p=PROJECTS[id];s.colonies[world].materials-=p.cost;s.colonies[world].components=(s.colonies[world].components||0)-(p.parts||0);s.colonies[world].project={id,remaining:p.work,total:p.work,paid:p.cost,paidParts:p.parts||0};log(s,'Local construction begins',`${WORLDS[world].name}: ${p.name}. ${p.work} crew-seasons of work.`,'build');return s;}
export function cancelProject(state,id='pelagos'){const s=copy(state),c=s.colonies[id];if(!c?.project)throw Error('No local project is underway.');const p=c.project,refund=Math.floor(p.paid*p.remaining/p.total);c.materials+=refund;c.components=(c.components||0)+Math.floor((p.paidParts||0)*p.remaining/p.total);c.project=null;log(s,'Project deferred',`${refund} unspent materials returned to ${WORLDS[id].name}.`);return s;}
export function setPolicy(state,policy,id='pelagos'){const c=state.colonies[id];if(!['research','housing'].includes(policy)||!c||c.kind!=='settlement')throw Error('Establish a permanent settlement first.');if(c.policy)throw Error('The community has already chosen its first shared investment.');if(c.materials<20)throw Error('This project needs 20 local materials.');const s=copy(state),n=s.colonies[id];n.materials-=20;n.policy=policy;if(id==='pelagos')s.policy=policy;if(policy==='housing')n.capacity+=12;else n.development+=3;milestone(s,'charter:'+id,WORLDS[id].name+' chooses its future',policy==='housing'?'The community builds housing for twelve more residents. New arrivals will need reliable provisions.':'The community establishes an observatory, earning knowledge while its people are supported.');return s;}
export function improveRegion(state,id,rid,kind){const r=regionById(id,rid,state.universe.seed),p=REGIONAL_PROJECTS[kind];if(!p||!state.surveys[id]||!regionalAllowed(r,kind)||!tileAtAxial(id,r.site,r.q,r.r,state.universe.seed))throw Error('Choose suitable surveyed ground.');if(state.improvements[rid])throw Error('This region already has an installation.');if(surfaceOccupants(state,id,r.site).some(o=>Math.hypot(longitudeDelta(o.x,r.x),o.z-r.z)<o.radius+3))throw Error('A structure occupies this building footprint.');if(id!=='hearth'&&!state.colonies[id])throw Error('Establish a foothold first.');if(kind==='garden'&&!state.colonies[id])throw Error('A terrace garden needs a local settlement.');if(inventory(state,id).materials<p.cost)throw Error(`Need ${p.cost} local materials.`);const s=copy(state);changeStock(s,id,{materials:p.cost},-1);s.improvements[rid]={kind,built:s.turn,ready:s.turn+p.work};log(s,p.name+' commissioned',`${WORLDS[id].name} · ${r.name}. Ready in ${p.work} seasons.`,'build');return s;}
export function researchTech(state,id){const t=TECHNOLOGIES[id];if(!t||state.tech[id])throw Error('Choose an unlearned technology.');if(state.research<t.cost)throw Error(`Collect ${t.cost} knowledge first.`);const s=copy(state);s.research-=t.cost;s.tech[id]=true;log(s,t.name,t.description,'discovery');return s;}
const emptyCargo=()=>({materials:0,provisions:0,propellant:0,components:0});
export const cargoTotal=c=>Object.values(c).reduce((a,b)=>a+b,0);
function routeFuel(s,r){return r.source.startsWith('orbit:')?1:Math.max(1,r.travel);}
function loadRoute(s,r){
 r.cargo=emptyCargo();if(r.phase==='outbound'){
  if(r.paused){r.waiting='Paused at home port';r.remaining=0;return;}
  const fuel=routeFuel(s,r);if(inventory(s,r.source).propellant<fuel){r.waiting='Waiting for propellant at '+facilityName(r.source);r.remaining=0;return;}
  const target=inventory(s,r.destination),c=s.colonies[facilityWorld(r.destination)],orbit=r.destination.startsWith('orbit:'),use=orbit?1:provisionUse(c,facilityWorld(r.destination)),reserveSeasons=({lean:2,balanced:4,secure:6})[r.reserve]||4;
  const targets={provisions:Math.max(orbit?36:0,use*(r.travel*2+reserveSeasons)),materials:r.materialReserve??(orbit?128:r.destination==='cinder'||r.destination==='nacre'?8:64),components:r.export==='components'?0:4,propellant:r.export==='propellant'?0:orbit?16:8};
  const order=r.priority==='components'?['provisions','components','materials','propellant']:r.priority==='propellant'?['provisions','propellant','materials','components']:['provisions','materials','components','propellant'];
  let room=r.capacity+(c?.upgrades.shelter?4:0);const stock=inventory(s,r.source),sourceCol=s.colonies[facilityWorld(r.source)],floor=r.source==='hearth'?{materials:0,provisions:12,propellant:fuel,components:0}:r.source.startsWith('orbit:')?{materials:0,provisions:4,propellant:fuel+2,components:2}:{materials:16,components:2,provisions:provisionUse(sourceCol,facilityWorld(r.source))*(sourceCol?.kind==='settlement'?GROWTH_POLICIES[sourceCol.city.policy].food:2),propellant:fuel+2};
  for(const key of order){const amount=Math.min(room,Math.max(0,targets[key]-target[key]),Math.floor(Math.max(0,stock[key]-floor[key])));r.cargo[key]=amount;room-=amount;}
  const returnStock=inventory(s,r.destination),returnFloor=r.export==='materials'?(r.materialReserve??64):r.export==='provisions'?Math.max(6,use*4):2;
  if(!cargoTotal(r.cargo)&&(r.export==='none'||returnStock[r.export]<=returnFloor)){r.waiting='Stores topped up · docked';r.remaining=0;return;}
  changeStock(s,r.source,{...r.cargo,propellant:r.cargo.propellant+fuel},-1);r.fuelSpent=(r.fuelSpent||0)+fuel;
 }else{
  const stock=inventory(s,r.destination),key=r.export,keep=key==='provisions'?Math.max(6,provisionUse(s.colonies[facilityWorld(r.destination)],facilityWorld(r.destination))*4):['propellant','components'].includes(key)?2:(r.materialReserve??(r.destination==='cinder'||r.destination==='nacre'?8:64));
  const destinationCol=s.colonies[r.destination],urbanFloor=destinationCol?.kind==='settlement'?(key==='materials'?GROWTH_POLICIES[destinationCol.city.policy].materials:key==='provisions'?GROWTH_POLICIES[destinationCol.city.policy].food*provisionUse(destinationCol,r.destination):0):0;
  if(key!=='none')r.cargo[key]=Math.min(r.capacity,Math.floor(Math.max(0,stock[key]-Math.max(keep,urbanFloor))));changeStock(s,r.destination,r.cargo,-1);
 }
 r.waiting=null;r.remaining=r.travel;
}
export function commissionService(state,destination,source='hearth',options={}){
 if(!facilities(state).includes(source)||!facilities(state).includes(destination)||source===destination)throw Error('Both ports must exist.');if(allServices(state).some(r=>r.source===source&&r.destination===destination))throw Error('This connection already has a service.');
 const available=state.fleet.find(f=>f.status==='available'&&f.location===source),cost=available?12:28;if(inventory(state,source).materials<cost)throw Error(`Commissioning needs ${cost} materials at ${facilityName(source)}.`);
 const s=copy(state);changeStock(s,source,{materials:cost},-1);const hull=available?s.fleet.find(f=>f.id===available.id):null;if(hull)hull.status='service';
 const rook=source==='hearth'&&destination==='cinder',id=rook?'ore-service':'service-'+(s.turn+1)+'-'+(s.services.length+1),travel=Math.max(1,Math.ceil(travelBetween(source,destination)/2));
 const r={id,name:hull?.name||facilityName(destination)+' Runner',hullId:hull?.id||id,source,destination,capacity:8,travel,period:travel*2,phase:'outbound',remaining:0,cargo:emptyCargo(),delivered:0,totals:emptyCargo(),trips:0,priority:options.priority||'materials',export:options.export||(facilityWorld(destination)==='nacre'?'propellant':'materials'),reserve:'balanced',materialReserve:destination==='cinder'||destination==='nacre'?8:destination.startsWith('orbit:')?128:64,paused:false,waiting:null,commissioned:s.turn};
 if(!hull)s.fleet.push({id,name:r.name,design:{...PRESETS.carrier},location:source,status:'service',launched:s.turn,flights:0});if(rook)s.route=r;else s.services.push(r);loadRoute(s,r);milestone(s,'service:'+id,'A regular connection',`${r.name} now serves ${facilityName(source)} and ${facilityName(destination)}. Supplies and return cargo will move through its hold.`);return s;
}
export function openRoute(s){if(!s.colonies.cinder?.mine)throw Error('Establish the Rook extractor first.');return commissionService(s,'cinder');}
export function configureService(state,id,patch){const allowed={priority:['materials','propellant','components'],export:['materials','provisions','propellant','components','none'],reserve:['lean','balanced','secure']};const s=copy(state),r=allServices(s).find(r=>r.id===id);if(!r)throw Error('Service not found.');for(const [k,v]of Object.entries(patch)){if(k==='materialReserve'&&[8,32,64,128].includes(v))r[k]=v;else if(k==='paused'&&typeof v==='boolean')r[k]=v;else if(allowed[k]?.includes(v))r[k]=v;else throw Error('Invalid service order.');}if(r.remaining===0)loadRoute(s,r);return s;}
export function upgradeRoute(state,id='ore-service'){const s=copy(state),r=allServices(s).find(r=>r.id===id);if(!r||r.capacity>=16)throw Error('No eligible freighter.');if(inventory(s,r.source).materials<26)throw Error('Expansion needs 26 materials at its home port.');changeStock(s,r.source,{materials:26},-1);r.capacity+=4;log(s,'A larger freighter',`${r.name} can now carry ${r.capacity} units. Its current manifest is unchanged.`,'trade');return s;}
export function buildStation(state,id){const c=state.colonies[id];if(!c||c.kind==='automated')throw Error('A crewed colony must assemble the depot.');if(state.stations[id])throw Error('A depot is already present or under construction.');const cost={materials:32,provisions:8,propellant:8};if(!stocked(state,id,cost))throw Error('The depot needs 32 local materials, 8 provisions and 8 propellant.');const s=copy(state);changeStock(s,id,cost,-1);s.stations[id]={name:WORLDS[id].name+' Anchorage',materials:8,provisions:8,propellant:8,components:0,building:3,built:null,crew:2,supported:true};log(s,'Orbital assembly begins',`${WORLDS[id].name} has committed a construction tender and stores. Three supported seasons until the depot opens.`,'build');return s;}
function receiveServices(s){for(const r of allServices(s)){if(r.remaining<=0)continue;r.remaining--;if(r.remaining)continue;const dest=r.phase==='outbound'?r.destination:r.source;changeStock(s,dest,r.cargo);recordCityFreight(s,r,cargoTotal(r.cargo));if(cargoTotal(r.cargo)){log(s,'Cargo received',`${r.name} at ${facilityName(dest)}: ${r.cargo.materials} materials, ${r.cargo.provisions} provisions, ${r.cargo.propellant} propellant, ${r.cargo.components||0} energy parts.`,'trade');milestone(s,'first-delivery:'+r.id,'The first regular delivery',`${r.name} delivered real cargo to ${facilityName(dest)}.`);}for(const k of Object.keys(r.totals))r.totals[k]+=r.cargo[k];if(r.phase==='return'){r.delivered+=r.cargo.materials;r.trips++;const hull=s.fleet.find(f=>f.id===r.hullId);if(hull)hull.flights++;}r.cargo=emptyCargo();r.phase=r.phase==='outbound'?'return':'outbound';}}
export function endTurn(state){
 const s=copy(state);s.turn++;s.materials+=6;s.home.provisions+=6;s.home.propellant+=3;s.home.components=(s.home.components||0)+1;receiveServices(s);
 const homeYield=improvementYield(s,'hearth');s.materials+=homeYield.materials;s.research+=homeYield.research;const homeParts=Math.min(homeYield.factories,Math.floor(s.materials));s.materials-=homeParts;s.home.components+=homeParts;
 const forecasts={};
 for(const [id,c]of Object.entries(s.colonies)){
  const f=colonyForecast(s,s.turn,id,false);forecasts[id]=f;c.maintenanceDue=!!f.maintenance&&!f.fed;c.supplies=f.reserve;c.materials+=f.materials-f.maintenance*(f.fed?1:0);c.propellant+=f.propellant;c.components=(c.components||0)+f.components;s.research+=f.research;c.development+=f.growth;c.population+=f.arrivals;c.ore=c.materials;
  if(f.arrivals&&c.population>12)milestone(s,'households:'+id,'People choose to stay',`${WORLDS[id].name} welcomes its first new permanent residents. Local work, housing and reserves made this possible.`);
  if(f.food&&f.fed)milestone(s,'harvest:'+id,'The first local harvest',`${WORLDS[id].name} grew provisions for its own people.`);
  if(!f.fed){c.shortages++;if(c.shortages===1)log(s,WORLDS[id].name+' needs support',c.kind==='automated'?'The condensers need maintenance material. Production pauses until a delivery arrives.':'Reserves are exhausted. Growth, construction and extraction pause; bring provisions or assign growers.','warning');}else{if(c.shortages)log(s,'Work resumes on '+WORLDS[id].name,'A restored reserve lets the community continue.','arrival');c.shortages=0;}
  if(c.project&&f.work){c.project.remaining=Math.max(0,c.project.remaining-f.work);if(!c.project.remaining){const p=c.project.id;c.upgrades[p]=true;c.project=null;if(p==='housing'){c.capacity+=12;if(c.kind!=='settlement'){c.kind='settlement';c.population=Math.max(6,c.population);c.people.push({name:'Ren Ash',role:'Resident coordinator',arrived:s.turn});}}milestone(s,'project:'+id+':'+p,PROJECTS[p].name+' complete',`${WORLDS[id].name}: the works you commissioned are now ready.`);}}
  for(const e of advanceCity(s,id,f))milestone(s,'city:'+id+':'+e.key,e.title,e.text);
 }
 for(const [id,st]of Object.entries(s.stations)){if(st.building){if(forecasts[id]?.fed)st.building--;if(!st.building){st.built=s.turn;milestone(s,'station:'+id,st.name+' opens','Orbital assembly reduces new ship costs by 25%; departures use less propellant. A tender will keep its stores supplied.');const tender={id:'tender-'+id,name:WORLDS[id].name+' Tender',hullId:'tender-'+id,source:id,destination:'orbit:'+id,capacity:12,travel:1,period:2,phase:'outbound',remaining:0,cargo:emptyCargo(),delivered:0,totals:emptyCargo(),trips:0,priority:'propellant',export:'none',reserve:'balanced',materialReserve:128,paused:false,waiting:null,commissioned:s.turn};s.services.push(tender);}}else{st.supported=st.provisions>=1;st.provisions=Math.max(0,st.provisions-1);}}
 const m=s.mission;if(m){m.elapsed++;m.remaining--;if(m.remaining<=0){if(m.phase==='outbound'&&m.kit==='survey'){if(!s.surveys[m.destination])s.research+=3;s.surveys[m.destination]=true;m.phase='return';m.remaining=m.travel;milestone(s,'survey:'+m.destination,WORLDS[m.destination].name+' surveyed',`${m.name} charts the landing sites. +3 knowledge for the program.`);}else if(m.phase==='return'){if(m.legacyRefund)changeStock(s,m.source,{materials:m.legacyRefund});log(s,'Home again',`${m.name} returns to ${facilityName(m.source)}. Commission a service here to reuse this vessel for 12 materials.`,'arrival');finish(s,m,true);}else if(m.phase==='outbound'&&m.deployment){m.phase='deploy';m.remaining=m.deployment;log(s,'Setting up camp',`${m.name} unfolds its arrays on ${WORLDS[m.destination].name}.`,'arrival');}else deploy(s,m);}}
 // Knowledge automatically funds the next discovery, in a visible fixed order.
 for(const [id,t]of Object.entries(TECHNOLOGIES).sort(([a],[b])=>['navigation','cargo','propulsion'].indexOf(a)-['navigation','cargo','propulsion'].indexOf(b)))if(!s.tech[id]){if(s.research<t.cost)break;s.research-=t.cost;s.tech[id]=true;milestone(s,'discovery:'+id,t.name+' discovered',t.description);}
 for(const r of allServices(s))if(r.remaining<=0)loadRoute(s,r);
 for(const c of Object.values(s.colonies))c.ore=c.materials;
 const p=s.colonies.pelagos;if(!s.won&&p&&p.policy&&p.development>=8&&p.supplies>=provisionUse(p,'pelagos')*2&&allServices(s).some(r=>r.trips>0)){s.won=true;milestone(s,'second-home','Our second home','A community with a future, supported by the network you built. The next expedition can begin here.');}
 return s;
}
export function objectives(s){return[{label:'Survey Rook',done:s.surveys.cinder},{label:'Establish extraction and a cargo service',done:!!s.route},{label:'Survey Pelagos',done:s.surveys.pelagos},{label:'Found a settlement on Pelagos',done:!!s.colonies.pelagos},{label:'Choose its first community investment',done:!!s.colonies.pelagos?.policy},{label:'Support a lasting second home',done:s.won}];}
export function guidance(s){
 const order=(title,text,world,kit=null,section=null,preset=null)=>({title,text,world,kit,section,preset});
 if(s.mission)return order(s.mission.name+' in flight',`Advance the season. ${s.mission.remaining} seasons to ${s.mission.phase==='return'?'return':s.mission.phase==='deploy'?'deployment':'arrival'}.`,s.mission.destination,null,'mission');
 const short=Object.entries(s.colonies).find(([,c])=>c.shortages>0);if(short)return order('Support '+WORLDS[short[0]].name,'Local work is paused. Plan a supply delivery and check the regular connection.',short[0],'supply');
 if(!s.surveys.cinder)return order('Survey Rook','Map the moon. The returning vessel can lead your first cargo relay.','cinder','survey');
 if(!s.colonies.cinder)return order('Establish the Rook outpost','Send an extraction kit. Its sealed crew will need provisions.','cinder','mine');
 if(!s.route)return order('Connect the outpost','Commission a relay: provisions out, materials home.','cinder',null,'network');
 if(!s.surveys.pelagos)return order('Survey Pelagos','Two tanks and an efficient drive cover the return journey.','pelagos','survey','', 'scout');
 if(!s.colonies.pelagos)return order('Found a second home','Send twelve settlers, three cargo pods and a construction reserve.','pelagos','habitat',null,'pioneer');
 if(!allServices(s).some(r=>r.destination==='pelagos'))return order('Connect Pelagos','Set up dependable provisions and construction deliveries.','pelagos',null,'network');
 if(!s.colonies.pelagos.policy)return order('Choose the first shared investment','Use 20 local materials for housing or an observatory.','pelagos',null,'community');
 if(!s.colonies.pelagos.greenhouse)return order('Grow food on Pelagos','Deliver an enclosed farm to reduce dependence on food imports.','pelagos','greenhouse');
 if(!s.colonies.pelagos.city?.civic)return order('Grow your first town','Support 24 residents through local work and supplies. Homes grow around the economy you create.','pelagos',null,'city');
 if(!s.surveys.nacre)return order('Survey the ice moon','Nacre can supply propellant to the growing network.','nacre','survey',null,'scout');
 if(!s.colonies.nacre)return order('Open the Nacre condensers','Automated extraction produces propellant without a resident food demand.','nacre','mine');
 if(!s.stations.pelagos)return order('Build an orbital depot','Stock a local hub for cheaper onward expeditions.','pelagos',null,'network');
 const uncharted=Object.keys(WORLDS).find(id=>!s.surveys[id]);if(uncharted)return order('Explore '+WORLDS[uncharted].name,'Choose a vessel and review its range before launch.',uncharted,'survey',null,'scout');
 return order('Shape your settlements','Choose local construction, regional installations or new connections.','pelagos',null,'construction');
}
export function nextIncome(s){const y=improvementYield({...s,turn:s.turn+1},'hearth'),incoming=arrivingCargo(s,'hearth').materials;return 6+y.materials+incoming-Math.min(y.factories,Math.floor(s.materials+6+y.materials+incoming));}

export function validateSave(x){
 const num=(n,max=1e9)=>Number.isFinite(n)&&n>=0&&n<=max,object=v=>v&&typeof v==='object'&&!Array.isArray(v),fail=msg=>{throw Error(msg||'This is not a compatible First Light save.');};
 if(!object(x)||![1,2,3,4,5,6,7].includes(x.version)||!Number.isInteger(x.turn)||!num(x.turn,100000)||!num(x.materials)||!object(x.surveys)||!object(x.colonies)||!Array.isArray(x.logs)||!Array.isArray(x.history)||!Number.isInteger(x.launched)||!num(x.launched))fail();
 const s=copy(x),legacy=s.version<5,oldCity=s.version<6,oldResources=s.version<7;
 if(legacy){
  s.universe={seed:s.universe?.seed||CLUSTER_SEED,version:GENERATOR_VERSION};s.research=s.research??3*(Number(!!s.surveys.cinder)+Number(!!s.surveys.pelagos));s.tech={navigation:false,cargo:false,propulsion:false,...s.tech};s.home={provisions:80,propellant:30};s.stations={};s.services=[];s.fleet=[];s.chronicle=[];s.improvements=s.improvements||{};
  for(const id of Object.keys(WORLDS))s.surveys[id]=!!s.surveys[id];
  for(const [id,c]of Object.entries(s.colonies)){if(!WORLDS[id]||id==='hearth'||!object(c)||!validDesign(c.design))fail('A saved settlement is invalid.');if(id==='cinder')c.site='coast';c.regionId=id+':'+c.site;c.policy=c.policy??(id==='pelagos'?s.policy:null);c.focus=c.focus||'balanced';c.upgrades=c.upgrades||{};c.project=c.project||null;c.kind=id==='cinder'?'outpost':'settlement';c.capacity=Math.max(12,c.population)+(c.policy==='housing'?12:0);c.materials=24+(id==='cinder'?c.ore:0);c.propellant=8;c.shortages=0;c.people=[{name:'Founding crew',role:'Original expedition',arrived:c.founded||0}];c.supplies=Math.max(c.supplies,provisionUse(c,id)*4);c.design.kit=c.design.kit||(id==='cinder'?'mine':'habitat');s.chronicle.push({key:'founded:'+id,turn:c.founded||0,title:WORLDS[id].name+' · a foothold',text:c.founder+' founded this community.'});}
  if(s.mission){const m=s.mission;if(!WORLDS[m.destination])fail();m.source='hearth';if(m.destination==='cinder')m.site='coast';m.regionId=m.destination+':'+m.site;m.cargoMaterials=['mine','habitat'].includes(m.kit)?24:0;m.cargoPropellant=m.kit==='survey'?0:4;m.legacyRefund=m.kit==='survey'?Math.floor(m.base/2):0;}
  if(s.route){const r=s.route;if(!s.colonies.cinder?.mine)fail('The old ore route has no mine.');const cargo=r.cargo??(r.remaining===1?Math.min(x.colonies.cinder.ore,r.capacity):0);if(r.cargo===undefined)s.colonies.cinder.materials-=cargo;if(!num(cargo,r.capacity))fail('The old ore manifest is invalid.');Object.assign(r,{id:'ore-service',name:'Rook freighter',hullId:'ore-service',source:'hearth',destination:'cinder',travel:1,phase:r.remaining===1?'return':'outbound',remaining:1,cargo:{materials:cargo,provisions:0,propellant:0,components:0},totals:{materials:r.delivered,provisions:0,propellant:0,components:0},priority:'materials',export:'materials',reserve:'balanced',paused:false,waiting:null,commissioned:0});s.fleet.push({id:'ore-service',name:r.name,design:{...PRESETS.carrier},location:'hearth',status:'service',launched:0,flights:r.trips});}
  const moved={};for(const [rid,p]of Object.entries(s.improvements)){const id=rid.split(':')[0];if(!WORLDS[id]||!p||!REGIONAL_PROJECTS[p.kind]||!num(p.built)||!num(p.ready)||p.ready<p.built)fail('A saved regional project is invalid.');const old=regionById(id,rid,s.universe.seed),target=old&&regionalAllowed(old,p.kind)?old:regions(id,s.colonies[id]?.site||'coast',s.universe.seed).find(r=>!moved[r.id]&&regionalAllowed(r,p.kind));if(target)moved[target.id]=p;else if(s.colonies[id])s.colonies[id].materials+=REGIONAL_PROJECTS[p.kind].cost;else s.materials+=REGIONAL_PROJECTS[p.kind].cost;}s.improvements=moved;s.version=5;
  log(s,'A connected chapter','Your worlds, founders and flights are preserved. Each foothold received 24 commissioning materials, fuel and a short provision reserve for the new local economy. The nearby worlds now share four systems.','discovery');
 }
 if(oldCity){for(const c of Object.values(s.colonies))c.city=initialCity();s.version=6;}
 if(oldResources){s.home.components=8;for(const c of Object.values(s.colonies)){c.components=0;if(c.project)c.project.paidParts=0;}for(const st of Object.values(s.stations))st.components=0;for(const r of allServices(s)){r.cargo.components=0;r.totals.components=0;}if(s.mission)s.mission.cargoComponents=0;s.version=7;}
 if(!object(s.universe)||typeof s.universe.seed!=='string'||!s.universe.seed||s.universe.seed.length>128||s.universe.version!==GENERATOR_VERSION)fail('The saved geography is incompatible.');
 if(!object(s.home)||!num(s.home.provisions)||!num(s.home.propellant)||!num(s.home.components)||!object(s.stations)||!Array.isArray(s.services)||!Array.isArray(s.fleet)||!Array.isArray(s.chronicle)||!object(s.improvements)||!object(s.tech)||!num(s.research))fail('The saved program is invalid.');
 if(Object.keys(s.surveys).some(id=>!WORLDS[id])||Object.values(s.surveys).some(v=>typeof v!=='boolean')||Object.keys(WORLDS).some(id=>typeof s.surveys[id]!=='boolean')||Object.keys(s.tech).some(k=>!TECHNOLOGIES[k])||Object.values(s.tech).some(v=>typeof v!=='boolean'))fail('The saved charts are invalid.');
 for(const [id,c]of Object.entries(s.colonies)){
  if(!WORLDS[id]||id==='hearth'||!object(c)||!['coast','plateau'].includes(c.site)||c.regionId!==id+':'+c.site||!validDesign(c.design)||!FOCUSES[c.focus]||!['automated','outpost','settlement'].includes(c.kind)||![null,'housing','research'].includes(c.policy)||!object(c.upgrades)||Object.keys(c.upgrades).some(k=>!PROJECTS[k])||Object.values(c.upgrades).some(v=>typeof v!=='boolean')||!Array.isArray(c.people)||c.people.some(p=>typeof p.name!=='string'||typeof p.role!=='string'||!num(p.arrived)))fail('The saved colony is invalid.');
  for(const key of ['supplies','materials','propellant','components','population','capacity','development','shortages','founded'])if(!num(c[key]))fail('A local inventory is invalid.');
  if(c.population>c.capacity||!Number.isInteger(c.population)||typeof c.founder!=='string'||typeof c.mine!=='boolean'||typeof c.greenhouse!=='boolean')fail('The saved community is invalid.');
  const city=c.city;if(!object(city)||!GROWTH_POLICIES[city.policy]||!Number.isInteger(city.momentum)||!num(city.momentum,3)||!Array.isArray(city.freight)||city.freight.length>4||city.freight.some(e=>!Number.isInteger(e.turn)||!num(e.turn,s.turn)||!num(e.units))||!Array.isArray(city.plots)||city.plots.length>17||typeof city.civic!=='boolean'||city.lastEvent!==null&&(!object(city.lastEvent)||typeof city.lastEvent.text!=='string'||!num(city.lastEvent.turn,s.turn)))fail('The saved town is invalid.');
  const plotIds=new Set();for(const p of city.plots){if(!object(p)||typeof p.id!=='string'||plotIds.has(p.id)||!['agriculture','industry','trade','research','market','commons'].includes(p.kind)||typeof p.name!=='string'||p.name.length>80||![p.x,p.z,...(p.road||[])].every(n=>Number.isFinite(n)&&Math.abs(n)<1000)||!Array.isArray(p.road)||p.road.length!==4||!num(p.built,s.turn)||!Number.isInteger(p.remaining)||!num(p.remaining,2)||p.capacity!==(['commons','market'].includes(p.kind)?0:4)||p.kind==='commons'&&p.remaining!==0)fail('The saved neighborhood is invalid.');plotIds.add(p.id);}
  if(city.plots.filter(p=>p.remaining>0).length>1||city.plots.filter(p=>p.kind==='commons').length!==Number(city.civic)||city.plots.filter(p=>!p.remaining).reduce((n,p)=>n+p.capacity,0)>c.capacity)fail('The saved neighborhood capacity is invalid.');
  if(c.project){const p=c.project;if(!PROJECTS[p.id]||!num(p.remaining,3)||p.remaining<1||p.total!==PROJECTS[p.id].work||p.paid!==PROJECTS[p.id].cost||!num(p.paidParts,PROJECTS[p.id].parts||0)||p.remaining>p.total||c.upgrades[p.id])fail('The saved construction is invalid.');}
 }
 for(const [id,st]of Object.entries(s.stations)){if(!s.colonies[id]||typeof st.name!=='string'||!num(st.building,3)||!Number.isInteger(st.building)||typeof st.supported!=='boolean')fail('The saved depot is invalid.');for(const k of ['materials','provisions','propellant','components','crew'])if(!num(st[k]))fail('A depot inventory is invalid.');}
 const routeIds=new Set();for(const r of allServices(s)){
  if(!object(r)||typeof r.id!=='string'||routeIds.has(r.id)||typeof r.name!=='string'||!facilities(s).includes(r.source)||!facilities(s).includes(r.destination)||r.source===r.destination||![8,12,16].includes(r.capacity)||!Number.isInteger(r.travel)||r.travel<1||r.travel>5||r.period!==r.travel*2||!Number.isInteger(r.remaining)||r.remaining<0||r.remaining>r.travel||!['outbound','return'].includes(r.phase)||!['materials','propellant','components'].includes(r.priority)||!['materials','provisions','propellant','components','none'].includes(r.export)||!['lean','balanced','secure'].includes(r.reserve)||typeof r.paused!=='boolean'||!(r.waiting===null||typeof r.waiting==='string'))fail('The saved cargo route is invalid.');
  routeIds.add(r.id);for(const cargo of [r.cargo,r.totals]){if(!object(cargo)||Object.keys(cargo).some(k=>!['materials','provisions','propellant','components'].includes(k))||['materials','provisions','propellant','components'].some(k=>!num(cargo[k])))fail('The saved manifest is invalid.');}if(r.remaining===0&&cargoTotal(r.cargo)>0)fail('Docked cargo must finish unloading before saving.');if(r.materialReserve!==undefined&&![8,32,64,128].includes(r.materialReserve))fail('The material reserve is invalid.');if(cargoTotal(r.cargo)>r.capacity+4||!num(r.delivered)||!num(r.trips))fail('The saved freight history is invalid.');
 }
 if(s.mission){const m=s.mission;if(m.legacyRefund!==undefined&&(!num(m.legacyRefund)||m.legacyRefund>Math.floor(m.base/2)))fail('The saved hull recovery is invalid.');if(!validDesign(m.design)||!WORLDS[m.destination]||m.destination==='hearth'||!facilities(s).includes(m.source)||!KITS[m.kit]||!['coast','plateau'].includes(m.site)||m.regionId!==m.destination+':'+m.site||!['outbound','deploy','return'].includes(m.phase)||!Number.isInteger(m.remaining)||m.remaining<1||m.remaining>20||!num(m.travel,10)||m.travel<1||!num(m.elapsed)||!num(m.duration,30)||!num(m.base)||!num(m.supplies)||!num(m.cargoMaterials)||!num(m.cargoPropellant)||!num(m.cargoComponents)||typeof m.name!=='string')fail('The saved expedition is invalid.');}
 for(const [rid,p]of Object.entries(s.improvements)){const id=rid.split(':')[0],r=regionById(id,rid,s.universe.seed);if(!r||!REGIONAL_PROJECTS[p.kind]||!s.surveys[id]||!num(p.built)||!num(p.ready)||p.ready<p.built||!regionalAllowed(r,p.kind))fail('A saved regional installation is invalid.');}
 for(const l of [...s.logs,...s.chronicle])if(typeof l.title!=='string'||typeof l.text!=='string'||!num(l.turn))fail('The expedition record is invalid.');
 for(const f of s.fleet)if(typeof f.name!=='string'||typeof f.id!=='string'||!validDesign(f.design)||!['available','service','founder'].includes(f.status)||!num(f.flights))fail('The saved vessel record is invalid.');
 return s;
}
