import {clamp,lerp,smooth} from './math.js';
export {clamp,lerp,smooth};
export const FIXED=1/60, BOUNDS={x:35,zMin:-38,zMax:34};
export const weapons=[{name:'Morrow carbine',short:'CARBINE',mag:24,interval:.13,damage:34,speed:105,spread:.007,reload:1.65},{name:'Trench SMG',short:'SMG',mag:32,interval:.078,damage:22,speed:85,spread:.020,reload:1.85}];
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function rng(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
const craters=[[-12,7,3.8],[-8,-1,3.9],[-14,-8,3.4],[4,6,4.2],[12,-1,3.9],[22,7,3.3],[20,-9,3.0],[-26,-4,3.2],[0,-5,2.7],[9,25,3],[-19,26,2.6],[25,-27,3.2]];
export class Battlefield{
 constructor(){this.craters=craters.map(([x,z,r])=>({x,z,r}));this.blocks=[];this.width=72;this.depth=78;this.grid=new Float32Array(73*79);for(let iz=0;iz<=78;iz++)for(let ix=0;ix<=72;ix++)this.grid[iz*73+ix]=this.raw(ix-36,iz-40);this.makeBlocks()}
 raw(x,z){let h=.07*Math.sin(x*.28)*Math.cos(z*.19)+.025*Math.sin(x*.8+z*.4);const trench=(center)=>-1.03*(1-smooth(2,3.7,Math.abs(z-center)))*(1-smooth(26,30,Math.abs(x)));h+=trench(18)+trench(-16);const ditchX=-25+Math.sin(z*.1)*1.4;h-=.78*(1-smooth(1,3.0,Math.abs(x-ditchX)))*(1-smooth(18,25,Math.abs(z)));for(const c of this.craters){const d=Math.hypot(x-c.x,z-c.z)/c.r;if(d<1.4)h+=-.90*(1-smooth(.1,1,d))+.25*Math.exp(-(((d-1.03)*5)**2))}return h}
 height(x,z){const gx=clamp(x+36,0,71.999),gz=clamp(z+40,0,77.999),ix=Math.floor(gx),iz=Math.floor(gz),u=gx-ix,v=gz-iz,a=this.grid[iz*73+ix],b=this.grid[iz*73+ix+1],c=this.grid[(iz+1)*73+ix],d=this.grid[(iz+1)*73+ix+1];return u+v<1?a+(b-a)*u+(c-a)*v:d+(c-d)*(1-u)+(b-d)*(1-v)}
 add(x,z,w,d,h,type='bags'){const y=this.height(x,z);this.blocks.push({id:this.blocks.length,x,z,w,d,h,y,type,hp:type==='bags'?155:1e9,destroyed:false})}
 makeBlocks(){for(const z of [14,-12]){for(const x of [-20,-16,-12,-4,0,4,12,16,20,24])this.add(x,z,3.6,.78,.68)}
 // The broken signal house leaves a south entrance and two flanking approaches.
 this.add(5,-25,9,.8,2.7,'stone');this.add(9.2,-22,.8,6,2.1,'stone');this.add(.8,-23,.8,3.8,1.9,'stone');this.add(1.8,-19.8,2.8,.8,1.45,'stone');
 this.add(-3,2,2.5,1.1,1.65,'stone');this.add(15,5,2,1.4,1.1,'stone');this.add(-17,-5,2.4,.9,.62);this.add(9,-4,2.4,.8,.6);this.add(-22,2,2,.7,.6);this.add(22,-19,3.4,.9,.7);
 this.add(-17,20,1.5,1.2,.85,'crate');this.add(18,20,1.5,1.2,.85,'crate');}
 blocked(x,z,r=.36,vault=false){const y=this.height(x,z);for(const b of this.blocks)if(!b.destroyed&&!(vault&&b.h<1)&&Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r&&y+1.0>b.y&&y<b.y+b.h)return b;return null}
}
export function segmentBox(a,b,min,max){let lo=0,hi=1;for(const k of ['x','y','z']){const d=b[k]-a[k];if(Math.abs(d)<1e-8){if(a[k]<min[k]||a[k]>max[k])return null}else{let t1=(min[k]-a[k])/d,t2=(max[k]-a[k])/d;if(t1>t2)[t1,t2]=[t2,t1];lo=Math.max(lo,t1);hi=Math.min(hi,t2);if(lo>hi)return null}}return lo}
export function bodyHeight(a){return 1.82-a.crouch*.58}
export function muzzle(a){const sn=Math.sin(a.heading),cs=Math.cos(a.heading),f=1.37-a.recoil*.07;return{x:a.x+sn*f+cs*.22,y:a.y+bodyHeight(a),z:a.z+cs*f-sn*.22}}
export function trace(world,a,b,actors=[],exclude=null){let nearest=1,hit=null;for(const block of world.blocks){if(block.destroyed)continue;const t=segmentBox(a,b,{x:block.x-block.w/2,y:block.y-.15,z:block.z-block.d/2},{x:block.x+block.w/2,y:block.y+block.h,z:block.z+block.d/2});if(t!==null&&t<nearest){nearest=t;hit={type:'cover',block}}}
 for(const actor of actors){if(actor.dead||actor===exclude)continue;const h=bodyHeight(actor)+.42;const t=segmentBox(a,b,{x:actor.x-.39,y:actor.y+.2,z:actor.z-.39},{x:actor.x+.39,y:actor.y+h,z:actor.z+.39});if(t!==null&&t<nearest){nearest=t;hit={type:'actor',actor}}}
 const length=Math.hypot(b.x-a.x,b.z-a.z,b.y-a.y),steps=Math.max(1,Math.ceil(length/.24));for(let i=0;i<=steps*nearest;i++){const t=i/steps,x=lerp(a.x,b.x,t),y=lerp(a.y,b.y,t),z=lerp(a.z,b.z,t);if(y<world.height(x,z)+.045){nearest=t;hit={type:'ground'};break}}
 return {...(hit||{type:'none'}),t:nearest,x:lerp(a.x,b.x,nearest),y:lerp(a.y,b.y,nearest),z:lerp(a.z,b.z,nearest)};
}
export class Battle{
 constructor(seed=107){this.random=rng(seed);this.world=new Battlefield();this.actors=[];this.bullets=[];this.shells=[];this.smokes=[];this.events=[];this.time=0;this.phase='advance';this.capture=0;this.hold=25;this.won=false;this.lost=false;this.kills=0;this.shots=0;this.hits=0;this.destroyed=0;this.counter=false;this.enemyBarrage=false;this.lastDamage=-99;this.objective={x:5,z:-22,r:4.5};this.player=this.actor(-12,18,'blue','player');this.player.ammo=[24,32];this.player.reserve=[168,160];this.player.weapon=0;this.player.stamina=100;this.player.barrages=3;this.player.smoke=3;this.player.bandages=2;this.actor(-14,18.4,'blue');this.actor(7,18,'blue');
 for(const [x,z,role] of [[-20,-15,'rifle'],[-12,-15,'rifle'],[-3,-15,'rifle'],[5,-15,'mg'],[16,-15,'rifle'],[23,-18,'rifle'],[4,-22,'rifle'],[-5,-23,'rifle']])this.actor(x,z,'red',role);this.events.push({type:'log',text:'Find a crossing. Your section will follow.'})}
 actor(x,z,team,role='rifle'){const a={id:this.actors.length,x,z,y:this.world.height(x,z),team,role,heading:team==='blue'?Math.PI:0,hp:role==='player'?100:role==='mg'?100:75,maxHp:role==='player'?100:role==='mg'?100:75,crouch:0,crouching:false,dead:false,recoil:0,moveSpeed:0,fireCooldown:.6+this.random()*1.3,reload:0,suppression:0,burst:0,think:.2+this.random(),target:null,peek:0,home:{x,z},ammoAI:24,vault:0,stepCooldown:0,phase:this.random()*6.28};this.actors.push(a);return a}
 event(type,data={}){this.events.push({...data,type})}
 reload(){const p=this.player,w=weapons[p.weapon];if(!p.dead&&!p.reload&&p.ammo[p.weapon]<w.mag&&p.reserve[p.weapon]>0){p.reload=w.reload;p.reloadWeapon=p.weapon;this.event('reload')}}
 switchWeapon(){const p=this.player;if(p.reload||p.dead)return;p.weapon=1-p.weapon;p.fireCooldown=.18;this.event('switch')}
 bandage(){const p=this.player;if(p.bandages>0&&p.hp<100&&!p.heal){p.heal=2.8;p.bandages--;this.event('log',{text:'Bandaging. Stay behind cover.'})}}
 vault(dx=0,dz=0){const p=this.player;if(p.stamina<22||p.stepCooldown>0||p.dead)return;const d=Math.hypot(dx,dz);p.vaultDX=d>.1?dx/d:Math.sin(p.heading);p.vaultDZ=d>.1?dz/d:Math.cos(p.heading);p.vault=.42;p.stepCooldown=.75;p.stamina-=22;p.heal=0;this.event('vault')}
 smokeAt(x,z){const p=this.player;if(p.smoke<1||p.dead)return false;const d=Math.hypot(x-p.x,z-p.z),t=Math.min(1,20/Math.max(1,d));x=p.x+(x-p.x)*t;z=p.z+(z-p.z)*t;p.smoke--;this.shells.push({x,z,y:0,t:1.05,max:1.05,team:'blue',smoke:true});this.event('throw');return true}
 artillery(x,z,team='blue'){const p=this.player;if(team==='blue'&&(p.barrages<1||p.dead||p.artCooldown>0))return false;if(team==='blue'){p.barrages--;p.artCooldown=5}for(let i=0;i<4;i++){const a=i*2.4,r=i===0?0:2.7;this.shells.push({x:clamp(x+Math.sin(a)*r,-33,33),z:clamp(z+Math.cos(a)*r,-36,32),t:2.6+i*.42,max:2.6+i*.42,team})}this.event('radio');this.event('log',{text:team==='blue'?'Fire mission confirmed. Clear the amber circle.':'Incoming artillery! Move out of the red circle.'});return true}
 smokeBlocked(a,b){for(const s of this.smokes){if(s.age<.6||s.age>12)continue;const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((s.x-a.x)*dx+(s.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);if(Math.hypot(a.x+dx*t-s.x,a.z+dz*t-s.z)<s.r)return true}return false}
 visible(a,b){if(this.smokeBlocked(a,b))return false;const from=muzzle(a),to={x:b.x,y:b.y+bodyHeight(b)-.04,z:b.z};return trace(this.world,from,to).type==='none'}
 move(a,dx,dz,dt,speed){const before={x:a.x,z:a.z},d=Math.hypot(dx,dz);if(d>.001){const amount=Math.min(1,d)*speed*dt;dx/=d;dz/=d;const n=Math.max(1,Math.ceil(amount/.15));for(let i=0;i<n;i++){const x=clamp(a.x+dx*amount/n,-33.5,33.5),z=clamp(a.z+dz*amount/n,-36.5,32.5);if(!this.world.blocked(x,a.z,.34,a.vault>0))a.x=x;if(!this.world.blocked(a.x,z,.34,a.vault>0))a.z=z}}a.moveSpeed=distance(a,before)/dt;a.y=this.world.height(a.x,a.z)+(a.vault>0?Math.sin((.42-a.vault)/.42*Math.PI)*.75:0)}
 shoot(a,target,accuracy=0){if(a.dead||a.reload||a.fireCooldown>0)return false;const isP=a===this.player,w=isP?weapons[a.weapon]:weapons[0];if(isP&&a.ammo[a.weapon]<=0){this.reload();return false}if(isP){a.ammo[a.weapon]--;this.shots++}else if(a.ammoAI--<=0){a.reload=1.8;a.ammoAI=24;return false}
 const start=muzzle(a),distanceXZ=Math.hypot(target.x-start.x,target.z-start.z),s=w.spread+accuracy+(isP?(a.moveSpeed>1?.018:0)+a.recoil*.025+(a.suppression*.012):0),angle=Math.atan2(target.x-start.x,target.z-start.z)+(this.random()-.5)*s*2;
 const dy=(target.y-start.y)/Math.max(2,distanceXZ)+(this.random()-.5)*s*.6,cs=1/Math.sqrt(1+dy*dy),v=w.speed;const b={x:start.x,y:start.y,z:start.z,ox:start.x,oy:start.y,oz:start.z,vx:Math.sin(angle)*v*cs,vy:dy*v*cs,vz:Math.cos(angle)*v*cs,life:.8,owner:a,damage:isP?w.damage:a.team==='blue'?16:9};
 // The shoulder-to-muzzle segment prevents a barrel from tunnelling through cover.
 const obstruction=trace(this.world,{x:a.x,y:start.y,z:a.z},start);if(obstruction.type!=='none'){this.event('impact',{...obstruction});if(isP)this.event('blocked')}else this.bullets.push(b);
 a.fireCooldown=isP?w.interval:a.role==='mg'?.13:.19;a.recoil=Math.min(1,a.recoil+.27);a.peek=.8;this.event('shot',{actor:a,start,weapon:isP?a.weapon:0});return true}
 damage(a,value,from=null){if(a.dead)return;if(a===this.player){if(this.time<(a.invulnerable||0))return;this.lastDamage=this.time;a.heal=0;this.event('hurt',{from})}a.hp=Math.max(0,a.hp-value);a.suppression=Math.min(1,a.suppression+.4);if(a.hp<=0){a.dead=true;a.deathTime=this.time;if(a.team==='red')this.kills++;this.event('down',{actor:a});if(a===this.player){this.lost=true;this.event('log',{text:'Your section has lost its lead. Regroup and try again.'})}}}
 explode(s){if(s.smoke){this.smokes.push({x:s.x,z:s.z,r:4.8,age:0});this.event('smoke',{x:s.x,z:s.z});return}const y=this.world.height(s.x,s.z);this.event('explosion',{x:s.x,y,z:s.z,team:s.team});for(const a of this.actors){if(a.dead)continue;const d=distance(a,s);if(d<6){const shield=trace(this.world,{x:s.x,y:y+1.3,z:s.z},{x:a.x,y:a.y+.6,z:a.z}).type!=='none';const damage=130*(1-d/6)*(shield?.27:1);this.damage(a,damage,{x:s.x,z:s.z});a.suppression=1}}
 for(const b of this.world.blocks){if(b.destroyed||b.type!=='bags')continue;const d=distance(b,s);if(d<5){b.hp-=170*(1-d/5);if(b.hp<=0){b.destroyed=true;this.destroyed++;this.event('coverDown',{block:b})}}}this.smokes.push({x:s.x,z:s.z,r:2,age:9,blast:true})}
 updateAI(a,dt){if(a.dead)return;a.think-=dt;a.peek=Math.max(0,a.peek-dt);const p=this.player,enemyTeam=a.team==='red'?'blue':'red';if(a.think<=0){a.think=.20+this.random()*.18;const candidates=this.actors.filter(t=>!t.dead&&t.team===enemyTeam&&distance(a,t)<46&&this.visible(a,t));candidates.sort((b,c)=>distance(a,b)-distance(a,c));a.target=candidates[0]||null;}
 let dx=0,dz=0;if(a.target){const t=a.target;a.heading=Math.atan2(t.x-a.x,t.z-a.z);const d=distance(a,t);if(a.suppression>.52&&a.peek<=0){a.crouching=true;a.burst=0;a.fireCooldown=Math.max(a.fireCooldown,.5)}else{a.crouching=false;if(a.fireCooldown<=0&&this.visible(a,t)){if(a.burst<=0){a.burst=a.role==='mg'?5:3;a.aimSnapshot={x:t.x+(this.random()-.5)*1.6,y:t.y+bodyHeight(t)-.10,z:t.z+(this.random()-.5)*1.6};a.fireCooldown=.34+this.random()*.26;a.peek=1.2}else{this.shoot(a,a.aimSnapshot,.020+d*.001+(a.suppression*.07));a.burst--;if(a.burst===0)a.fireCooldown=.9+this.random()*.85}}}
 // Support moves once the player has crossed; the MG holds its firing lane.
 if(d>18&&a.role!=='mg'&&(a.team==='blue'&&p.z<7||a.counter)){const dest=a.counter&&a.route?.length?a.route[0]:t;while(a.counter&&a.route?.length&&distance(a,a.route[0])<1.2)a.route.shift();dx=dest.x-a.x;dz=dest.z-a.z}
 }else{a.crouching=false;let destination=null;if(a.team==='blue'){destination=p.z<6?{x:p.x+(a.id%2?-3:3),z:p.z+3}:a.home}else if(a.counter){while(a.route?.length&&distance(a,a.route[0])<1.2)a.route.shift();destination=a.route?.[0]||this.objective;}if(destination&&distance(a,destination)>2){dx=destination.x-a.x;dz=destination.z-a.z;a.heading=Math.atan2(dx,dz)}}
 if(dx||dz){const d=Math.hypot(dx,dz);dx/=d;dz/=d;const next=this.world.blocked(a.x+dx*.7,a.z+dz*.7);if(next){if(next.h<1){a.vault=.18}else{dx=Math.sign(a.x-next.x)||1;dz=0}}}this.move(a,dx,dz,dt,a.team==='blue'?3.4:2.5)}
 update(dt,input={}){if(this.won||this.lost)return;this.time+=dt;const p=this.player;for(const a of this.actors){a.fireCooldown-=dt;a.recoil=Math.max(0,a.recoil-dt*2.5);a.suppression=Math.max(0,a.suppression-dt*.19);a.stepCooldown=Math.max(0,a.stepCooldown-dt);a.vault=Math.max(0,a.vault-dt);if(a.reload>0){a.reload-=dt;if(a.reload<=0){a.reload=0;if(a===p){const w=weapons[p.reloadWeapon],n=Math.min(w.mag-p.ammo[p.reloadWeapon],p.reserve[p.reloadWeapon]);p.ammo[p.reloadWeapon]+=n;p.reserve[p.reloadWeapon]-=n;this.event('loaded')}}}}
 p.artCooldown=Math.max(0,(p.artCooldown||0)-dt);p.peek=Math.max(0,p.peek-dt);const mx=input.mx||0,mz=input.mz||0,fire=!!input.fire;let aim=input.aim||{x:p.x+Math.sin(p.heading)*20,z:p.z+Math.cos(p.heading)*20};p.heading=Math.atan2(aim.x-p.x,aim.z-p.z);p.crouching=!!input.crouch;p.sprinting=!!input.sprint&&!fire&&!input.steady&&!p.crouching&&p.stamina>2&&Math.hypot(mx,mz)>.05;
 const peek=fire||input.steady;p.crouch=lerp(p.crouch,p.crouching&&!peek?1:0,Math.min(1,dt*16));const speed=p.sprinting?7.2:p.crouching?2.2:input.steady?2.9:4.5;this.move(p,p.vault>0?p.vaultDX:mx,p.vault>0?p.vaultDZ:mz,dt,p.vault>0?10:speed);p.stamina=clamp(p.stamina+(p.sprinting?-21:15)*dt,0,100);
 if(fire&&!p.vault){const targetActor=input.target||null;let target={x:aim.x,z:aim.z,y:targetActor?targetActor.y+bodyHeight(targetActor)-.02:this.world.height(aim.x,aim.z)+1.4};this.shoot(p,target,input.steady?-.003:0)}
 if(p.heal>0){p.heal-=dt;if(p.heal<=0){p.heal=0;p.hp=Math.min(100,p.hp+65);this.event('log',{text:'Bandage complete.'})}}
 // Quiet recovery restores only the last quarter; bandages remain meaningful.
 if(this.time-this.lastDamage>9&&p.hp<35)p.hp=Math.min(35,p.hp+3*dt);
 for(const a of this.actors){if(a===p)continue;this.updateAI(a,dt);a.crouch=lerp(a.crouch,a.crouching?1:0,Math.min(1,dt*10))}
 for(let i=this.bullets.length-1;i>=0;i--){const b=this.bullets[i],to={x:b.x+b.vx*dt,y:b.y+b.vy*dt,z:b.z+b.vz*dt},targets=this.actors.filter(a=>a.team!==b.owner.team),hit=trace(this.world,b,to,targets,b.owner);b.ox=b.x;b.oy=b.y;b.oz=b.z;b.x=hit.x;b.y=hit.y;b.z=hit.z;b.life-=dt;
 for(const a of targets){if(a.dead)continue;const dx=b.x-b.ox,dz=b.z-b.oz,t=clamp(((a.x-b.ox)*dx+(a.z-b.oz)*dz)/(dx*dx+dz*dz||1),0,1),d=Math.hypot(a.x-(b.ox+dx*t),a.z-(b.oz+dz*t));if(d<1.7){a.suppression=Math.min(1,a.suppression+dt*5);if(a===p&&this.random()<.07)this.event('whiz')}}
 if(hit.type!=='none'){if(hit.actor){this.damage(hit.actor,b.damage,b.owner);if(b.owner===p){this.hits++;this.event('hit',{dead:hit.actor.dead})}}this.event('impact',{...hit});this.bullets.splice(i,1)}else if(b.life<=0)this.bullets.splice(i,1)}
 for(let i=this.shells.length-1;i>=0;i--){this.shells[i].t-=dt;if(this.shells[i].t<=0){this.explode(this.shells[i]);this.shells.splice(i,1)}}for(let i=this.smokes.length-1;i>=0;i--){this.smokes[i].age+=dt;if(this.smokes[i].age>13)this.smokes.splice(i,1)}
 const inside=distance(p,this.objective)<this.objective.r,contested=this.actors.some(a=>a.team==='red'&&!a.dead&&distance(a,this.objective)<this.objective.r);
 if(this.phase==='advance'&&inside){this.phase='capture';this.event('log',{text:'Signal station reached. Clear it and stay in the circle.'})}
 if(this.phase==='capture'){if(inside&&!contested)this.capture+=dt;if(this.capture>=5){this.phase='hold';this.hold=25;this.counter=true;p.hp=Math.max(p.hp,80);p.reserve=[168,160];p.barrages=Math.max(p.barrages,1);p.smoke=Math.max(p.smoke,1);this.event('log',{text:'Station secured. Ammunition replenished. Hold for 25 seconds.'});for(const [x,z] of [[-10,-35],[-3,-34],[17,-34],[23,-29],[28,-24]]){const a=this.actor(x,z,'red');a.counter=true;const flank=x<5?-3:13;a.route=[{x:flank,z:-28},{x:flank,z:-17},{x:5,z:-17},{x:5,z:-22}]}}}
 if(this.phase==='hold'){if(inside&&!contested)this.hold-=dt;if(!this.enemyBarrage&&this.hold<17){this.enemyBarrage=true;this.artillery(p.x,p.z,'red')}if(this.hold<=0){this.won=true;this.event('victory')}}
 if(distance(p,{x:-16,z:22})<2.3&&this.time-(this.resupplyAt||-99)>15){p.hp=100;p.reserve=[168,160];p.bandages=Math.max(2,p.bandages);this.resupplyAt=this.time;this.event('log',{text:'Aid station: health and ammunition replenished.'})}
 }
 status(){const p=this.player;return{phase:this.phase,elapsed:this.time,health:Math.ceil(p.hp),ammo:p.ammo[p.weapon],reserve:p.reserve[p.weapon],kills:this.kills,enemies:this.actors.filter(a=>a.team==='red'&&!a.dead).length,capture:this.capture,hold:this.hold,won:this.won,lost:this.lost,position:{x:p.x,z:p.z}}}
}
