import {Battle,FIXED,weapons,distance,clamp,muzzle,bodyHeight,trace} from './engine.js';
import {View} from './render.js';
import {AudioScene} from './audio.js';
const $=id=>document.getElementById(id),canvas=$('battlefield'),overlay=$('overlay'),ctx=overlay.getContext('2d'),map=$('minimap'),mc=map.getContext('2d');
let battle=new Battle(),view,audio=new AudioScene(),started=false,paused=false,mode=null,previous=performance.now(),acc=0,lastUI=0,aim={x:-8,z:-15},target=null,mouse={x:innerWidth/2,y:innerHeight*.4,active:false,down:false,right:false},keys=new Set(),crouch=false,touchSprint=false,touchFire=false,padPrev=[],padFire=false,padConnected=false,lockTarget=null,inputMode='mouse',releaseFire=false,hitTime=0,hitDead=false,hurtTime=0,blockedTime=0,radio=[];
const sticks={move:{x:0,y:0},aim:{x:0,y:0}};let input={mx:0,mz:0,aim,fire:false};
function fatal(e){console.error(e);$('error').hidden=false;$('error').textContent='The battlefield could not start. Reload to try again. '+(e.message||e)}
try{view=new View(canvas,battle);document.body.dataset.renderer=view.software?'software':'webgl'}catch(e){fatal(e)}
const touchInitially=matchMedia('(pointer: coarse)').matches;document.body.classList.toggle('touch',touchInitially);
function resize(){view?.resize();overlay.width=innerWidth;overlay.height=innerHeight}window.addEventListener('resize',resize);resize();
function clearInput(){keys.clear();mouse.down=mouse.right=false;touchFire=false;touchSprint=false;padFire=false;for(const s of Object.values(sticks)){s.x=s.y=0}document.querySelectorAll('.stick i').forEach(el=>el.style.transform='');document.querySelectorAll('.stick').forEach(el=>el.classList.remove('active'))}
function start(sound=true){if(sound)audio.enable().then(()=>updateSound());started=true;paused=false;clearInput();$('briefing').hidden=true;$('pause-screen').hidden=true;$('result-screen').hidden=true;canvas.focus();previous=performance.now()}
function updateSound(){$('sound').textContent=audio.enabled?'SOUND ON':'SOUND OFF'}
function pause(value=!paused){if(!started||battle.won||battle.lost)return;paused=value;$('pause-screen').hidden=!value;if(value){clearInput();mode=null;setModeUI()}previous=performance.now();acc=0}
function restart(){location.reload()}
$('deploy').onclick=()=>start(true);$('quiet-deploy').onclick=()=>start(false);$('sound').onclick=async()=>{if(audio.enabled)audio.disable();else await audio.enable();updateSound()};$('pause').onclick=()=>pause();$('resume').onclick=()=>pause(false);$('restart').onclick=restart;$('again').onclick=restart;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};$('touch-toggle').onclick=()=>{document.body.classList.toggle('touch');$('touch-toggle').textContent=document.body.classList.contains('touch')?'Hide touch controls':'Show touch controls'};$('quality').onclick=()=>{$('quality').textContent='Graphics: '+view.toggleQuality()};
function setModeUI(){$('target-mode').hidden=!mode;document.querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('active',b.dataset.action===mode||b.dataset.action==='crouch'&&crouch));if(mode){$('mode-label').textContent=mode==='artillery'?'PLACE BARRAGE':'THROW SMOKE';$('mode-help').textContent=document.body.classList.contains('touch')?'Tap the ground to place · tap action again to cancel':'Aim, then fire to confirm · press action again to cancel'}}
function command(action){if(!started||paused||battle.won||battle.lost)return;if(action==='crouch'){crouch=!crouch;setModeUI()}if(action==='reload')battle.reload();if(action==='bandage')battle.bandage();if(action==='switch')battle.switchWeapon();if(action==='vault')battle.vault(input.mx,input.mz);if(action==='artillery'||action==='smoke'){const amount=action==='artillery'?battle.player.barrages:battle.player.smoke;if(amount>0){mode=mode===action?null:action;setModeUI();mouse.down=false}}}
function confirmMode(){if(!mode)return;const ok=mode==='artillery'?battle.artillery(aim.x,aim.z):battle.smokeAt(aim.x,aim.z);if(ok){releaseFire=true;mode=null;setModeUI();mouse.down=false;padFire=false;touchFire=false}}
function nearest(){const p=battle.player,list=battle.actors.filter(a=>a.team==='red'&&!a.dead&&battle.visible(p,a));list.sort((a,b)=>distance(p,a)-distance(p,b));lockTarget=list[0]||null;if(lockTarget){aim={x:lockTarget.x,z:lockTarget.z};target=lockTarget;mouse.active=false;inputMode='lock'}}
for(const el of document.querySelectorAll('[data-action]'))el.onclick=()=>command(el.dataset.action);$('vault-touch').onclick=()=>command('vault');$('switch-touch').onclick=()=>command('switch');
const sprintButton=$('sprint-touch');sprintButton.addEventListener('pointerdown',e=>{e.preventDefault();sprintButton.setPointerCapture(e.pointerId);touchSprint=true;sprintButton.classList.add('active')});for(const ev of ['pointerup','pointercancel','lostpointercapture'])sprintButton.addEventListener(ev,()=>{touchSprint=false;sprintButton.classList.remove('active')});
window.addEventListener('keydown',e=>{if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(mode){mode=null;setModeUI()}else pause();return}if(!started){if(e.code==='Enter')start();return}if(paused)return;keys.add(e.code);if(!e.repeat){const a={KeyC:'crouch',KeyR:'reload',KeyQ:'artillery',KeyG:'smoke',KeyH:'bandage',Space:'vault',KeyE:'switch'}[e.code];if(a)command(a);if(e.code==='Digit1'&&battle.player.weapon!==0)command('switch');if(e.code==='Digit2'&&battle.player.weapon!==1)command('switch');if(e.code==='Tab')nearest()}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(started&&!paused)pause(true);clearInput()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started)pause(true)});
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){mouse.x=e.clientX;mouse.y=e.clientY;mouse.active=true;inputMode='mouse';lockTarget=null}});canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(!started||paused)return;canvas.setPointerCapture(e.pointerId);mouse.x=e.clientX;mouse.y=e.clientY;if(e.button===2){mouse.right=true;return}if(e.pointerType==='mouse'){mouse.active=true;inputMode='mouse';lockTarget=null}if(mode){aim=view.groundPoint(e.clientX,e.clientY);confirmMode();return}if(e.pointerType==='mouse')mouse.down=true;else{const picked=view.pick(e.clientX,e.clientY);if(picked){lockTarget=picked;inputMode='lock';target=picked;aim={x:picked.x,z:picked.z}}else{aim=view.groundPoint(e.clientX,e.clientY);lockTarget=null}}});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{mouse.down=mouse.right=false});canvas.addEventListener('wheel',e=>{e.preventDefault();view.zoom=clamp(view.zoom+e.deltaY*.0007,.67,1.7)},{passive:false});
for(const name of ['move','aim']){const element=$(name+'-stick'),knob=element.querySelector('i');let pointer=null;function update(e){const r=element.getBoundingClientRect(),dx=e.clientX-(r.x+r.width/2),dy=e.clientY-(r.y+r.height/2),radius=r.width*.34,d=Math.hypot(dx,dy),scale=d>radius?radius/d:1;sticks[name].x=dx*scale/radius;sticks[name].y=dy*scale/radius;knob.style.transform=`translate(${dx*scale}px,${dy*scale}px)`;if(name==='aim'){inputMode='stick';lockTarget=null;mouse.active=false;const firing=Math.hypot(sticks.aim.x,sticks.aim.y)>.64;if(mode&&firing&&!touchFire){aim={x:battle.player.x+sticks.aim.x*22,z:battle.player.z+sticks.aim.y*22};confirmMode()}touchFire=firing}}element.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;element.setPointerCapture(pointer);element.classList.add('active');update(e)});element.addEventListener('pointermove',e=>{if(e.pointerId===pointer)update(e)});function end(e){if(e.pointerId!==pointer)return;pointer=null;sticks[name].x=sticks[name].y=0;knob.style.transform='';element.classList.remove('active');if(name==='aim')touchFire=false}for(const event of ['pointerup','pointercancel','lostpointercapture'])element.addEventListener(event,end)}
function getPad(){const pads=navigator.getGamepads?.()||[];return Array.from(pads).find(Boolean)}
function aimAssist(x,z){const p=battle.player,angle=Math.atan2(x,z);let picked=null,best=.16;for(const a of battle.actors){if(a.team!=='red'||a.dead||!battle.visible(p,a))continue;const delta=Math.abs(Math.atan2(Math.sin(Math.atan2(a.x-p.x,a.z-p.z)-angle),Math.cos(Math.atan2(a.x-p.x,a.z-p.z)-angle)));if(delta<best){best=delta;picked=a}}return picked}
function controls(){const p=battle.player;let mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),mz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),sprint=keys.has('ShiftLeft')||keys.has('ShiftRight')||touchSprint,steady=mouse.right,fire=mouse.down||touchFire;if(Math.hypot(sticks.move.x,sticks.move.y)>.12){mx=sticks.move.x;mz=sticks.move.y}
 const pad=getPad();padConnected=!!pad;if(pad){const pressed=pad.buttons.map(b=>b.pressed||b.value>.5),edge=i=>pressed[i]&&!padPrev[i],dz=v=>Math.abs(v)>.16?Math.sign(v)*(Math.abs(v)-.16)/.84:0;const px=dz(pad.axes[0]||0),pz=dz(pad.axes[1]||0),ax=dz(pad.axes[2]||0),az=dz(pad.axes[3]||0);if(edge(9)){if(!started)start();else pause()}if(started&&!paused){if(px||pz){mx=px;mz=pz}if(Math.hypot(ax,az)>.15){inputMode='pad';mouse.active=false;lockTarget=null;target=mode?null:aimAssist(ax,az);aim=target?{x:target.x,z:target.z}:{x:p.x+ax*27,z:p.z+az*27}}sprint||=pressed[4];steady||=pressed[6];if(edge(0)||edge(10))command('vault');if(edge(1)){if(mode){mode=null;setModeUI()}else command('crouch')}if(edge(2))command('reload');if(edge(3))command('artillery');if(edge(5))command('smoke');if(edge(15))command('switch');if(edge(13))command('bandage');if(edge(11))nearest();if(mode&&edge(7))confirmMode();else fire||=pressed[7];padFire=pressed[7]}padPrev=pressed}else{padPrev=[];padFire=false}
 if(inputMode==='mouse'&&mouse.active){target=mode?null:view.pick(mouse.x,mouse.y);aim=target?{x:target.x,z:target.z}:view.groundPoint(mouse.x,mouse.y)}if(inputMode==='stick'&&Math.hypot(sticks.aim.x,sticks.aim.y)>.12){target=mode?null:aimAssist(sticks.aim.x,sticks.aim.y);aim=target?{x:target.x,z:target.z}:{x:p.x+sticks.aim.x*24,z:p.z+sticks.aim.y*24};steady=true}if(lockTarget){if(lockTarget.dead||battle.smokeBlocked(p,lockTarget)){lockTarget=null;target=null}else{target=lockTarget;aim={x:target.x,z:target.z}}}if(target?.dead)target=null;
 const length=Math.hypot(mx,mz);if(length>1){mx/=length;mz/=length}if(releaseFire&&!mouse.down&&!touchFire&&!padFire)releaseFire=false;input={mx,mz,aim,target,fire:!mode&&!releaseFire&&fire,steady,crouch,sprint};return input}
function event(e){view.effect(e);audio.event(e,battle.player);if(e.type==='hit'){hitTime=.18;hitDead=e.dead}if(e.type==='hurt')hurtTime=.5;if(e.type==='blocked')blockedTime=.6;if(e.type==='log'){radio.push({text:e.text,at:battle.time});radio=radio.slice(-3)}if(e.type==='victory'||battle.lost)showResult()}
function showResult(){if(!$('result-screen').hidden)return;$('result-screen').hidden=false;clearInput();const won=battle.won;$('result-eyebrow').textContent=won?'THE LINE HAS MOVED':'REGROUP';$('result-title').textContent=won?'Station secured.':'A hard crossing.';$('result-description').textContent=won?'Your section has a foothold. The signal is through.':'Use cover between bursts. Smoke the crossing, or take the drainage ditch along the western edge.';const mins=Math.floor(battle.time/60),secs=Math.floor(battle.time%60).toString().padStart(2,'0');$('result-stats').innerHTML=`<div><strong>${mins}:${secs}</strong><span>ELAPSED</span></div><div><strong>${battle.kills}</strong><span>NEUTRALIZED</span></div><div><strong>${battle.shots?Math.round(battle.hits/battle.shots*100):0}%</strong><span>HITS / SHOTS</span></div>`}
function ui(){const p=battle.player;$('health').textContent=Math.ceil(p.hp);$('healthbar').style.width=p.hp+'%';$('healthbar').style.background=p.hp<30?'#ee9276':'#9ddcde';$('stamina').style.width=p.stamina+'%';$('ammo').textContent=p.ammo[p.weapon].toString().padStart(2,'0');$('reserve').textContent=p.reserve[p.weapon];$('weapon-name').textContent=weapons[p.weapon].name.toUpperCase();$('reload-status').textContent=p.reload>0?'RELOADING':p.heal>0?'BANDAGING':p.ammo[p.weapon]===0?'RELOAD':'';$('squad-state').textContent='SECTION · '+battle.actors.filter(a=>a.team==='blue'&&!a.dead).length+' ACTIVE';$('smoke-count').textContent=p.smoke;$('arty-count').textContent=p.barrages;$('bandage-count').textContent=p.bandages;const threats=battle.actors.filter(a=>!a.dead&&a.team==='red'&&distance(a,p)<45);const covered=threats.length>0&&threats.every(a=>trace(battle.world,muzzle(a),{x:p.x,y:p.y+bodyHeight(p),z:p.z}).type!=='none');$('cover-state').textContent=p.sprinting?'SPRINT':p.suppression>.5?'SUPPRESSED':crouch&&(input.fire||input.steady)?'PEEKING':crouch&&covered?'LOW COVER':crouch?'CROUCHED':'EXPOSED';$('cover-state').style.color=crouch&&covered?'#a0d6cb':p.suppression>.5?'#f58a6c':'#bdc8c5';let progress=0,phase='01 / CROSS THE LINE',objective='Take the signal station';if(battle.phase==='capture'){phase='02 / SECURE THE STATION';objective='Clear the circle · '+Math.max(0,Math.ceil(5-battle.capture))+'s to capture';progress=battle.capture/5}else if(battle.phase==='hold'){phase='03 / HOLD THE STATION';objective='Hold the circle · '+Math.max(0,Math.ceil(battle.hold))+'s remaining';progress=1-battle.hold/25}else{progress=clamp((18-p.z)/38,0,1)*.9}$('phase').textContent=phase;$('objective').textContent=objective;$('mission-progress').style.width=progress*100+'%';$('radio').textContent=radio.filter(r=>battle.time-r.at<9).map(r=>r.text).slice(-2).join('  /  ');
 for(const b of document.querySelectorAll('[data-action]')){const action=b.dataset.action;b.disabled=action==='smoke'&&p.smoke===0||action==='artillery'&&(p.barrages===0||p.artCooldown>0)||action==='bandage'&&(p.bandages===0||p.hp>=100||p.heal>0)}
 if(mode&&distance(p,aim)<7)$('mode-help').textContent=mode==='artillery'?'DANGER CLOSE · artillery hurts your section too':'Smoke blocks sight for both sides';
 const cross=$('crosshair');cross.style.display=started&&!paused&&!battle.won&&!battle.lost&&!mode?'block':'none';const pt=target?view.project(target.x,target.y+1.25,target.z):inputMode==='mouse'&&mouse.active?mouse:view.project(aim.x,battle.world.height(aim.x,aim.z)+1.4,aim.z);cross.style.left=pt.x+'px';cross.style.top=pt.y+'px';cross.classList.toggle('enemy',!!target);cross.classList.toggle('blocked',blockedTime>0);$('hitmarker').style.left=pt.x+'px';$('hitmarker').style.top=pt.y+'px';$('hitmarker').style.opacity=hitTime>0?1:0;$('hitmarker').style.color=hitDead?'#f5b979':'#fffbdc';
 if(padConnected)$('desktop-hint').textContent='Left stick move · right stick aim · RT fire · LT steady · LB sprint · A vault · B cover · Y barrage';drawMap();}
function drawMap(){const w=190,h=192,to=a=>({x:(a.x+36)/72*w,y:(a.z+40)/78*h});mc.clearRect(0,0,w,h);mc.fillStyle='#293a3d';mc.fillRect(0,0,w,h);mc.strokeStyle='#b6b59a12';mc.lineWidth=1;for(let i=0;i<8;i++){mc.beginPath();mc.moveTo(i*w/8,0);mc.lineTo(i*w/8,h);mc.stroke();mc.beginPath();mc.moveTo(0,i*h/8);mc.lineTo(w,i*h/8);mc.stroke()}for(const z of [18,-16]){const p=to({x:-27,z:z-2});mc.fillStyle='#192c30';mc.fillRect(p.x,p.y,54/72*w,4/78*h);mc.strokeStyle='#aeaa7e';mc.beginPath();mc.moveTo(p.x,p.y);mc.lineTo(p.x+54/72*w,p.y);mc.stroke()}for(const c of battle.world.craters){const p=to(c);mc.strokeStyle='#798976';mc.beginPath();mc.arc(p.x,p.y,c.r/72*w,0,7);mc.stroke()}const o=to(battle.objective);mc.strokeStyle=battle.phase==='hold'?'#8bdbd5':'#efbd72';mc.lineWidth=1.5;mc.strokeRect(o.x-5,o.y-5,10,10);for(const s of battle.smokes){const q=to(s);mc.fillStyle='#d0d1b944';mc.beginPath();mc.arc(q.x,q.y,s.r/72*w,0,7);mc.fill()}for(const a of battle.actors){if(a.dead||a.team==='red'&&battle.smokeBlocked(battle.player,a))continue;const p=to(a);mc.fillStyle=a.role==='player'?'#ffffff':a.team==='blue'?'#9ddcde':'#ef946f';mc.beginPath();mc.arc(p.x,p.y,a.role==='player'?3:2,0,7);mc.fill();if(a.role==='player'){mc.strokeStyle='#f4efd8';mc.beginPath();mc.moveTo(p.x,p.y);mc.lineTo(p.x+Math.sin(a.heading)*8,p.y+Math.cos(a.heading)*8);mc.stroke()}}for(const s of battle.shells){const p=to(s);mc.strokeStyle=s.team==='blue'?'#efbd72':'#f07d69';mc.beginPath();mc.arc(p.x,p.y,5/72*w,0,7);mc.stroke()}}
function circle3D(x,z,r,color,width=2){ctx.beginPath();for(let i=0;i<=64;i++){const a=i/64*Math.PI*2,px=x+Math.sin(a)*r,pz=z+Math.cos(a)*r,q=view.project(px,battle.world.height(px,pz)+.10,pz);if(!i)ctx.moveTo(q.x,q.y);else ctx.lineTo(q.x,q.y)}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function drawOverlay(){ctx.clearRect(0,0,innerWidth,innerHeight);if(!started)return;const p=battle.player;
 for(const a of battle.actors){if(a.dead||a.team==='red'&&battle.smokeBlocked(p,a))continue;const q=view.project(a.x,a.y+2.8,a.z);if(!q.visible)continue;if(a===p){ctx.fillStyle='#ddedce';ctx.beginPath();ctx.moveTo(q.x-4,q.y-6);ctx.lineTo(q.x+4,q.y-6);ctx.lineTo(q.x,q.y);ctx.fill()}else{ctx.fillStyle=a.team==='blue'?'#91d7d6':'#efa178';ctx.fillRect(q.x-2,q.y-2,4,4);if(a.hp<a.maxHp){ctx.fillStyle='#16282ccc';ctx.fillRect(q.x-12,q.y+5,24,3);ctx.fillStyle=a.team==='blue'?'#8fcfcd':'#e49c77';ctx.fillRect(q.x-12,q.y+5,24*a.hp/a.maxHp,3)}if(a.suppression>.5){ctx.strokeStyle='#e5bb78';ctx.lineWidth=1;ctx.beginPath();ctx.arc(q.x,q.y,6,Math.PI,Math.PI*2);ctx.stroke()}}}
 for(const s of battle.shells){if(s.smoke)continue;circle3D(s.x,s.z,5*(.85+.04*Math.sin(battle.time*8)),s.team==='blue'?'#f2c47a':'#ff9277',2);const q=view.project(s.x,battle.world.height(s.x,s.z)+.1,s.z);ctx.fillStyle=s.team==='blue'?'#f2c47a':'#ff9277';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText(s.t.toFixed(1),q.x,q.y-9)}
 if(mode){circle3D(aim.x,aim.z,mode==='artillery'?5:4.8,'#eec47d',2);const a=view.project(p.x,p.y+1.7,p.z),b=view.project(aim.x,.2,aim.z);ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle='#efbd7299';ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([])}else if(input.steady||target){const from=muzzle(p),to={x:aim.x,z:aim.z,y:target?target.y+bodyHeight(target):battle.world.height(aim.x,aim.z)+1.4},hit=trace(battle.world,from,to);if(hit.type!=='none'){const h=view.project(hit.x,hit.y,hit.z);ctx.strokeStyle='#edbd79';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(h.x-4,h.y-4);ctx.lineTo(h.x+4,h.y+4);ctx.moveTo(h.x+4,h.y-4);ctx.lineTo(h.x-4,h.y+4);ctx.stroke()}}
 const obj=view.project(5,2,-22);if(obj.y<110||obj.x<20||obj.x>innerWidth-20){const ox=clamp(obj.x,35,innerWidth-35),oy=clamp(obj.y,128,innerHeight-190);ctx.fillStyle='#efbd72';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText('◇ SIGNAL STATION',ox,oy);ctx.font='11px Arial';ctx.fillText(Math.round(distance(p,battle.objective))+' m',ox,oy+17)}else if(battle.phase==='capture'||battle.phase==='hold'){circle3D(5,-22,4.5,battle.phase==='hold'?'#9ddcdeaa':'#efbd72aa',2)}
 if(hurtTime>0){const gradient=ctx.createRadialGradient(innerWidth*.5,innerHeight*.5,innerHeight*.22,innerWidth*.5,innerHeight*.5,innerHeight*.77);gradient.addColorStop(0,'#c5492a00');gradient.addColorStop(1,`rgba(175,57,35,${hurtTime*.6})`);ctx.fillStyle=gradient;ctx.fillRect(0,0,innerWidth,innerHeight)}
}
function loop(now){requestAnimationFrame(loop);if(!view)return;const dt=Math.min((now-previous)/1000,.08);previous=now;try{controls();if(started&&!paused&&!battle.won&&!battle.lost){acc+=dt;let n=0;while(acc>=FIXED&&n++<6){battle.update(FIXED,input);view.animate(FIXED);acc-=FIXED}audio.step(battle.player,battle.time)}else{acc=0;if(!started)view.animate(FIXED)}for(const e of battle.events.splice(0))event(e);if(battle.lost||battle.won)showResult();hitTime-=dt;hurtTime-=dt;blockedTime-=dt;view.render(dt,aim,!started);drawOverlay();if(now-lastUI>80){ui();lastUI=now}}catch(e){fatal(e)}}
requestAnimationFrame(loop);
// Agent-readable mission state is mirrored in the DOM; no browser internals required.
setInterval(()=>{document.body.dataset.mission=JSON.stringify(battle.status())},400);
const modelContext=document.modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn)}catch(e){console.warn(e)}};
register({name:'get_battle_status',description:'Read this local mission’s health, ammunition, progress, and remaining opposition.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async()=>battle.status()});
register({name:'pause_battle',description:'Pause or resume the current local mission.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(value)=>{if(typeof value?.paused!=='boolean')throw new Error('paused must be a boolean');if(!started||battle.won||battle.lost)throw new Error('No active mission');pause(value.paused);return{paused}}});
window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
