import * as THREE from 'three';
import {Gait,solveLimb,HIP_HEIGHT} from './gait.js';
import {SoftwareRenderer} from './software-renderer.js';
import {clamp,lerp,rng,bodyHeight,muzzle,trace} from './engine.js';
const UP=new THREE.Vector3(0,1,0),V=new THREE.Vector3();
export class View{
 constructor(canvas,battle){this.canvas=canvas;this.battle=battle;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#667b80');this.scene.fog=new THREE.Fog('#667b80',58,120);this.camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.2,170);this.zoom=1;this.look=new THREE.Vector3(-8,0,10);this.shake=0;this.time=0;this.quality='High';this.rigs=new Map();this.blockMeshes=new Map();this.fx=[];this.smokeMeshes=new Map();this.bulletMeshes=[];this.raycaster=new THREE.Raycaster();
 try{const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw Error('No WebGL');this.renderer=new THREE.WebGLRenderer({canvas,context:gl,antialias:true});this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.outputColorSpace=THREE.SRGBColorSpace}catch{this.renderer=new SoftwareRenderer({canvas});this.software=true}
 this.scene.add(new THREE.HemisphereLight('#c5e3ea','#605540',2.1));this.sun=new THREE.DirectionalLight('#ffd297',3.15);this.sun.position.set(-32,42,-18);this.sun.castShadow=true;Object.assign(this.sun.shadow.camera,{left:-43,right:43,top:43,bottom:-43,near:.5,far:125});this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.bias=-.0004;this.sun.shadow.normalBias=.03;this.scene.add(this.sun);this.scene.add(new THREE.AmbientLight('#a5b1ab',.15));this.geo={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.IcosahedronGeometry(1,0),cyl:new THREE.CylinderGeometry(1,1,1,7),cone:new THREE.ConeGeometry(1,1,7)};this.mats={};this.buildWorld();this.resize();}
 mat(c,flat=true){const key=c+(flat?'f':'');return this.mats[key]||(this.mats[key]=new THREE.MeshStandardMaterial({color:c,roughness:.94,flatShading:flat}))}
 box(parent,x,y,z,w,h,d,color){const m=new THREE.Mesh(this.geo.box,this.mat(color));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 shape(parent,g,x,y,z,sx,sy,sz,color){const m=new THREE.Mesh(this.geo[g],this.mat(color));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 beam(parent,a,b,r,color){const m=new THREE.Mesh(this.geo.cyl,this.mat(color));this.segment(m,a,b,r);m.castShadow=true;parent.add(m);return m}
 segment(mesh,a,b,r){mesh.position.copy(a).add(b).multiplyScalar(.5);const v=V.copy(b).sub(a),len=v.length();mesh.scale.set(r,len,r);mesh.quaternion.setFromUnitVectors(UP,v.normalize());}
 buildWorld(){const w=this.battle.world,rand=rng(421),pos=[],colors=[],indices=[],color=new THREE.Color();for(let iz=0;iz<=78;iz++)for(let ix=0;ix<=72;ix++){const x=ix-36,z=iz-40,h=w.height(x,z);pos.push(x,h,z);const trench=h<-.65,crater=w.craters.some(c=>Math.hypot(x-c.x,z-c.z)<c.r*1.1),road=Math.abs(x-7-Math.sin(z*.11)*3)<1.8;const palette=trench?['#514c3e','#575242','#605744']:crater?['#69604e','#77705b','#655d4c']:road?['#89816b','#7a745e']:['#7d8160','#8a8866','#737b5d','#929071'];color.set(palette[Math.floor(rand()*palette.length)]);color.multiplyScalar(.91+rand()*.18);colors.push(color.r,color.g,color.b)}for(let z=0;z<78;z++)for(let x=0;x<72;x++){const a=z*73+x;indices.push(a,a+73,a+1,a+1,a+73,a+74)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setIndex(indices);g.computeVertexNormals();this.terrain=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:true}));this.terrain.receiveShadow=true;this.scene.add(this.terrain);
 const batch=[];const add=(x,y,z,sx,sy,sz,c,ry=0,rz=0)=>batch.push({x,y,z,sx,sy,sz,c,ry,rz});
 for(const z of [18,-16]){for(let x=-25;x<26;x+=1.1){const y=w.height(x,z)+.045;add(x,y,z,.83,.07,1.2,'#76664a',rand()*.1);if(Math.abs(x%6)<1.2){for(const off of [-2.2,2.2]){const sz=z+off;add(x,w.height(x,sz)+.40,sz,.12,1,.13,'#4c4a3e',.1)}}}for(const dz of [-2.35,2.35])for(let x=-25;x<26;x+=2){const zz=z+dz;add(x,w.height(x,zz)+.17,zz,1.92,.12,.12,'#706044')}}
 // Sandbags use a shared collision volume and individual rounded visual bags.
 for(const b of w.blocks){const group=new THREE.Group();group.position.set(b.x,b.y,b.z);this.scene.add(group);this.blockMeshes.set(b.id,group);if(b.type==='bags'){const n=Math.max(1,Math.ceil(b.w/.65));for(let row=0;row<2;row++)for(let i=0;i<n;i++){const m=this.shape(group,'sphere',-b.w/2+(i+.5)*b.w/n+(row?.07:0),.17+row*.29,0,b.w/n*.61,.22,b.d*.63,row?'#a39873':'#8e8664');m.rotation.y=(rand()-.5)*.14}}else if(b.type==='stone'){this.box(group,0,b.h*.5,0,b.w,b.h,b.d,'#7c8075');const count=Math.ceil(b.w/1.0);for(let i=0;i<count;i++){const bh=.20+rand()*.25;this.box(group,-b.w/2+(i+.5)*b.w/count,b.h+bh*.5,0,b.w/count*.87,bh,b.d*.8,'#909286')}for(let j=0;j<Math.ceil(b.h/.5);j++)this.box(group,0,j*.5+.1,b.d/2+.006,b.w,.025,.013,'#5b665f')}else{this.box(group,0,b.h*.5,0,b.w,b.h,b.d,'#6e6448');this.box(group,0,b.h*.5,b.d/2+.02,b.w*.9,.09,.04,'#b0a077');this.box(group,0,b.h*.5,0,.1,b.h+.05,b.d+.03,'#343e39')}}
 // Earth, stubble and fragments are seeded in patches; crossings stay legible.
 for(let i=0;i<1200;i++){const x=rand()*69-34.5,z=rand()*75-38,y=w.height(x,z),trench=y<-.5;const near=w.blocks.some(b=>Math.abs(x-b.x)<b.w/2+.3&&Math.abs(z-b.z)<b.d/2+.3);if(near||trench)continue;if(rand()<.70){const h=.07+rand()*.24;add(x,y+h/2,z,.025,h,.055,rand()<.5?'#a99c65':'#636e4d',rand()*6,.2*(rand()-.5))}else{const s=.08+rand()*.22;add(x,y+s*.3,z,s,s*.6,s*.7,rand()<.5?'#605e51':'#969079',rand()*6)}}
 for(const c of w.craters){for(let i=0;i<17;i++){const a=rand()*6.28,r=c.r*(.85+rand()*.44),x=c.x+Math.cos(a)*r,z=c.z+Math.sin(a)*r;add(x,w.height(x,z)+.1,z,.16+rand()*.4,.15,.2,'#6c6656',a)}if(c.r>3.6){const m=new THREE.Mesh(new THREE.CircleGeometry(c.r*.30,20),new THREE.MeshStandardMaterial({color:'#687d7d',roughness:.22,metalness:.32}));m.rotation.x=-Math.PI/2;m.position.set(c.x,w.height(c.x,c.z)+.045,c.z);this.scene.add(m)}}
 const treePlaces=[[-30,12],[-31,-14],[29,12],[30,-10],[17,29],[-25,-29],[16,-30],[32,-34],[-29,30]];for(const [x,z]of treePlaces){const y=w.height(x,z),h=3+rand()*3;this.beam(this.scene,new THREE.Vector3(x,y,z),new THREE.Vector3(x+.5,y+h,z-.2),.17,'#444b42');for(let k=0;k<3;k++){const a=rand()*6.28;this.beam(this.scene,new THREE.Vector3(x+.3,y+h*.55,z),new THREE.Vector3(x+Math.sin(a)*1.5,y+h*.78,z+Math.cos(a)*1.5),.09,'#4b5044')}}
 // Wire has broad clear gaps at the central and western crossing.
 const wirePoints=[];for(const [start,end,z] of [[-19,-10,10],[-3,15,10],[19,28,10],[-17,-7,-8],[7,20,-8]]){for(let x=start;x<=end;x+=1.8){const y=w.height(x,z);add(x,y+.65,z,.07,1.3,.07,'#494f43',0,.12);add(x,y+.65,z,.07,1.3,.07,'#494f43',0,-.12)}for(let x=start;x<end;x+=.18){const y=w.height(x,z),t=(x-start)*8;wirePoints.push(new THREE.Vector3(x,y+.45+Math.sin(t)*.35,z+Math.cos(t)*.38))}}
 const wire=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(wirePoints.flatMap((p,i)=>i?[wirePoints[i-1],p]:[])),new THREE.LineBasicMaterial({color:'#48564a'}));this.scene.add(wire);
 // Telephone poles and the signal flag establish direction without a floating quest pillar.
 for(const z of [-31,-1,28]){const x=31,y=w.height(x,z);add(x,y+3.4,z,.18,6.8,.18,'#645741');add(x,y+5.9,z,2.3,.13,.13,'#5e513d')}
 this.flag=new THREE.Group();this.flag.position.set(5,w.height(5,-22),-22);this.scene.add(this.flag);this.box(this.flag,0,2,0,.06,4,.06,'#383f3b');this.flagCloth=this.box(this.flag,.61,3.4,0,1.25,.67,.035,'#b86749');this.box(this.scene,6,w.height(6,-23)+.5,-23,1.15,1,.68,'#424d45');this.box(this.scene,6,w.height(6,-23)+1.1,-23,1.3,.08,.8,'#8c8465');this.shape(this.scene,'cyl',6.3,w.height(6.3,-23)+1.4,-23,.025,.8,.025,'#2f403e');
 // Resupply station behind the starting line.
 const sy=w.height(-16,22);this.box(this.scene,-16,sy+.48,22,1.4,.9,.85,'#7c8470');this.box(this.scene,-16,sy+.53,22.44,.7,.18,.03,'#ded8b8');this.box(this.scene,-16,sy+.53,22.46,.18,.65,.03,'#ded8b8');
 // Distant wreckage and sunlit horizon are still part of the 3D scene.
 for(let i=0;i<45;i++){const x=(rand()-.5)*130,z=-46-rand()*12;this.box(this.scene,x,1+rand()*1.5,z,1+rand()*2,2+rand()*4,1+rand()*2,'#626e68')}
 const im=new THREE.InstancedMesh(this.geo.box,this.mat('#ffffff'),batch.length),dummy=new THREE.Object3D();batch.forEach((b,i)=>{dummy.position.set(b.x,b.y,b.z);dummy.scale.set(b.sx,b.sy,b.sz);dummy.rotation.set(0,b.ry,b.rz);dummy.updateMatrix();im.setMatrixAt(i,dummy.matrix);im.setColorAt(i,new THREE.Color(b.c))});im.castShadow=true;im.receiveShadow=true;this.scene.add(im);
 const ringGeo=new THREE.RingGeometry(4.4,4.48,64),ringMat=new THREE.MeshBasicMaterial({color:'#efbd72',side:THREE.DoubleSide,transparent:true,opacity:.55,depthWrite:false});this.objectiveRing=new THREE.Mesh(ringGeo,ringMat);this.objectiveRing.rotation.x=-Math.PI/2;this.objectiveRing.position.set(5,w.height(5,-22)+.07,-22);this.scene.add(this.objectiveRing);
 this.playerRing=new THREE.Mesh(new THREE.RingGeometry(.65,.72,36),new THREE.MeshBasicMaterial({color:'#bee9da',side:THREE.DoubleSide,transparent:true,opacity:.8,depthWrite:false}));this.playerRing.rotation.x=-Math.PI/2;this.scene.add(this.playerRing);
 }
 createRig(a){const group=new THREE.Group();this.scene.add(group);const cloth=a.team==='blue'?(a.role==='player'?'#687b75':'#667572'):'#958166',helmet=a.team==='blue'?'#424f49':'#635e4d',skin=['#b28868','#d0a481','#956949','#bc9472'][a.id%4],rig={group,gait:new Gait(),legs:[],arms:[]};rig.pelvis=this.box(group,0,1.37,0,.40,.24,.29,cloth);rig.torso=this.box(group,0,1.70,0,.49,.54,.29,cloth);this.box(rig.torso,0,0,.52,.45,.26,.06,'#343f39');rig.head=this.shape(group,'sphere',0,2.16,.02,.21,.26,.21,skin);rig.helmet=this.shape(group,'sphere',0,2.32,0,.28,.15,.28,helmet);rig.brim=this.shape(group,'cyl',0,2.24,.025,.30,.045,.30,helmet);rig.nose=this.box(group,0,2.16,.21,.085,.1,.09,skin);rig.pack=this.box(group,0,1.65,-.29,.37,.44,.22,'#675f48');rig.belt=this.box(group,0,1.47,.03,.45,.11,.35,'#3e4338');rig.pouch=this.box(group,-.25,1.48,.10,.16,.22,.2,'#87795b');
 for(const side of [-1,1]){const thigh=this.shape(group,'cyl',0,0,0,.13,1,.13,cloth),shin=this.shape(group,'cyl',0,0,0,.105,1,.105,cloth),boot=this.box(group,0,.1,0,.21,.22,.38,'#353d36');rig.legs.push({side,thigh,shin,boot});const upper=this.shape(group,'cyl',0,0,0,.10,1,.10,cloth),fore=this.shape(group,'cyl',0,0,0,.085,1,.085,cloth),hand=this.shape(group,'sphere',0,0,0,.09,.1,.09,skin);rig.arms.push({side,upper,fore,hand})}
 rig.gun=new THREE.Group();group.add(rig.gun);this.box(rig.gun,0,0,.06,.14,.17,.68,'#655740');this.box(rig.gun,0,.015,.39,.12,.13,.31,'#3e4642');this.box(rig.gun,0,-.17,.37,.11,.27,.15,'#363e39');this.box(rig.gun,0,.06,.72,.055,.07,.72,'#343e3b');this.box(rig.gun,0,.115,.62,.026,.07,.035,'#141f20');const flashMat=new THREE.MeshBasicMaterial({color:'#ffeac2'});rig.flash=new THREE.Mesh(this.geo.cone,flashMat);rig.flash.rotation.x=Math.PI/2;rig.flash.position.set(0,0,1.08);rig.flash.scale.set(.18,.5,.18);rig.flash.visible=false;rig.gun.add(rig.flash);rig.flashTime=0;
 const shadow=new THREE.Mesh(new THREE.CircleGeometry(.53,14),new THREE.MeshBasicMaterial({color:'#25332a',transparent:true,opacity:.24,depthWrite:false}));shadow.rotation.x=-Math.PI/2;this.scene.add(shadow);rig.shadow=shadow;this.rigs.set(a.id,rig);return rig}
 animate(dt){this.time+=dt;for(const a of this.battle.actors){const r=this.rigs.get(a.id)||this.createRig(a),g=r.group;r.shadow.position.set(a.x,this.battle.world.height(a.x,a.z)+.035,a.z);if(a.dead){g.position.set(a.x,a.y+.18,a.z);g.rotation.set(Math.PI/2,0,-a.heading);g.scale.setScalar(.94);r.flash.visible=false;continue}g.position.set(a.x,a.y,a.z);g.rotation.set(0,a.heading,0);r.gait.update(dt,a,(x,z)=>this.battle.world.height(x,z),a.crouching?.2:0);const lower=a.crouch*.44,hip=HIP_HEIGHT+r.gait.pelvis-lower,bodyShift=hip-HIP_HEIGHT;r.pelvis.position.y=hip;r.pelvis.position.x=r.gait.sway;r.torso.position.y=1.73+bodyShift;r.torso.rotation.x=a.sprinting?.14:0;r.pack.position.y=1.65+bodyShift;r.belt.position.y=1.47+bodyShift;r.pouch.position.y=1.48+bodyShift;for(const m of [r.head,r.helmet,r.brim,r.nose])m.position.y=(m===r.head?2.16:m===r.helmet?2.32:m===r.brim?2.24:2.16)+bodyShift;
 for(let i=0;i<2;i++){const l=r.legs[i],f=r.gait.feet[i],foot=f.local.clone().add(new THREE.Vector3(0,.13,0)),origin=new THREE.Vector3(l.side*.17+r.gait.sway,hip,0),sol=solveLimb(origin,foot,.64,.62,new THREE.Vector3(0,0,1));this.segment(l.thigh,origin,sol.joint,.13);this.segment(l.shin,sol.joint,sol.end,.105);l.boot.position.copy(sol.end);l.boot.position.z+=.07;l.boot.rotation.x=f.roll||0}
 const gunHeight=bodyHeight(a);r.gun.position.set(.22,gunHeight,.29-a.recoil*.07);r.gun.rotation.x=a.reload>0?-.28:0;for(let i=0;i<2;i++){const arm=r.arms[i],shoulder=new THREE.Vector3(arm.side*.28,1.92+bodyShift,0),hand=new THREE.Vector3(arm.side<0?.13:.28,gunHeight-.04,a.reload>0?(arm.side<0?.48:.20):(arm.side<0?.61:.18)),sol=solveLimb(shoulder,hand,.36,.35,new THREE.Vector3(arm.side,-.8,-.3));this.segment(arm.upper,shoulder,sol.joint,.1);this.segment(arm.fore,sol.joint,sol.end,.082);arm.hand.position.copy(sol.end)}r.flashTime=Math.max(0,r.flashTime-dt);r.flash.visible=r.flashTime>0;}
 }
 effect(event){const r=event.actor?this.rigs.get(event.actor.id):null;if(event.type==='shot'&&r){r.flashTime=.065;if(event.actor===this.battle.player)this.shake=Math.max(this.shake,.035)}if(event.type==='coverDown'){const g=this.blockMeshes.get(event.block.id);if(g){g.scale.y=.23;g.rotation.z=.04}}if(event.type==='explosion'){this.shake=Math.max(this.shake,.43/(1+Math.hypot(event.x-this.battle.player.x,event.z-this.battle.player.z)/20));this.burst(event.x,event.y+.4,event.z,24,true)}if(event.type==='impact')this.burst(event.x,event.y,event.z,event.type==='actor'?3:3,false);if(event.type==='hurt')this.shake=Math.max(this.shake,.14);}
 burst(x,y,z,n,big){for(let i=0;i<n;i++){const color=big?(i<7?'#ffc276':i<12?'#a38c67':'#575d50'):'#bdac7d';const mesh=this.shape(this.scene,'sphere',x,y,z,big?.30:.055,big?.30:.055,big?.30:.055,color),life=big?1.2+Math.random()*.8:.25+Math.random()*.3;this.fx.push({mesh,age:0,life,vx:(Math.random()-.5)*(big?11:3),vy:Math.random()*(big?10:3),vz:(Math.random()-.5)*(big?11:3),big})}while(this.fx.length>180){this.scene.remove(this.fx.shift().mesh)}}
 resize(){this.w=innerWidth;this.h=innerHeight;this.renderer.setPixelRatio(this.software?.5:Math.min(devicePixelRatio,this.quality==='High'?1.7:1));this.renderer.setSize(this.w,this.h);this.camera.aspect=this.w/this.h;this.camera.updateProjectionMatrix()}
 toggleQuality(){this.quality=this.quality==='High'?'Balanced':'High';if(!this.software)this.renderer.shadowMap.enabled=this.quality==='High';this.resize();return this.quality}
 project(x,y,z){const p=new THREE.Vector3(x,y,z).project(this.camera);return{x:(p.x*.5+.5)*this.w,y:(-.5*p.y+.5)*this.h,visible:p.z<1&&p.z>-1}}
 groundPoint(px,py){this.raycaster.setFromCamera(new THREE.Vector2(px/this.w*2-1,1-py/this.h*2),this.camera);const hit=this.raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());return hit?{x:clamp(hit.x,-34,34),z:clamp(hit.z,-37,33)}:{x:this.battle.player.x,z:this.battle.player.z-15}}
 pick(px,py){let best=null,d=31;for(const a of this.battle.actors){if(a.dead||a.team==='blue'||this.battle.smokeBlocked(this.battle.player,a))continue;const q=this.project(a.x,a.y+1.3,a.z),dist=Math.hypot(px-q.x,py-q.y);if(dist<d){best=a;d=dist}}return best}
 render(dt,aim,overview=false){const mobile=this.w<700,touch=document.body.classList.contains('touch');const p=this.battle.player,lookTarget=new THREE.Vector3(overview?-3:p.x,0,overview?0:p.z+(touch?4:-3));if(!overview&&aim){lookTarget.x+=clamp(aim.x-p.x,-20,20)*.14;lookTarget.z+=clamp(aim.z-p.z,-25,25)*.12}this.look.lerp(lookTarget,1-Math.exp(-dt*5));const dist=(mobile?1.20:1)*this.zoom*(overview?1.30:1);this.camera.position.set(this.look.x,this.look.y+31*dist,this.look.z+29*dist);this.shake*=Math.exp(-dt*11);this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.y+=(Math.random()-.5)*this.shake;this.camera.lookAt(this.look);this.camera.updateMatrixWorld();this.playerRing.position.set(p.x,this.battle.world.height(p.x,p.z)+.052,p.z);this.playerRing.visible=!p.dead;
 this.objectiveRing.material.color.set(this.battle.phase==='hold'?'#a2ddd9':'#efbd72');this.flagCloth.material=this.mat(this.battle.phase==='hold'?'#7eb9bd':'#b86749');this.flagCloth.rotation.y=Math.sin(this.time*3)*.12;
 for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.age+=dt;f.mesh.position.x+=f.vx*dt;f.mesh.position.y+=f.vy*dt;f.mesh.position.z+=f.vz*dt;f.vy-=dt*13;f.mesh.rotation.x+=dt*3;f.mesh.scale.multiplyScalar(Math.max(.1,1-dt*1.8));if(f.age>f.life||f.mesh.position.y<this.battle.world.height(f.mesh.position.x,f.mesh.position.z)){this.scene.remove(f.mesh);this.fx.splice(i,1)}}
 let n=0;for(const b of this.battle.bullets){let m=this.bulletMeshes[n++];if(!m){m=new THREE.Mesh(this.geo.cyl,new THREE.MeshBasicMaterial({color:'#ffe5a6'}));this.scene.add(m);this.bulletMeshes.push(m)}m.visible=true;m.material.color.set(b.owner.team==='red'?'#ffc28f':'#fff2af');const a=new THREE.Vector3(b.x,b.y,b.z),end=a.clone().add(new THREE.Vector3(-b.vx,-b.vy,-b.vz).multiplyScalar(.018));this.segment(m,a,end,.021)}for(;n<this.bulletMeshes.length;n++)this.bulletMeshes[n].visible=false;
 for(const [s,group]of this.smokeMeshes)if(!this.battle.smokes.includes(s)){this.scene.remove(group);this.smokeMeshes.delete(s)}for(const s of this.battle.smokes){let g=this.smokeMeshes.get(s);if(!g){g=new THREE.Group();this.scene.add(g);this.smokeMeshes.set(s,g);for(let i=0;i<7;i++){const m=new THREE.Mesh(this.geo.sphere,new THREE.MeshStandardMaterial({color:s.blast?'#7d8073':'#bac1ad',transparent:true,opacity:.42,depthWrite:false,flatShading:true}));const a=i*2.4,r=i===0?0:s.r*.52;m.position.set(Math.sin(a)*r,1.2+(i%3)*.55,Math.cos(a)*r);m.scale.set(2.4,1.8,2.3);g.add(m)}}g.position.set(s.x,this.battle.world.height(s.x,s.z),s.z);const fade=Math.min(1,s.age*1.6,(13-s.age));g.scale.setScalar(clamp(fade,.01,1));g.rotation.y=this.time*.025;for(const m of g.children)m.material.opacity=clamp(fade*.40,0,.40)}
 this.renderer.render(this.scene,this.camera);
 }
}
