export class AudioScene{
 constructor(){this.enabled=false;this.ctx=null;this.lastStep=0}
 async enable(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.42;this.master.connect(this.ctx.destination);const len=this.ctx.sampleRate*2;this.noiseBuffer=this.ctx.createBuffer(1,len,this.ctx.sampleRate);const d=this.noiseBuffer.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;const wind=this.ctx.createBufferSource();wind.buffer=this.noiseBuffer;wind.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=280;const gain=this.ctx.createGain();gain.gain.value=.11;wind.connect(filter).connect(gain).connect(this.master);wind.start()};await this.ctx.resume();this.enabled=true;this.master.gain.setTargetAtTime(.42,this.ctx.currentTime,.04)}catch{this.enabled=false}return this.enabled}
 disable(){this.enabled=false;if(this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.04)}
 noise(duration,volume,freq=1600,type='lowpass'){if(!this.enabled||!this.ctx)return;const c=this.ctx,n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noiseBuffer;f.type=type;f.frequency.value=freq;const t=c.currentTime;g.gain.setValueAtTime(Math.max(.0001,volume),t);g.gain.exponentialRampToValueAtTime(.001,t+duration);n.connect(f).connect(g).connect(this.master);n.start(t,Math.random());n.stop(t+duration+.02)}
 tone(freq,to,duration,volume,type='sine'){if(!this.enabled||!this.ctx)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain(),t=c.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(1,to),t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(this.master);o.start();o.stop(t+duration+.02)}
 event(e,p){const dist=e.actor?Math.hypot(e.actor.x-p.x,e.actor.z-p.z):0,v=1/(1+dist*.08);if(e.type==='shot'){this.noise(.10,.43*v,2800);this.tone(e.weapon?150:115,45,.15,.23*v,'triangle');if(e.actor===p)this.noise(.035,.22,6400,'highpass')}if(e.type==='explosion'){const d=Math.hypot(e.x-p.x,e.z-p.z),v=1/(1+d*.04);this.noise(1.4,.75*v,650);this.tone(85,22,.8,.6*v)}if(e.type==='hit')this.tone(e.dead?780:570,e.dead?1150:360,.085,.08,'triangle');if(e.type==='reload'||e.type==='loaded'||e.type==='switch'){this.noise(.075,.13,2200);this.tone(180,90,.05,.04,'square')}if(e.type==='radio'){this.noise(.4,.10,1800,'bandpass');this.tone(480,380,.3,.09)}if(e.type==='hurt')this.tone(75,38,.22,.30);if(e.type==='whiz'){this.noise(.18,.13,3200,'bandpass')}if(e.type==='smoke')this.noise(.7,.16,1100);if(e.type==='victory'){this.tone(220,330,.8,.09);setTimeout(()=>this.tone(330,440,.9,.09),220)}}
 step(a,time){if(a.moveSpeed>1&&time-this.lastStep>(a.sprinting?.22:.34)){this.lastStep=time;this.noise(.055,.09,500)}}
}
