import * as T from 'three';
export const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),up=V(0,1,0),materials=new Map();
export const geo={box:new T.BoxGeometry(1,1,1),cyl:new T.CylinderGeometry(1,1,1,20),sphere:new T.IcosahedronGeometry(1,1),cone:new T.ConeGeometry(1,1,8)};
export const finishes={paint:{roughness:.62,metalness:.22},metal:{roughness:.34,metalness:.78},cloth:{roughness:.96,metalness:0},skin:{roughness:.82,metalness:0},rubber:{roughness:.88,metalness:.03},glass:{roughness:.17,metalness:.38},stone:{roughness:1,metalness:0},floor:{roughness:.84,metalness:.12}};
export function surface(kind,c){const key=kind+':'+c;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color:c,...(finishes[kind]||finishes.paint),flatShading:kind==='stone'}));return materials.get(key);}
export function mat(c,glow=false){if(!glow)return surface('paint',c);const key='glow:'+c;if(!materials.has(key))materials.set(key,new T.MeshBasicMaterial({color:c}));return materials.get(key);}
export function mesh(parent,type,x,y,z,sx,sy,sz,c,glow=false){const m=new T.Mesh(geo[type],mat(c,glow));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
export const box=(p,x,y,z,w,h,d,c,glow=false)=>mesh(p,'box',x,y,z,w,h,d,c,glow);
// Small paving cells let the software fallback interpolate local lamp light
// across long roads instead of lighting an entire street as one triangle.
export function litPaving(p,x,y,z,w,h,d,c){const m=box(p,x,y,z,w,h,d,c);m.geometry=new T.BoxGeometry(1,1,1,Math.ceil(w/3),1,Math.ceil(d/3));return m;}
const shaped=new Map();
export function chamfer(p,x,y,z,w,h,d,c,kind='paint',edge=.08){const e=Math.min(edge,w*.15,h*.15,d*.15),key=[w,h,d,e].join(':');let geometry=shaped.get(key);if(!geometry){const s=new T.Shape();s.moveTo(-w/2+e,-h/2);s.lineTo(w/2-e,-h/2);s.lineTo(w/2,-h/2+e);s.lineTo(w/2,h/2-e);s.lineTo(w/2-e,h/2);s.lineTo(-w/2+e,h/2);s.lineTo(-w/2,h/2-e);s.lineTo(-w/2,-h/2+e);s.closePath();geometry=new T.ExtrudeGeometry(s,{depth:d-2*e,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:e*.4,bevelThickness:e});geometry.translate(0,0,-d/2+e);shaped.set(key,geometry);}const m=new T.Mesh(geometry,surface(kind,c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;p.add(m);return m;}
export function pipe(p,a,b,r,c,kind='metal'){const m=new T.Mesh(geo.cyl,surface(kind,c));p.add(m);segment(m,V(...a),V(...b),r);m.castShadow=m.receiveShadow=true;return m;}
export function panelLines(p,x,y,z,w,d,c='#172e36'){for(let t=-d/2+1;t<d/2;t+=2.5)box(p,x,y,z+t,w,.018,.035,c);}
export function ring(parent,x,y,z,r,c){const m=new T.Mesh(new T.RingGeometry(r-.08,r,48),new T.MeshBasicMaterial({color:c,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(x,y,z);parent.add(m);return m;}
export function label(parent,text,x,y,z,color='#afc3c8',size=1){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 27px monospace';ctx.fillText(text,256,32);const texture=new T.CanvasTexture(canvas),sprite=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthTest:false}));sprite.position.set(x,y,z);sprite.scale.set(8*size,size,1);sprite.userData.worldLabel=true;parent.add(sprite);return sprite;}
export function segment(m,a,b,r){m.position.copy(a).add(b).multiplyScalar(.5);m.scale.set(r,a.distanceTo(b),r);m.quaternion.setFromUnitVectors(up,b.clone().sub(a).normalize());}

// Bake static geometry within visibility boundaries; cutaways and moving parts stay independent.
export function batchStatic(root){root.updateMatrixWorld(true);function boundary(base){const buckets=new Map(),inverse=base.matrixWorld.clone().invert();function visit(o){if(o!==base&&(o.userData.animated||o.userData.batchBoundary)){if(o.userData.batchBoundary&&!o.userData.animated)boundary(o);return;}if(o.isMesh&&!o.userData.doorFrame&&!o.isSkinnedMesh&&!Array.isArray(o.material)){const key=o.material.uuid+':'+!!o.geometry.attributes.color+':'+!!o.userData.detail+':'+!!o.userData.localLighting+':'+!!o.userData.bakedRelayLighting;let b=buckets.get(key);if(!b){b={material:o.material,pos:[],normal:[],uv:[],color:[],colored:!!o.geometry.attributes.color,detail:!!o.userData.detail,localLighting:!!o.userData.localLighting,bakedRelayLighting:!!o.userData.bakedRelayLighting,source:[]};buckets.set(key,b);}const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry,m=inverse.clone().multiply(o.matrixWorld),normal=new T.Matrix3().getNormalMatrix(m),p=g.attributes.position,n=g.attributes.normal,uv=g.attributes.uv,c=g.attributes.color,v=V();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(m);b.pos.push(v.x,v.y,v.z);if(n)v.fromBufferAttribute(n,i).applyNormalMatrix(normal);else v.set(0,1,0);b.normal.push(v.x,v.y,v.z);b.uv.push(uv?.getX(i)||0,uv?.getY(i)||0);if(c)b.color.push(c.getX(i),c.getY(i),c.getZ(i));}if(g!==o.geometry)g.dispose();b.source.push(o);return;}for(const child of [...o.children])visit(child);}visit(base);for(const b of buckets.values()){if(b.source.length<2)continue;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(b.pos,3));g.setAttribute('normal',new T.Float32BufferAttribute(b.normal,3));g.setAttribute('uv',new T.Float32BufferAttribute(b.uv,2));if(b.colored)g.setAttribute('color',new T.Float32BufferAttribute(b.color,3));const m=new T.Mesh(g,b.material);m.castShadow=m.receiveShadow=true;m.userData={staticGeometry:true,ignoreLocalLights:b.material.isMeshBasicMaterial||!b.localLighting,localLighting:b.localLighting,bakedRelayLighting:b.bakedRelayLighting,detail:b.detail};base.add(m);b.source.forEach(o=>o.parent.remove(o));}}boundary(root);}

