// Locally synthesized ambience: no remote audio assets or automatic playback.
export class Soundscape{
 constructor(){this.ctx=null;this.enabled=false;this.nodes=[];this.timer=null;}
 async enable(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Audio is not supported in this browser.');this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=.22;this.master.connect(this.ctx.destination);}await this.ctx.resume();this.enabled=true;this.master.gain.setTargetAtTime(.22,this.ctx.currentTime,.3);if(!this.nodes.length){for(const f of[65.406,98,130.81]){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(this.master);o.start();this.nodes.push(o);}const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*4,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.1;const noise=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain();noise.buffer=buffer;noise.loop=true;filter.type='lowpass';filter.frequency.value=430;gain.gain.value=.09;noise.connect(filter);filter.connect(gain);gain.connect(this.master);noise.start();this.nodes.push(noise);}if(!this.timer)this.timer=setInterval(()=>this.phrase(),14000);this.phrase();}
 disable(){this.enabled=false;if(this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.15);clearInterval(this.timer);this.timer=null;}
 note(f,duration=.3,delay=0,volume=.12,type='sine'){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.03);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.05);o.onended=()=>{o.disconnect();g.disconnect();};}
 effect(kind){if(kind==='launch'){[130.81,196,261.63,392].forEach((f,i)=>this.note(f,1.1,i*.16,.13));}else if(kind==='arrival'||kind==='victory'){[261.63,329.63,392,523.25].forEach((f,i)=>this.note(f,1.7,i*.16,.1));}else if(kind==='turn'){this.note(164.81,.65,0,.07);this.note(246.94,.8,.1,.06);}else this.note(440,.09,0,.065);}
 phrase(){if(!this.enabled)return;[196,261.63,293.66,392,329.63].forEach((f,i)=>this.note(f,3.5,i*1.1,.025));}
 dispose(){this.disable();this.nodes.forEach(n=>{try{n.stop()}catch{}});this.ctx?.close();}
}
