import {triangleHeight} from './terrain-height.js';
import {woodlandRoute} from './woodland-route.js';
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const lerp=(a,b,t)=>a+(b-a)*t;
export const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)};
export function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function segmentDistance(x,z,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return {d:Math.hypot(x-a.x-dx*t,z-a.z-dz*t),t}}
export function makeAtlas(seed='MOSS-731'){
 const r=rng(hash(seed));
 const regionData=[['hearth','Hearthwick',0,44,14,4,'village'],['orchard','The Old Orchard',20,15,16,4.5,'orchard'],['birch','Birchweald',-29,18,18,4.8,'birch'],['ford','The Drowned Road',-53,-6,12,3,'marsh'],['pine','Blackpine Rise',-32,-39,18,9,'pine'],['abbey','The Sunken Abbey',9,-50,15,8,'ruin'],['moor','Heather March',49,-28,18,6,'moor'],['quarry','Widow’s Quarry',54,17,16,4.8,'quarry']];
 const regions=regionData.map(([id,name,x,z,radius,y,biome],i)=>({id,name,x:x+(i?r()*6-3:0),z:z+(i?r()*6-3:0),r:radius,y,biome}));
 const edgeIds=[[0,1],[0,2],[2,3],[3,4],[4,5],[1,7],[7,6],[6,5],r()<.5?[1,2]:[2,4],r()<.5?[1,6]:[1,5]];
 const routes=edgeIds.map(([ai,bi])=>{const a=regions[ai],b=regions[bi],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz),off=(r()-.5)*7;return {a:ai,b:bi,points:[a,{x:(a.x+b.x)/2-dz/len*off,z:(a.z+b.z)/2+dx/len*off,y:(a.y+b.y)/2},b]}});
 // Leave the village between the houses instead of grading a road through one.
 routes.find(p=>p.a===0&&p.b===2).points.splice(1,0,{x:regions[0].x-1.2,z:regions[0].z-6.9,y:regions[0].y+.05});
 const woodland=woodlandRoute(routes.find(p=>p.a===0&&p.b===2));
 function roadAt(x,z){let best={d:Infinity,y:0};for(const route of routes)for(let i=1;i<route.points.length;i++){const a=route.points[i-1],b=route.points[i],s=segmentDistance(x,z,a,b);if(s.d<best.d)best={d:s.d,y:lerp(a.y,b.y,s.t)}}return best}
 const salt=hash(seed)%1000,noise=(x,z)=>Math.sin(x*.057+salt)*Math.cos(z*.063-salt)*1.4+Math.sin(x*.18+z*.11+salt)*.45+Math.cos(x*.41-z*.23)*.12;
 const riverX=z=>-52+Math.sin(z*.034+1)*5;
 function rawHeight(x,z){let h=4+noise(x,z)+Math.max(0,-z-10)*.066;const rd=roadAt(x,z);h=lerp(h,rd.y,1-smooth(2.2,7,rd.d));for(const n of regions){const d=Math.hypot(x-n.x,z-n.z);h=lerp(h,n.y,1-smooth(n.r*.5,n.r,d))}h+=woodland.sample(x,z).offset;const riv=Math.abs(x-riverX(z)),bank=1-smooth(3,7,riv);h=lerp(h,-.65+noise(x,z)*.1,bank);return h}
 const height=triangleHeight(rawHeight,1.5,-96,128);
 function walkHeight(x,z){const rd=roadAt(x,z);return Math.abs(x-riverX(z))<7&&rd.d<2.65?Math.max(height(x,z),rd.y+.08):height(x,z)}
 const closestRegion=(x,z)=>regions.reduce((a,b)=>Math.hypot(x-a.x,z-a.z)/a.r<Math.hypot(x-b.x,z-b.z)/b.r?a:b);
 const surface={id:'surface',name:'The Bramblewild',depth:0,size:192,terrainSegments:128,regions,routes,roadAt,height,walkHeight,noise,riverX,closestRegion,woodland,rooms:[],corridors:[],colliders:[],portals:[],interactables:[],encounters:[],props:[],bounds:96};
 surface.canWalk=(x,z,rad=.38)=>Math.abs(x)<86-rad&&Math.abs(z)<86-rad&&walkHeight(x,z)>.3;
 const hub=regions[0],abbey=regions[5];
 surface.start={x:hub.x,z:hub.z+4};
 surface.interactables=[{id:'rest',kind:'rest',x:hub.x-4,z:hub.z+1,name:'Hearthwick fire',hint:'Rest · refill draughts'},{id:'mara',kind:'npc',x:hub.x+3,z:hub.z-1,name:'Mara, the surveyor',hint:'Speak to Mara'},{id:'surface-hoist',kind:'hoist',x:hub.x+8,z:hub.z-7,name:'Old freight hoist',hint:'Hoist to the Root Vault',locked:true}];
 surface.portals=[{id:'abbey-stairs',x:abbey.x,z:abbey.z-2,to:'cistern',entry:'entrance',name:'Descend beneath the abbey'}];
 for(let i=1;i<regions.length;i++){const n=regions[i],count=i===5?3:2;for(let j=0;j<count;j++){const ang=j*2.6+.3;surface.encounters.push({id:`s-${i}-${j}`,type:i===5&&j===2?'warden':i===3||i===4?'reaver':'outlaw',x:n.x+Math.cos(ang)*5,z:n.z+Math.sin(ang)*5,home:i})}surface.interactables.push({id:'cache-'+i,kind:'chest',x:n.x-2,z:n.z-6,name:i===5?'Abbey strongbox':'Wayfarer cache',hint:'Open cache',tier:i===5?2:1})}
 // Keep stable encounter IDs so old saves retain kills and opened caches.
 Object.assign(surface.encounters.find(e=>e.id==='s-2-0'),woodland.point(.83,1.4));
 Object.assign(surface.encounters.find(e=>e.id==='s-2-1'),{x:regions[2].x-5,z:regions[2].z-7});
 function dungeon(id,depth,small=false){
 const random=rng(hash(seed+id+'topology-v2')),rooms=[],rows=small?2:4,cols=small?2:3,base=depth===1?-4:-16;
 const cells=[];for(let row=0;row<rows;row++)for(let col=0;col<cols;col++)cells.push({row,col});cells.sort((a,b)=>(a.row===0&&a.col===1?-1:b.row===0&&b.col===1?1:0));
 for(let i=0;i<cells.length;i++){const {row,col}=cells[i];rooms.push({id:i,row,col,x:(col-1)*24+(i?random()*2-1:0),z:30-row*23+(i?random()*2-1:0),w:14+random()*4,h:14+random()*3,y:base-row*1.6,role:'chamber'})}
 rooms[0].role='arrival';const candidates=[];for(let a=0;a<rooms.length;a++)for(let b=a+1;b<rooms.length;b++)if(Math.abs(rooms[a].row-rooms[b].row)+Math.abs(rooms[a].col-rooms[b].col)===1)candidates.push([a,b]);
 const visited=new Set([0]),pairs=[],stack=[0];while(stack.length){const a=stack[stack.length-1],next=candidates.filter(([x,y])=>x===a&&!visited.has(y)||y===a&&!visited.has(x));if(!next.length){stack.pop();continue}const pair=next[Math.floor(random()*next.length)],b=pair[0]===a?pair[1]:pair[0];pairs.push(pair);visited.add(b);stack.push(b)}
 let extra=candidates.filter(p=>!pairs.includes(p));for(let i=0;i<(small?1:2)&&extra.length;i++){const k=Math.floor(random()*extra.length);pairs.push(extra.splice(k,1)[0])}
 const distances=new Map([[0,0]]),queue=[0];while(queue.length){const a=queue.shift();for(const [x,y]of pairs){const b=x===a?y:y===a?x:-1;if(b>=0&&!distances.has(b)){distances.set(b,distances.get(a)+1);queue.push(b)}}}let goal=rooms.reduce((a,b)=>(distances.get(a.id)??0)>(distances.get(b.id)??0)?a:b);goal.role='descent';
 const corridors=pairs.map(([ai,bi])=>{const a=rooms[ai],b=rooms[bi],vertical=Math.abs(a.z-b.z)>Math.abs(a.x-b.x),turn=vertical?{x:a.x,z:b.z}:{x:b.x,z:a.z};return {a:ai,b:bi,points:[a,turn,b],w:3.8,kind:a.y!==b.y?'stair':'passage'}});
 const inRoom=(q,x,z,pad=0)=>Math.abs(x-q.x)<q.w/2-pad&&Math.abs(z-q.z)<q.h/2-pad;
 const inside=(x,z,pad=0)=>rooms.some(q=>inRoom(q,x,z,pad))||corridors.some(c=>c.points.slice(1).some((b,j)=>segmentDistance(x,z,c.points[j],b).d<c.w/2-pad));
 function height(x,z){const q=rooms.find(q=>inRoom(q,x,z));if(q)return q.y;let best={d:Infinity,y:base};for(const c of corridors){const a=rooms[c.a],b=rooms[c.b],lens=c.points.slice(1).map((p,i)=>distance(p,c.points[i])),total=lens.reduce((a,b)=>a+b,0);let along=0;for(let i=0;i<lens.length;i++){const d=segmentDistance(x,z,c.points[i],c.points[i+1]);if(d.d<best.d){const vertical=Math.abs(c.points[1].z-a.z)>Math.abs(c.points[1].x-a.x),start=(vertical?a.h:a.w)/2,end=lens[0]-(vertical?b.h:b.w)/2;best={d:d.d,y:lerp(a.y,b.y,smooth(start,end,along+d.t*lens[i]))}}along+=lens[i]}}return best.y}
 const d={id,name:id==='quarry'?'The Quarry Workings':depth===1?'The Buried Cistern':'The Root Vault',depth,size:128,bounds:64,rooms,corridors,goalRoom:goal.id,regions:rooms.map(q=>({...q,r:9,name:q.role==='descent'?'The lower gate':'Buried chamber',biome:'dungeon'})),routes:corridors,height,walkHeight:height,canWalk:(x,z,rad=.38)=>inside(x,z,rad),inside,colliders:[],props:[],interactables:[],portals:[],encounters:[],start:{x:rooms[0].x,z:rooms[0].z+2},closestRegion:(x,z)=>rooms.reduce((a,b)=>distance({x,z},a)<distance({x,z},b)?a:b),roadAt:()=>({d:Infinity,y:base})};
 d.portals.push({id:id+'-up',x:rooms[0].x,z:rooms[0].z+4,to:id==='quarry'?'surface':depth===1?'surface':'cistern',entry:id==='quarry'?'quarry':depth===1?'abbey':'lower',name:id==='quarry'?'Return to Widow’s Quarry':depth===1?'Return to the abbey':'Climb to the cistern'});
 if(depth===1&&!small)d.portals.push({id:'cistern-down',x:goal.x,z:goal.z-2,to:'vault',entry:'entrance',name:'Descend into the Root Vault'});
 for(const q of rooms){if(!q.id)continue;const isGoal=q.id===goal.id,quiet=!isGoal&&random()<.30;q.role=isGoal?'descent':quiet?'refuge':random()<.4?'ambush':'guardroom';if(!quiet)for(let j=0;j<(isGoal?1:2);j++)d.encounters.push({id:`${id}-${q.id}-${j}`,type:isGoal?'warden':q.role==='ambush'?'reaver':'outlaw',x:q.x-2+j*4,z:q.z+1,home:q.id,tier:depth,objectiveGuardian:isGoal});if(quiet||random()<.24)d.interactables.push({id:`${id}-cache-${q.id}`,kind:'chest',x:q.x-3,z:q.z-3,name:q.role==='refuge'?'Keeper’s cache':'Sealed coffer',hint:'Open coffer',tier:depth+1,source:small?'quarry':'keepers'});}
 if(depth===2){d.interactables.push({id:'relic',kind:'relic',x:goal.x,z:goal.z-3,name:'The Rootbound seal',hint:'Recover the seal'},{id:'hoist',kind:'unlock',x:goal.x+3,z:goal.z-1,name:'Freight hoist',hint:'Restore the hoist to Hearthwick'})}
 if(depth===1&&!small){const room=rooms.find(q=>q.id&&q.id!==goal.id);room.role='refuge';d.encounters=d.encounters.filter(e=>e.home!==room.id);d.interactables.push({id:'prospector',kind:'npc',x:room.x-3,z:room.z-3,name:'Edren, the prospector',hint:'Speak to Edren'},{id:'cistern-lore',kind:'lore',x:room.x+3,z:room.z-3,name:'A keeper’s slate',hint:'Read the slate',text:'Hearthwick freight, seventh bell. Grain above. Lamp oil below. No one is to open the lower sluice after the roots begin to move.'});d.portals.push({id:'drain-unlock',x:room.x+3,z:room.z+3,to:'cellar',entry:'drain',unlock:'cellarGate',name:'Unbar the old drain · Hearthwick cellar'});d.drainRoom=room.id;}
 if(small)d.interactables.push({id:'quarry-lore',kind:'lore',x:goal.x+3,z:goal.z-3,name:'The foreman’s tally',hint:'Read the tally',text:'The abbey bought stone from us for forty years. We reached their lower foundations yesterday. The same mason’s mark is there, beneath a seam no one has ever cut.'});
 d.entryPosition=entry=>entry==='lower'?{x:goal.x,z:goal.z+2}:entry==='drain'?{x:rooms[d.drainRoom].x+2,z:rooms[d.drainRoom].z+1}:d.start;return d;
 }
 const cistern=dungeon('cistern',1),vault=dungeon('vault',2),quarry=dungeon('quarry',1,true);
 const cellar={id:'cellar',name:'The Crooked Cellar',depth:1,size:64,bounds:32,rooms:[{id:0,x:0,z:13,w:13,h:13,y:-2,role:'arrival'},{id:1,x:0,z:-7,w:13,h:13,y:-3,role:'refuge'},{id:2,x:19,z:-7,w:12,h:13,y:-4,role:'descent'}],corridors:[],colliders:[],props:[],interactables:[],portals:[],encounters:[]};
 cellar.corridors=[{a:0,b:1,points:[cellar.rooms[0],cellar.rooms[1]],w:3.8},{a:1,b:2,points:[cellar.rooms[1],cellar.rooms[2]],w:3.8}];cellar.routes=cellar.corridors;cellar.inside=(x,z,pad=0)=>cellar.rooms.some(q=>Math.abs(x-q.x)<q.w/2-pad&&Math.abs(z-q.z)<q.h/2-pad)||cellar.corridors.some(c=>segmentDistance(x,z,c.points[0],c.points[1]).d<c.w/2-pad);cellar.height=(x,z)=>x>6?lerp(-3,-4,smooth(6,13,x)):lerp(-2,-3,smooth(6,-1,z));cellar.walkHeight=cellar.height;cellar.canWalk=(x,z,rad=.38)=>cellar.inside(x,z,rad);cellar.start={x:0,z:15};cellar.regions=cellar.rooms.map(q=>({...q,r:8,name:'The Crooked Cellar'}));cellar.closestRegion=()=>cellar.regions[0];cellar.roadAt=()=>({d:Infinity,y:-2});cellar.entryPosition=entry=>entry==='drain'?{x:18,z:-5}:cellar.start;
 cellar.portals=[{id:'cellar-up',x:0,z:17,to:'surface',entry:'cellar',name:'Return to Hearthwick'},{id:'cellar-drain',x:20,z:-9,to:'cistern',entry:'drain',requires:'cellarGate',name:'The barred drain'}];cellar.interactables=[{id:'cellar-lore',kind:'lore',x:-3,z:-7,name:'A freight keeper’s journal',hint:'Read the journal',text:'There is an abbey under the abbey. I barred the drain from the other side. If they come looking, tell them I took the northern road.'},{id:'cellar-cache',kind:'chest',x:3,z:12,name:'An old traveler’s trunk',hint:'Open the trunk',tier:1,source:'cellar'}];
 surface.portals.push({id:'cellar-entry',x:hub.x+2,z:hub.z+2,to:'cellar',entry:'entrance',name:'Explore the Crooked Cellar'},{id:'quarry-entry',x:regions[7].x+5,z:regions[7].z,to:'quarry',entry:'entrance',name:'Enter the abandoned workings'});
 surface.entryPosition=entry=>entry==='abbey'?{x:abbey.x,z:abbey.z+3}:entry==='quarry'?{x:regions[7].x+5,z:regions[7].z+3}:entry==='cellar'?{x:hub.x+2,z:hub.z+5}:surface.start;

 for(const layer of [cistern,vault,cellar,quarry])layer.height=layer.walkHeight=triangleHeight(layer.height,1,-64,128);
 return {seed,surface,cistern,vault,cellar,quarry,layers:[surface,cistern,vault,cellar,quarry],get(id){return this[id]??surface}};
}
export function makeSpatial(colliders,cell=5){const grid=new Map();for(const c of colliders){for(let x=Math.floor((c.x-c.r)/cell);x<=Math.floor((c.x+c.r)/cell);x++)for(let z=Math.floor((c.z-c.r)/cell);z<=Math.floor((c.z+c.r)/cell);z++){const k=x+','+z;if(!grid.has(k))grid.set(k,[]);grid.get(k).push(c)}}return (x,z)=>{const found=new Set(),cx=Math.floor(x/cell),cz=Math.floor(z/cell);for(let a=cx-1;a<=cx+1;a++)for(let b=cz-1;b<=cz+1;b++)for(const c of grid.get(a+','+b)??[])found.add(c);return [...found]}}
export function findPath(layer,start,end,step=2){const limit=layer.bounds,n=Math.ceil(limit*2/step),key=(x,z)=>z*n+x,toCell=p=>({x:clamp(Math.round((p.x+limit)/step),0,n-1),z:clamp(Math.round((p.z+limit)/step),0,n-1)}),world=(x,z)=>({x:x*step-limit,z:z*step-limit}),a=toCell(start),b=toCell(end),open=[{...a,g:0,f:0}],prev=new Map(),scores=new Map([[key(a.x,a.z),0]]),closed=new Set();let target=key(b.x,b.z),done=null;
 for(let loops=0;open.length&&loops<4500;loops++){open.sort((a,b)=>b.f-a.f);const q=open.pop(),k=key(q.x,q.z);if(closed.has(k))continue;closed.add(k);if(k===target){done=q;break}for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=q.x+dx,z=q.z+dz;if(x<0||z<0||x>=n||z>=n)continue;const p=world(x,z),nk=key(x,z),g=q.g+1;if(closed.has(nk)||!layer.canWalk(p.x,p.z,.44)||Math.abs(layer.walkHeight(p.x,p.z)-layer.walkHeight(q.x*step-limit,q.z*step-limit))>1.1||(layer.nearby?.(p.x,p.z)??[]).some(c=>segmentDistance(c.x,c.z,world(q.x,q.z),p).d<c.r+.46)||[.25,.5,.75].some(t=>!layer.canWalk(lerp(q.x*step-limit,p.x,t),lerp(q.z*step-limit,p.z,t),.44)))continue;if(g<(scores.get(nk)??Infinity)){scores.set(nk,g);prev.set(nk,k);open.push({x,z,g,f:g+Math.abs(x-b.x)+Math.abs(z-b.z)})}}}
 if(!done)return [];const points=[];let k=target;while(prev.has(k)){points.push(world(k%n,Math.floor(k/n)));k=prev.get(k)}return points.reverse();
}
