import test from 'node:test';
import assert from 'node:assert/strict';
import * as G from '../lib/game.js';
import {initialCity,nextCityPlot,recordCityFreight,originFor,economicSources} from '../lib/city.js';
import {tileAtAxial} from '../lib/world.js';
function town(id='pelagos') {const s=G.initialState('urban-proof');s.surveys[id]=true;s.colonies[id]={site:'coast',regionId:id+':coast',policy:null,city:initialCity(),population:16,capacity:24,kind:'settlement',supplies:100,materials:100,components:0,propellant:20,development:0,mine:false,greenhouse:false,ore:100,founded:0,founder:'Pioneer 01',design:{...G.PRESETS.pioneer,kit:'habitat'},focus:'balanced',upgrades:{},project:null,shortages:0,people:[]};return s;}
const step=(s,n=1)=>{for(let i=0;i<n;i++)s=G.validateSave(G.endTurn(s));return s;};
function completeShop(s,business,activity) {const p=nextCityPlot(s,'pelagos','market');Object.assign(p,{business,remaining:0,origin:originFor(s,'pelagos',activity,s.turn)});s.colonies.pelagos.city.plots.push(p);return p;}
function clay(s) {for(let q=-10;q<10;q++)for(let r=-7;r<8;r++){const t=tileAtAxial('pelagos','coast',q,r,s.universe.seed);if(t&&G.regionalAllowed(t,'brickworks'))return t;}throw Error('Missing clay');}
test('population and inventories never create shops without economic work',()=>{let s=town();s=step(s,8);assert.equal(s.colonies.pelagos.city.plots.filter(p=>p.kind==='market').length,0);});
test('specific ready industries sustain paid shops with immutable founding history',()=>{let s=town(),r=clay(s);s=G.improveRegion(s,'pelagos',r.id,'brickworks');s=step(s);assert.equal(s.colonies.pelagos.city.plots.length,0);s=step(s,2);const p=s.colonies.pelagos.city.plots.find(p=>p.business==='repair');assert.ok(p);assert.equal(p.remaining,2);assert.equal(p.origin.suppliers[0].id,'region:'+r.id);assert.match(p.origin.reason,/Clay brickworks/);const origin=structuredClone(p.origin);s.colonies.pelagos.supplies=0;s=step(s,2);assert.equal(s.colonies.pelagos.city.plots.find(q=>q.id===p.id).remaining,2);s.colonies.pelagos.supplies=100;s=step(s,2);assert.equal(s.colonies.pelagos.city.plots.find(q=>q.id===p.id).remaining,0);assert.deepEqual(s.colonies.pelagos.city.plots.find(q=>q.id===p.id).origin,origin);});
test('an operating market can supply the last provision needed to avoid starvation',()=>{let s=town();s.colonies.pelagos.greenhouse=true;s.colonies.pelagos.population=30;s.colonies.pelagos.capacity=36;s.colonies.pelagos.supplies=0;s.colonies.pelagos.city.policy='hold';completeShop(s,'bakery','agriculture');const f=G.colonyForecast(s);assert.equal(f.primaryFood,4);assert.equal(f.food,5);assert.equal(f.fed,true);assert.equal(step(s).colonies.pelagos.shortages,0);});
test('completed secondary shops cannot sustain their own economic demand',()=>{let s=town();s.colonies.pelagos.greenhouse=true;completeShop(s,'bakery','agriculture');s.colonies.pelagos.greenhouse=false;const f=G.colonyForecast(s);assert.equal(f.food,0);assert.equal(f.city.activity.agriculture,0);assert.equal(f.businesses.bakery.operating,false);s=step(s,8);assert.equal(s.colonies.pelagos.city.plots.filter(p=>p.business).length,1);});
test('incoming external freight activates the same business forecast as the actual delivery',()=>{let s=town();s=G.commissionService(s,'pelagos');s.services[0].remaining=1;completeShop(s,'freight','trade');const f=G.colonyForecast(s),n=step(s),actual=G.colonyForecast(n,n.turn,'pelagos',false);assert.ok(f.businesses.freight.operating);assert.equal(f.work,actual.work);assert.equal(f.city.activity.trade,actual.city.activity.trade);assert.ok(n.colonies.pelagos.city.freight[0].deliveries[0].units>0);});
test('local orbital shuttles and empty flights do not count as external trade',()=>{const s=town();s.services.push({id:'local',source:'pelagos',destination:'orbit:pelagos',remaining:1,waiting:null,cargo:{materials:8,provisions:0,propellant:0,components:0}});recordCityFreight(s,s.services[0],8);assert.equal(G.colonyForecast(s).city.activity.trade,0);assert.equal(economicSources(s,'pelagos',1).some(q=>q.activity==='trade'),false);assert.equal(s.colonies.pelagos.city.freight.length,0);});
test('v7 towns retain construction and positions without invented historical suppliers',()=>{let s=town();s.colonies.pelagos.greenhouse=true;s=step(s,2);s.version=7;delete s.colonies.pelagos.city.commerce;for(const p of s.colonies.pelagos.city.plots){delete p.business;delete p.origin;}const before=structuredClone(s),n=G.validateSave(s);assert.equal(n.version,8);assert.deepEqual(G.inventory(n,'pelagos'),G.inventory(before,'pelagos'));assert.equal(n.colonies.pelagos.city.plots[0].x,before.colonies.pelagos.city.plots[0].x);assert.equal(n.colonies.pelagos.city.plots[0].remaining,2);assert.deepEqual(n.colonies.pelagos.city.plots[0].origin.suppliers,[]);assert.deepEqual(G.validateSave(n),n);});
