import * as THREE from 'three';
import {ITEMS,rollItem} from './hero.js';
import {clamp,random} from './terrain.js';
export const ATTACKS={slash:{duration:.43,active:.176,recovery:.29,stamina:8,damage:1,arc:1.22,reach:1},cleave:{duration:.83,active:.415,recovery:.65,stamina:28,damage:1.85,arc:1.55,reach:1.35},roll:{duration:.46,active:0,recovery:.4,stamina:22}};
export class Adventure{
 constructor({scene,hero,ramp,getWorld,getColliders,onEvent=()=>{}}){Object.assign(this,{scene,hero,ramp,getWorld,getColliders,onEvent});this.root=new THREE.Group();scene.add(this.root);this.enemies=[];this.loot=[];this.effects=[];this.materials=[];this.geos=[];this.time=0;this.stats={kills:0,hits:0,swings:0,dodges:0};this.inventory=new Set(['sword','buckler','leather','hood']);this.potions=3;this.gold=0;this.hp=100;this.stamina=100;this.action=null;this.buffer=null;this.combo=0;this.iframe=0;this.hurt=0;this.hitstop=0;this.dead=false;this.paused=false;this.velocity=new THREE.Vector2();this.moveDirection=new THREE.Vector2(0,1);this.rng=random(47);this.geometry={box:new THREE.BoxGeometry(1,1,1),ico:new THREE.IcosahedronGeometry(1,1),rock:new THREE.IcosahedronGeometry(1,0),cyl:new THREE.CylinderGeometry(1,1,1,8),cone:new THREE.ConeGeometry(1,1,7)};this.geos.push(...Object.values(this.geometry));}
 material(c,basic=false){const m=basic?new THREE.MeshBasicMaterial({color:c}):new THREE.MeshToonMaterial({color:c,gradientMap:this.ramp});this.materials.push(m);return m}
 part(parent,type,c,x,y,z,sx,sy,sz){const m=new THREE.Mesh(this.geometry[type],this.material(c));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 ring(radius,color,opacity=.55){const g=new THREE.RingGeometry(radius*.9,radius,48);this.geos.push(g);const m=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));this.materials.push(m.material);m.rotation.x=-Math.PI/2;this.root.add(m);return m}
 reset(){const shared=new Set(Object.values(this.geometry));for(const m of this.materials)m.dispose();for(const g of this.geos)if(!shared.has(g))g.dispose();this.materials=[];this.geos=[...shared];for(const e of this.enemies){this.root.remove(e.mesh,e.telegraph)}for(const l of this.loot)this.root.remove(l.mesh);for(const e of this.effects)this.root.remove(e.mesh);this.enemies=[];this.loot=[];this.effects=[];this.hp=100;this.stamina=100;this.potions=3;this.dead=false;this.action=null;this.buffer=null;this.velocity.set(0,0);this.iframe=1;this.stats={kills:0,hits:0,swings:0,dodges:0};this.time=0;this.rng=random(this.getWorld().hash+971);this.spawnEncounters();this.onEvent({type:'reset'});}
 spawnEncounters(){const w=this.getWorld();let id=0;const spawn=(type,p,dx=0,dz=0,drop=null)=>{let x=p.x+dx,z=p.z+dz;const spot=this.findSpot(x,z,3);if(!spot)return;this.enemies.push(this.createEnemy(type,spot.x,spot.z,id++,drop))};const a=w.routes[0][25];spawn('slime',a,1,2,'axe');spawn('slime',a,-2,-1,'potion');const b=w.routes[3][34];spawn('raider',b,1,2,'helm');spawn('slime',b,-2,-1);const c=w.routes[2][30];spawn('raider',c,2,-1,'tower');spawn('slime',c,-1,3);const d=w.routes[1][33];spawn('raider',d,-1,2,'iron');spawn('slime',d,2,-1);const shrine=w.landmarks[2];spawn('sentinel',{x:shrine.x,z:shrine.z+5},0,0,'tower');spawn('slime',shrine,-4,5);const court=w.landmarks[4];spawn('raider',court,-2,1,'iron');spawn('slime',court,2,1,'potion');const camp=w.landmarks[3];this.drop('potion',camp.x+2,camp.z+3);const v=w.landmarks[0];this.drop('axe',v.x+5,v.z+3);}
 findSpot(x,z,r=4){const w=this.getWorld();for(let i=0;i<25;i++){const a=i*2.4,rr=i===0?0:r*Math.sqrt(i/25),px=x+Math.cos(a)*rr,pz=z+Math.sin(a)*rr,h=w.walkHeight(px,pz);if(h>.9&&w.slope(px,pz)<.95&&!this.getColliders().some(c=>Math.hypot(px-c.x,pz-c.z)<c.r+.9))return{x:px,z:pz}}return null}
 createEnemy(type,x,z,id,drop){const mesh=new THREE.Group(),body=new THREE.Group();mesh.add(body);this.root.add(mesh);const sentinel=type==='sentinel',slime=type==='slime',maxHp=sentinel?210:slime?48:85;let arm=null;
 if(slime){this.part(body,'ico','#bc6962',0,.62,0,.83,.65,.78);this.part(body,'ico','#d98a6d',-.25,.85,.1,.4,.27,.43);for(const xx of [-.22,.22]){this.part(body,'ico','#f9e5af',xx,.77,.65,.14,.17,.07);this.part(body,'box','#372e34',xx,.77,.72,.065,.12,.02)}this.part(body,'box','#6d3f40',0,.48,.72,.23,.06,.03)}else if(sentinel){this.part(body,'rock','#7d9288',0,1.7,0,1.25,1.15,.72);this.part(body,'rock','#9baa93',0,3.05,0,.63,.62,.59);this.part(body,'box','#7de2ce',0,3.14,.53,.67,.12,.08);this.part(body,'rock','#7fd0c0',0,1.88,.71,.3,.47,.1);for(const xx of [-1,1]){this.part(body,'rock','#687e74',xx*1.35,1.6,0,.50,1.05,.52);this.part(body,'rock','#809488',xx*.63,.45,0,.52,.57,.62)}arm=this.part(body,'rock','#9eac92',1.4,.75,.15,.6,.6,.64)}else{this.part(body,'ico','#647d55',0,1.12,0,.46,.61,.32);this.part(body,'ico','#9dae69',0,1.93,.03,.38,.42,.34);for(const xx of [-.43,.43])this.part(body,'cone','#94a367',xx,1.99,0,.23,.5,.16).rotation.z=xx>0?-1:1;this.part(body,'box','#c8a879',0,1.53,.32,.4,.13,.1);for(const xx of [-.15,.15])this.part(body,'box','#282f2f',xx,1.98,.35,.08,.1,.035);this.part(body,'box','#674d39',0,.92,.01,.75,.2,.60);for(const xx of [-.25,.25])this.part(body,'box','#5c5140',xx,.34,.04,.23,.68,.32);arm=new THREE.Group();arm.position.set(.5,1.42,0);body.add(arm);this.part(arm,'box','#909c61',0,-.22,0,.19,.55,.24);this.part(arm,'box','#6b4938',0,-.38,.7,.17,.17,1.2);this.part(arm,'rock','#878b77',0,-.38,1.35,.38,.36,.5);this.part(body,'box','#8d473b',0,1.43,-.26,.7,.22,.3)}
 const range=sentinel?3.8:slime?1.65:2.2,telegraph=this.ring(range,'#e8a16a',.7);telegraph.visible=false;mesh.position.set(x,this.getWorld().walkHeight(x,z)+.04,z);
 return{id,type,mesh,body,arm,spawn:new THREE.Vector2(x,z),hp:maxHp,maxHp,range,radius:sentinel?1.1:slime?.7:.65,speed:sentinel?1.8:slime?2.5:3.35,state:'idle',timer:1+this.rng(),age:this.rng()*6,windup:sentinel?1.25:slime?.72:.85,recovery:sentinel?1.3:slime?.8:.85,target:new THREE.Vector2(x,z),telegraph,flash:0,drop,dead:false,engaged:false,damage:sentinel?30:slime?12:19};
 }
 equip(id){const item=ITEMS[id];if(!item||!this.inventory.has(id))return false;this.hero.equip(item.slot,id);this.onEvent({type:'equipment',id});return true}
 get weapon(){return ITEMS[this.hero.equipment.weapon]}
 get defense(){return Object.values(this.hero.equipment).reduce((n,id)=>n+(ITEMS[id].defense??0),0)}
 request(type,aim=null){if(this.dead||this.paused)return false;if(type==='potion'){if(this.potions&&this.hp<100){this.potions--;this.hp=Math.min(100,this.hp+45);this.onEvent({type:'heal',value:45});return true}return false}if(!ATTACKS[type])return false;if(this.action){if(type==='roll'&&this.action.type!=='roll'&&this.action.age/this.action.duration>=this.action.spec.recovery/this.action.spec.duration){this.action=null;return this.start(type,aim)}this.buffer={type,aim,expires:this.time+.18};return false}return this.start(type,aim)}
 start(type,aim){const spec=ATTACKS[type];if(this.stamina<spec.stamina)return false;const p=this.hero.root;this.stamina-=spec.stamina;let angle=p.rotation.y;if(aim&&Math.hypot(aim.x-p.position.x,aim.z-p.position.z)>.2)angle=Math.atan2(aim.x-p.position.x,aim.z-p.position.z);else if(type==='roll'&&this.moveDirection.length()>.1)angle=Math.atan2(this.moveDirection.x,this.moveDirection.y);else if(type!=='roll'){const e=this.enemies.filter(e=>!e.dead&&e.engaged&&e.mesh.position.distanceTo(p.position)<4.5).sort((a,b)=>a.mesh.position.distanceToSquared(p.position)-b.mesh.position.distanceToSquared(p.position))[0];if(e)angle=Math.atan2(e.mesh.position.x-p.position.x,e.mesh.position.z-p.position.z)}p.rotation.y=angle;this.action={type,age:0,duration:spec.duration/(type==='roll'?1:this.weapon.speed),angle,weapon:{...this.weapon},fired:false,combo:this.combo++,spec};this.stats[type==='roll'?'dodges':'swings']++;this.onEvent({type:'action',action:type});return true}
 canMove(from,x,z,r=.28){const w=this.getWorld(),h=w.walkHeight(x,z),old=w.walkHeight(from.x,from.z);if(h<.65||Math.abs(x)>66||Math.abs(z)>66||Math.abs(h-old)>.18+Math.hypot(x-from.x,z-from.z)*1.15)return false;return !this.getColliders().some(c=>(x-c.x)**2+(z-c.z)**2<(c.r+r)**2)}
 move(obj,dx,dz,r=.28){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.14));let moved=0;for(let i=0;i<steps;i++){const x=obj.position.x,z=obj.position.z;if(this.canMove(obj.position,x+dx/steps,z,r))obj.position.x+=dx/steps;if(this.canMove(obj.position,obj.position.x,z+dz/steps,r))obj.position.z+=dz/steps;moved+=Math.hypot(obj.position.x-x,obj.position.z-z);obj.position.y=this.getWorld().walkHeight(obj.position.x,obj.position.z)+.04}return moved}
 arcHit(e,spec){const p=this.hero.root.position,q=e.mesh.position,dx=q.x-p.x,dz=q.z-p.z,d=Math.hypot(dx,dz);if(d>this.action.weapon.reach*spec.reach+e.radius||Math.abs(q.y-p.y)>2.3)return false;const dot=(dx*Math.sin(this.action.angle)+dz*Math.cos(this.action.angle))/Math.max(.001,d);if(dot<Math.cos(spec.arc))return false;const len2=dx*dx+dz*dz;for(const c of this.getColliders()){const t=clamp(((c.x-p.x)*dx+(c.z-p.z)*dz)/Math.max(.001,len2),0,1);if(t>.03&&t<.97&&Math.hypot(p.x+t*dx-c.x,p.z+t*dz-c.z)<c.r*.9)return false}return true}
 hitEnemy(e,damage){if(e.dead)return;e.hp-=damage;e.flash=.16;this.stats.hits++;this.onEvent({type:'hit',value:damage,position:e.mesh.position.clone().add(new THREE.Vector3(0,2,0))});this.burst(e.mesh.position,'#f9e8b2',7);this.hitstop=.045;const p=this.hero.root.position,delta=new THREE.Vector2(e.mesh.position.x-p.x,e.mesh.position.z-p.z).normalize();this.move(e.mesh,delta.x*.5,delta.y*.5,e.radius*.6);if(e.hp<=0){e.dead=true;e.state='dead';e.timer=.55;e.telegraph.visible=false;this.stats.kills++;this.drop(e.drop??'gold',e.mesh.position.x,e.mesh.position.z,true,e.type==='sentinel');this.drop('gold',e.mesh.position.x+.5,e.mesh.position.z+.3);this.onEvent({type:'kill',enemy:e.type});if(this.enemies.every(q=>q.dead))this.onEvent({type:'victory'});}else if(e.type!=='sentinel'){e.state='stagger';e.timer=.28;e.telegraph.visible=false}}
 hitPlayer(damage,from){const to=this.hero.root.position,dx=to.x-from.x,dz=to.z-from.z,len2=dx*dx+dz*dz;for(const c of this.getColliders()){const t=clamp(((c.x-from.x)*dx+(c.z-from.z)*dz)/Math.max(.001,len2),0,1);if(t>.03&&t<.97&&Math.hypot(from.x+t*dx-c.x,from.z+t*dz-c.z)<c.r*.9)return false}if(this.dead||this.iframe>0||(this.action?.type==='roll'&&this.action.age>.035&&this.action.age<.34))return false;const actual=Math.max(2,damage-this.defense);this.hp=Math.max(0,this.hp-actual);this.hurt=.20;this.iframe=.8;this.action=null;this.buffer=null;this.onEvent({type:'hurt',value:actual});const d=new THREE.Vector2(this.hero.root.position.x-from.x,this.hero.root.position.z-from.z).normalize();this.move(this.hero.root,d.x*.6,d.y*.6);if(this.hp<=0){this.dead=true;this.velocity.set(0,0);this.onEvent({type:'death'})}return true}
 update(dt,input=new THREE.Vector2(),aim=null){if(this.paused)return;this.time+=dt;this.iframe=Math.max(0,this.iframe-dt);this.hurt=Math.max(0,this.hurt-dt);if(this.hitstop>0){this.hitstop-=dt;return}const p=this.hero.root,prev=p.position.clone();if(!this.dead){if(input.length()>.1)this.moveDirection.copy(input);if(this.action){const a=this.action;a.age+=dt;const prog=a.age/a.duration;if(a.type==='roll'){this.move(p,Math.sin(a.angle)*12.5*dt,Math.cos(a.angle)*12.5*dt);this.velocity.set(0,0)}else{if(prog>.18&&prog<.58)this.move(p,Math.sin(a.angle)*1.7*dt,Math.cos(a.angle)*1.7*dt);if(!a.fired&&a.age>=a.spec.active/a.weapon.speed){a.fired=true;for(const e of this.enemies)if(!e.dead&&this.arcHit(e,a.spec))this.hitEnemy(e,Math.round(a.weapon.damage*a.spec.damage));this.slashEffect(a)}}if(a.age>=a.duration){this.action=null;if(this.buffer&&this.buffer.expires>=this.time){const b=this.buffer;this.buffer=null;this.start(b.type,b.aim)}}}else{const moveMultiplier=Object.values(this.hero.equipment).reduce((n,id)=>n*(1-(ITEMS[id].movePenalty??0)),1);const target=input.clone().multiplyScalar(6.5*moveMultiplier);this.velocity.lerp(target,1-Math.exp(-dt*22));this.move(p,this.velocity.x*dt,this.velocity.y*dt);if(this.velocity.length()>.12){let angle=Math.atan2(this.velocity.x,this.velocity.y);if(aim&&input.length()>.1)angle=Math.atan2(aim.x-p.position.x,aim.z-p.position.z);p.rotation.y+=Math.atan2(Math.sin(angle-p.rotation.y),Math.cos(angle-p.rotation.y))*(1-Math.exp(-dt*20))}this.stamina=Math.min(100,this.stamina+26*dt)}}
 for(const e of this.enemies)this.updateEnemy(e,dt);this.updateLoot(dt);this.updateEffects(dt);const speed=p.position.distanceTo(prev)/Math.max(dt,.001);this.hero.animate(dt,{speed:Math.min(speed,9),time:this.time,action:this.action?.type??'idle',progress:this.action?this.action.age/this.action.duration:0,combo:this.action?.combo??0,hurt:this.hurt,dead:this.dead});}
 updateEnemy(e,dt){e.age+=dt;e.flash=Math.max(0,e.flash-dt);if(e.dead){e.timer-=dt;e.body.scale.setScalar(Math.max(.02,e.timer/.55));if(e.timer<=0)e.mesh.visible=false;return}const p=this.hero.root.position,pos=e.mesh.position,dx=p.x-pos.x,dz=p.z-pos.z,d=Math.hypot(dx,dz),safe=Math.hypot(p.x-this.getWorld().landmarks[0].x,p.z-this.getWorld().landmarks[0].z)<7;
 if(e.state==='idle'){e.timer-=dt;if(d<12&&!safe&&!this.dead){e.engaged=true;e.state='chase'}else{e.body.rotation.y=Math.sin(e.age*.3)*.15}}
 if(e.state==='chase'){if(d>21||safe||this.dead){e.state='return';e.engaged=false}else if(d<e.range+(e.type==='slime'?1.5:.6)&&this.enemies.filter(q=>q.state==='windup'||q.state==='strike').length<2){e.state='windup';e.timer=e.windup;e.target.set(p.x,p.z);e.mesh.rotation.y=Math.atan2(dx,dz);e.telegraph.visible=true;const center=e.type==='slime'?e.target:new THREE.Vector2(pos.x,pos.z);e.telegraph.position.set(center.x,this.getWorld().walkHeight(center.x,center.y)+.09,center.y);e.telegraph.scale.setScalar(.4)}else{const vec=new THREE.Vector2(dx,dz).normalize();if(d<e.range+.5)vec.set(vec.y,-vec.x);for(const other of this.enemies){if(other===e||other.dead)continue;const ox=pos.x-other.mesh.position.x,oz=pos.z-other.mesh.position.z,dd=Math.hypot(ox,oz);if(dd<e.radius+other.radius+.6&&dd>.01){vec.x+=ox/dd*.6;vec.y+=oz/dd*.6}}vec.normalize();const moved=this.move(e.mesh,vec.x*e.speed*dt,vec.y*e.speed*dt,e.radius*.55);if(moved<e.speed*dt*.3)this.move(e.mesh,vec.y*e.speed*dt,-vec.x*e.speed*dt,e.radius*.55);e.mesh.rotation.y=Math.atan2(vec.x,vec.y)}}
 else if(e.state==='return'){const dx=e.spawn.x-pos.x,dz=e.spawn.y-pos.z,dist=Math.hypot(dx,dz);if(dist<1)e.state='idle';else this.move(e.mesh,dx/dist*e.speed*dt,dz/dist*e.speed*dt,e.radius*.55)}
 else if(e.state==='windup'){e.timer-=dt;const progress=1-e.timer/e.windup;e.telegraph.scale.setScalar(.4+.6*progress);e.telegraph.material.color.set(progress>.75?'#ed6d56':'#eeb46f');if(e.timer<=0){e.state='strike';e.timer=e.type==='slime'?.28:.2;e.struck=false;e.start=pos.clone()}}
 else if(e.state==='strike'){e.timer-=dt;if(e.type==='slime'){const t=clamp(1-e.timer/.28,0,1),x=THREE.MathUtils.lerp(e.start.x,e.target.x,t),z=THREE.MathUtils.lerp(e.start.z,e.target.y,t);this.move(e.mesh,x-pos.x,z-pos.z,e.radius*.5);e.body.position.y=Math.sin(t*Math.PI)*1.1}if(!e.struck&&(e.type!=='slime'||e.timer<.05)){e.struck=true;const dist=Math.hypot(p.x-pos.x,p.z-pos.z);const facing=(dx*Math.sin(e.mesh.rotation.y)+dz*Math.cos(e.mesh.rotation.y))/Math.max(d,.001);if(dist<e.range+.25&&Math.abs(p.y-pos.y)<2&&(e.type!=='raider'||facing>.15))this.hitPlayer(e.damage,pos);if(e.type==='sentinel'){const ring=this.ring(1,'#e0c994',.65);ring.position.copy(pos);ring.position.y+=.12;this.effects.push({mesh:ring,age:0,duration:.45,kind:'shock'})}}if(e.timer<=0){e.state='recover';e.timer=e.recovery;e.telegraph.visible=false;e.body.position.y=0}}
 else if(e.state==='recover'||e.state==='stagger'){e.timer-=dt;if(e.timer<=0)e.state='chase'}
 if(e.type==='slime'&&e.state!=='strike'){const bounce=Math.sin(e.age*5);e.body.position.y=e.state==='windup'?0:Math.max(0,bounce)*.15;e.body.scale.set(1+(e.state==='windup'?.25:0),e.state==='windup'?.63:1+Math.cos(e.age*5)*.05,1+(e.state==='windup'?.25:0))}else if(e.type!=='slime'){e.body.position.y=e.state==='chase'?Math.abs(Math.sin(e.age*8))*.07:0;if(e.arm)e.arm.rotation.x=e.state==='windup'?-1.2:e.state==='strike'?.6:Math.sin(e.age*4)*.08}
 e.mesh.traverse(o=>{if(o.isMesh&&o.material.emissive)o.material.emissive.set(e.flash>0?'#93543a':'#000000')});}
 slashEffect(a){const g=new THREE.RingGeometry(.8,a.weapon.reach*a.spec.reach,30,1,0,a.spec.arc*2),mat=new THREE.MeshBasicMaterial({color:a.type==='cleave'?'#8ee4d7':'#fff0b1',transparent:true,opacity:.48,side:THREE.DoubleSide,depthWrite:false}),m=new THREE.Mesh(g,mat);this.geos.push(g);this.materials.push(mat);m.rotation.x=-Math.PI/2;m.rotation.z=a.angle-Math.PI/2-a.spec.arc;m.position.copy(this.hero.root.position);m.position.y+=.85;this.root.add(m);this.effects.push({mesh:m,age:0,duration:.17,kind:'slash'})}
 burst(pos,c,n){for(let i=0;i<n;i++){const m=new THREE.Mesh(this.geometry.rock,this.material(c,true));m.scale.setScalar(.055+this.rng()*.07);m.position.copy(pos);m.position.y+=.7;this.root.add(m);const a=this.rng()*Math.PI*2;this.effects.push({mesh:m,age:0,duration:.3+this.rng()*.25,v:new THREE.Vector3(Math.cos(a)*3,2+this.rng()*3,Math.sin(a)*3),kind:'particle'})}}
 updateEffects(dt){for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.age+=dt;const t=e.age/e.duration;if(e.v){e.v.y-=12*dt;e.mesh.position.addScaledVector(e.v,dt)}else{e.mesh.material.opacity=(1-t)*.55;if(e.kind==='shock')e.mesh.scale.setScalar(1+t*4)}if(t>=1){this.root.remove(e.mesh);e.mesh.material.dispose();const mi=this.materials.indexOf(e.mesh.material);if(mi>=0)this.materials.splice(mi,1);if(e.kind!=='particle'){e.mesh.geometry.dispose();const gi=this.geos.indexOf(e.mesh.geometry);if(gi>=0)this.geos.splice(gi,1)}this.effects.splice(i,1)}}}
 drop(id,x,z,rolled=false,rare=false){if(rolled&&ITEMS[id])id=rollItem(id,this.rng,rare);const mesh=new THREE.Group();this.root.add(mesh);const c=id==='gold'?'#e3c36b':id==='potion'?'#cc645b':ITEMS[id]?.rarity==='rare'?'#86bae9':ITEMS[id]?.rarity==='uncommon'?'#8acb83':'#dfd0a0';const gem=this.part(mesh,id==='gold'?'cyl':'rock',c,0,.42,0,.22,.32,.22);if(id==='gold')gem.rotation.x=Math.PI/2;else if(id==='potion')this.part(mesh,'cyl','#e3d6a4',0,.76,0,.1,.14,.1);else{this.part(mesh,'box','#e6dfb7',0,1.05,0,.05,.95,.05);this.part(mesh,'box',c,.2,1.42,0,.4,.28,.04)}mesh.position.set(x,this.getWorld().walkHeight(x,z)+.1,z);this.loot.push({id,mesh,age:0,picked:false});}
 updateLoot(dt){for(const l of this.loot){if(l.picked)continue;l.age+=dt;l.mesh.children[0].rotation.y+=dt;l.mesh.position.y=this.getWorld().walkHeight(l.mesh.position.x,l.mesh.position.z)+.12+Math.sin(l.age*3)*.08;if(!this.dead&&l.age>.4&&this.hero.root.position.distanceTo(l.mesh.position)<1.7){l.picked=true;this.root.remove(l.mesh);if(l.id==='gold'){this.gold+=5;this.onEvent({type:'gold'})}else if(l.id==='potion'){this.potions=Math.min(9,this.potions+1);this.onEvent({type:'pickup',id:l.id})}else{this.inventory.add(l.id);this.onEvent({type:'pickup',id:l.id})}}}}
 nearbyLoot(){return this.loot.filter(l=>!l.picked&&l.mesh.position.distanceTo(this.hero.root.position)<5)}
 snapshot(){return {hp:this.hp,stamina:this.stamina,potions:this.potions,gold:this.gold,kills:this.stats.kills,total:this.enemies.length,defense:this.defense,equipment:{...this.hero.equipment},inventory:[...this.inventory],action:this.action?.type??'idle',dead:this.dead,enemies:this.enemies.map(e=>({id:e.id,type:e.type,hp:e.hp,state:e.state,x:e.mesh.position.x,z:e.mesh.position.z})),stats:{...this.stats}}}
}
