import * as THREE from 'three';
import {createHero,ITEMS} from './hero.js';
import {Adventure} from './combat.js';
import {addWorldDetails} from './world-details.js';
import {SoftwareRenderer} from './software-renderer.js';
import {makeWorld,SIZE,N,STEP,clamp,mix,smooth,random} from './terrain.js';
const d3=window.d3;
const state={seed:'BRAMBLE-47',ruggedness:.55,density:.64,time:15.5,resolution:1,motion:true,wireframe:false,mode:'explore'};
const canvas=document.querySelector('#scene');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'})}catch(e){renderer=new SoftwareRenderer({canvas});document.body.dataset.renderer='software';document.querySelector('#stats').title='Software fallback: no shadows, water shader, or stepped GPU lighting.'}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#91bbb3');scene.fog=new THREE.Fog('#91bbb3',110,245);
const camera=new THREE.PerspectiveCamera(40,1,.2,450);
const sun=new THREE.DirectionalLight('#fff0c1',2.5);sun.position.set(-42,65,28);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-78,right:78,top:78,bottom:-78,near:1,far:190});sun.shadow.normalBias=.12;sun.shadow.bias=-.0001;scene.add(sun);scene.add(sun.target);
const hemi=new THREE.HemisphereLight('#c2e5ea','#667347',1.7);scene.add(hemi);
const ramp=new THREE.DataTexture(new Uint8Array([70,125,187,255]),4,1,THREE.RedFormat);ramp.minFilter=ramp.magFilter=THREE.NearestFilter;ramp.needsUpdate=true;
const propMaterial=new THREE.MeshToonMaterial({color:0xffffff,gradientMap:ramp});
const terrainMaterial=new THREE.MeshLambertMaterial({vertexColors:true});
const geometries={box:new THREE.BoxGeometry(1,1,1),cone:new THREE.ConeGeometry(1,1,7),cyl:new THREE.CylinderGeometry(1,1,1,8),trunk:new THREE.CylinderGeometry(.65,1,1,6),ico:new THREE.IcosahedronGeometry(1,0),crown:new THREE.IcosahedronGeometry(1,1),crystal:new THREE.OctahedronGeometry(1,0)};
// A gabled roof keeps an unmistakable silhouette even at small screen sizes.
const roof=new THREE.BufferGeometry();roof.setAttribute('position',new THREE.Float32BufferAttribute([-1,0,-1, 1,0,-1, 0,1,-1, -1,0,1, 0,1,1, 1,0,1, -1,0,-1,0,1,-1,0,1,1, -1,0,-1,0,1,1,-1,0,1, 1,0,-1,1,0,1,0,1,1, 1,0,-1,0,1,1,0,1,-1],3));{const p=roof.attributes.position.array;for(let i=0;i<p.length;i+=9)for(let k=0;k<3;k++){const t=p[i+3+k];p[i+3+k]=p[i+6+k];p[i+6+k]=t}}roof.computeVertexNormals();geometries.roof=roof;
let group=new THREE.Group();scene.add(group);let world,batches={},colliders=[],mills=[],clouds=[],terrain,waters=[],forest=[],frame=0,elapsed=0;
const transform=new THREE.Object3D(),color=new THREE.Color();
function put(type,c,x,y,z,sx=1,sy=1,sz=1,ry=0,rx=0,rz=0){(batches[type]??=[]).push({c,x,y,z,sx,sy,sz,ry,rx,rz})}
function box(c,x,y,z,sx,sy,sz,ry=0){put('box',c,x,y,z,sx,sy,sz,ry)}
function commitBatches(){for(const [type,arr] of Object.entries(batches)){const mesh=new THREE.InstancedMesh(geometries[type],propMaterial,arr.length);arr.forEach((p,i)=>{transform.position.set(p.x,p.y,p.z);transform.rotation.set(p.rx,p.ry,p.rz);transform.scale.set(p.sx,p.sy,p.sz);transform.updateMatrix();mesh.setMatrixAt(i,transform.matrix);mesh.setColorAt(i,color.set(p.c))});mesh.castShadow=true;mesh.receiveShadow=true;mesh.instanceMatrix.needsUpdate=true;group.add(mesh)}}
const pal={grass:['#83a655','#8dab5b','#799c50','#92af61'],wood:'#6a4532',stone:'#8b9987',cream:'#e6d6ad',roof:'#b9553e'};
function tree(x,z,s,pine=false){const y=world.ground(x,z),r=world.rng,mo=world.moisture(x,z),type=pine?'pine':mo<.33&&r()<.30?'dead':mo>.55?'birch':'oak';
 if(type==='dead'){put('trunk','#807a62',x,y+2.2*s,z,.30*s,4.4*s,.30*s,.2);for(let j=0;j<3;j++){const a=j*2.1;put('trunk','#857d65',x+Math.sin(a)*.5*s,y+(2.7+j*.4)*s,z+Math.cos(a)*.5*s,.11*s,2*s,.11*s,a,.65,.25)} }
 else if(type==='birch'){put('trunk','#e0dbc0',x,y+2.7*s,z,.23*s,5.4*s,.23*s);for(let j=0;j<5;j++)box('#665f50',x+.1*s,y+(.7+j*.8)*s,z+.15*s,.22*s,.09*s,.06*s,j*.9);put('crown','#a1b956',x,y+5.5*s,z,1.45*s,2.1*s,1.3*s,r()*6);put('ico','#b2bd65',x+.7*s,y+6.55*s,z-.1*s,.95*s,1.3*s,1*s,r()*6);put('ico','#7b9e4b',x-.6*s,y+4.7*s,z+.35*s,1.15*s,1.3*s,1.1*s)}
 else if(type==='pine'){put('trunk','#6f5040',x,y+1.8*s,z,.32*s,3.6*s,.32*s,r()*6);for(let j=0;j<4;j++)put('cone',['#325f50','#3d7054','#4b8059','#638f5d'][j],x,y+(2.9+j*1.15)*s,z,(2.2-j*.43)*s,3.1*s,(2.2-j*.43)*s,r()*6)}
 else{put('trunk','#76523b',x,y+1.6*s,z,.46*s,3.3*s,.46*s,r()*6);for(let j=0;j<3;j++){const a=j*2.1;put('trunk','#806043',x+Math.sin(a)*.6*s,y+2.7*s,z+Math.cos(a)*.6*s,.17*s,2*s,.17*s,a,.7)}put('crown','#6e9644',x,y+4.1*s,z,2.4*s,1.8*s,2.3*s,r()*6);put('crown','#89a64d',x+1*s,y+4.85*s,z-.2*s,1.6*s,1.5*s,1.7*s,r()*6);put('ico','#5f863f',x-1.45*s,y+3.9*s,z+.5*s,1.6*s,1.3*s,1.7*s,r()*6)}
 colliders.push({x,z,r:(type==='oak'?.52:.32)*s});forest.push({x,z,s,type})}
function house(x,z,w=4.8,d=4.3,ry=0,roofColor=pal.roof){const y=world.ground(x,z),h=3.4;const local=(a,b,c)=>({x:x+a*Math.cos(ry)+c*Math.sin(ry),y:y+b,z:z-a*Math.sin(ry)+c*Math.cos(ry)});const b=(c,a,v,k,sx,sy,sz)=>{const p=local(a,v,k);box(c,p.x,p.y,p.z,sx,sy,sz,ry)};
 b('#8b8a70',0,.15,0,w+.35,.65,d+.3);b(pal.cream,0,h/2+.35,0,w,h,d);const rp=local(0,h+.35,0);put('roof',roofColor,rp.x,rp.y,rp.z,w*.62,2.5,d*.63,ry);
 b(pal.wood,0,.6,d/2+.035,w+.08,.17,.15);b(pal.wood,0,2.8,d/2+.05,w+.08,.15,.15);
 for(const a of [-w/2+.12,w/2-.12])b(pal.wood,a,h/2+.35,d/2+.09,.19,h,.18);
 b('#553e2f',.45,1.35,d/2+.12,1.1,2,.18);b('#d1cbb0',.45,.26,d/2+.5,1.7,.3,.85);b('#ddb767',.7,1.4,d/2+.24,.08,.08,.06);
 b('#584c35',-1.15,1.9,d/2+.11,.98,1.1,.13);b('#f4cc76',-1.15,1.9,d/2+.2,.75,.84,.06);b(pal.wood,-1.15,1.9,d/2+.25,.06,.95,.07);b(pal.wood,-1.15,1.9,d/2+.25,.85,.06,.07);
 b('#968c75',w*.28,4.8,-d*.19,.64,2.4,.7);b('#746e62',w*.28,6.04,-d*.19,.85,.22,.88);
 for(let k=0;k<5;k++){const yy=h+.5+k*.43,xx=w*.62*(1-(yy-h-.35)/2.5);b('#cc7550',-xx,yy,0,.09,.055,d*1.27);b('#974b3a',xx,yy,0,.08,.055,d*1.27)}
 colliders.push({x,z,r:Math.max(w,d)*.56});
}
function village(l){house(l.x-5,l.z-4,5.6,4.8,.14);house(l.x+5.5,l.z-3,4.5,4.2,-.35,'#9c5648');house(l.x-5,l.z+5.5,4.4,4.1,1.8,'#be7650');
 const y=l.y;put('cyl','#8a998c',l.x,y+.45,l.z,1.3,.8,1.3);put('cyl','#284f4b',l.x,y+.88,l.z,.85,.06,.85);for(const dx of [-1.1,1.1])box(pal.wood,l.x+dx,y+1.8,l.z,.17,2.4,.17);put('roof','#ae6044',l.x,y+3,l.z,1.5,.9,1.3);colliders.push({x:l.x,z:l.z,r:1.25});
 for(let i=0;i<7;i++){const x=l.x-10+i*1.05,z=l.z-9;box('#8a6543',x,y+.65,z,.12,1.3,.12);if(i<6)for(const yy of [.4,.9])box('#b89b67',x+.52,y+yy,z,1.1,.12,.11)}
 for(let i=0;i<30;i++){const x=l.x+7+(i%5)*.48,z=l.z+3+Math.floor(i/5)*.5;box('#6a5b39',x,y+.04,z,.42,.12,.42);put('cone','#809943',x,y+.37,z,.24,.55,.24)}
 for(const [dx,dz] of [[-2,5],[7,1]]){put('cyl','#a77943',l.x+dx,y+.55,l.z+dz,.5,1,.5);for(const h of [.18,.85])put('cyl','#645345',l.x+dx,y+h,l.z+dz,.52,.12,.52)}
}
function mill(l){put('trunk','#e6d6b1',l.x,l.y+4,l.z,2.3,8,2.3);put('cone','#a75a43',l.x,l.y+9.3,l.z,2.7,3,2.7);box('#695240',l.x,l.y+1.2,l.z+2.05,1.1,2.3,.2);const rotor=new THREE.Group();rotor.position.set(l.x,l.y+6.8,l.z+2.4);const mat=new THREE.MeshToonMaterial({color:'#eee1ba',gradientMap:ramp});for(let i=0;i<4;i++){const arm=new THREE.Group();arm.rotation.z=i*Math.PI/2;const spar=new THREE.Mesh(new THREE.BoxGeometry(.16,4.8,.14),new THREE.MeshToonMaterial({color:pal.wood,gradientMap:ramp}));spar.position.y=2;spar.castShadow=true;arm.add(spar);const sail=new THREE.Mesh(new THREE.BoxGeometry(.85,3.2,.08),mat);sail.position.set(.36,2.5,.04);sail.castShadow=true;arm.add(sail);rotor.add(arm)}group.add(rotor);mills.push(rotor);colliders.push({x:l.x,z:l.z,r:2.35});
 for(let i=0;i<50;i++){const x=l.x-7+world.rng()*4,z=l.z-3+world.rng()*8;put('cone','#e4c36a',x,world.ground(x,z)+.4,z,.15,.8,.15)}
}
function shrine(l){const y=l.y;put('cyl','#9ba99a',l.x,y+.18,l.z,4.4,.35,4.4);put('cyl','#899b8e',l.x,y+.48,l.z,3.5,.3,3.5);
 for(const dx of [-3,3]){box('#8b9b90',l.x+dx,y+3,l.z,1.15,5.2,1.35);box('#b1b59c',l.x+dx,y+5.8,l.z,1.5,.5,1.55);box('#607b65',l.x+dx,y+2,l.z+.71,1.12,.17,.08);colliders.push({x:l.x+dx,z:l.z,r:.9})}box('#9faa94',l.x,y+6.1,l.z,7,.75,1.5);for(let i=0;i<5;i++)box('#607f67',l.x-3+i*1.3,y+6.55,l.z+.2,1,.16,1.2);
 put('cyl','#556e63',l.x,y+.95,l.z,1.05,.7,1.05);put('crystal','#8ad5cd',l.x,y+2.5,l.z,.65,1.35,.65,.4);put('crystal','#b7ead4',l.x-.7,y+1.8,l.z+.3,.3,.6,.3,-.4);
 for(let i=0;i<8;i++){let a=world.rng()*Math.PI*2,r=4.7+world.rng()*2;put('ico','#859383',l.x+Math.cos(a)*r,y+.35,l.z+Math.sin(a)*r,.65,.5,.7,a)}
}
function camp(l){put('roof','#c98d56',l.x-1.7,l.y,l.z-2,2.3,2.7,2);put('roof','#815e40',l.x-1.7,l.y+.02,l.z+.015,1.4,2.1,.02);for(let i=0;i<9;i++){const a=i/9*Math.PI*2;put('ico','#858e7f',l.x+2+Math.cos(a)*.8,l.y+.18,l.z+1+Math.sin(a)*.8,.24,.23,.26)}box('#69503b',l.x+2,l.y+.2,l.z+1,1.1,.25,.3,.7);put('cone','#f4b25b',l.x+2,l.y+.65,l.z+1,.4,.95,.4);box('#927047',l.x+4,l.y+.45,l.z+3,2,.6,.55,-.5);colliders.push({x:l.x-1.7,z:l.z-2,r:2})}
function bridge(){const {bx,bz}=world;for(let i=0;i<28;i++){const x=bx-7+(i+.5)*.5;box(i%3?'#b78c57':'#c79d68',x,world.bridgeHeight(x),bz,.47,.32,3.6)}for(const z of [bz-1.8,bz+1.8]){for(let i=0;i<=7;i++){const x=bx-7+i*2;box('#72523b',x,world.bridgeHeight(x)+.65,z,.19,1.5,.19);if(i<7){const nx=x+1;box('#97714d',nx,world.bridgeHeight(nx)+1.2,z,2.1,.16,.17)}}for(const x of [bx-5,bx+5])box('#6a5a44',x,1.9,z,.48,5,.5)}}
function makeTerrain(){const positions=[],colors=[],a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),normal=new THREE.Vector3();const shade=new THREE.Color();
 const vertex=(ix,iz)=>[ix*STEP-SIZE/2,world.heights[iz*(N+1)+ix],iz*STEP-SIZE/2];
 for(let z=0;z<N;z++)for(let x=0;x<N;x++){const vs=[vertex(x,z),vertex(x,z+1),vertex(x+1,z),vertex(x+1,z+1)];for(const ids of [[0,1,2],[2,1,3]]){const v=ids.map(i=>vs[i]);a.fromArray(v[0]);b.fromArray(v[1]);c.fromArray(v[2]);normal.crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();const cx=(a.x+b.x+c.x)/3,cz=(a.z+b.z+c.z)/3,h=(a.y+b.y+c.y)/3,mo=world.moisture(cx,cz);let hex=h<1.3?'#d1c494':normal.y<.73||h>24?'#929787':mo>.66?'#71944f':mo<.32?'#a3ae65':'#88a555';const rd=world.roadAt(cx,cz);if(rd.d<1.32&&h>1.5)hex='#c9b580';shade.set(hex).multiplyScalar(.96+world.noise(cx*.22,cz*.22)*.08);for(const vv of v){positions.push(...vv);colors.push(shade.r,shade.g,shade.b)}}}
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();terrain=new THREE.Mesh(geo,terrainMaterial);terrain.receiveShadow=true;terrain.castShadow=true;group.add(terrain);
}
function addGroundShading(){const index=d3.quadtree().x(d=>d.x).y(d=>d.z).addAll(forest),positions=terrain.geometry.attributes.position,colors=terrain.geometry.attributes.color;for(let i=0;i<positions.count;i+=3){const x=(positions.getX(i)+positions.getX(i+1)+positions.getX(i+2))/3,z=(positions.getZ(i)+positions.getZ(i+1)+positions.getZ(i+2))/3,t=index.find(x,z,4);if(!t)continue;const d=Math.hypot(x-t.x,z-t.z),shade=1-.18*(1-smooth(.3,3*t.s,d));for(let j=0;j<3;j++)colors.setXYZ(i+j,colors.getX(i+j)*shade,colors.getY(i+j)*shade,colors.getZ(i+j)*shade)}colors.needsUpdate=true}
function makeWater(){const g=new THREE.PlaneGeometry(SIZE*3,SIZE*3,1,1);g.rotateX(-Math.PI/2);const mat=new THREE.ShaderMaterial({uniforms:{time:{value:0},day:{value:1}},vertexShader:`varying vec3 vWorld;void main(){vWorld=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 vWorld;uniform float time;uniform float day;void main(){vec2 p=vWorld.xz;float f=sin(p.x*.47+p.y*.22+time*.55)*sin(p.y*.7-time*.7);float stripe=smoothstep(.84,.91,f);float wide=sin(p.x*.035+p.y*.023)*.5+.5;vec3 c=mix(vec3(.10,.39,.40),vec3(.20,.56,.52),wide);c+=stripe*vec3(.20,.30,.23);c*=day;gl_FragColor=vec4(c,1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>}`,side:THREE.DoubleSide});const m=new THREE.Mesh(g,mat);m.position.y=.12;group.add(m);waters.push(mat);
 // Shore ribbons follow the actual terrain's sea-level contour.
 const seg=[];for(let z=0;z<N;z++)for(let x=0;x<N;x++){const v=[[x,z],[x+1,z],[x+1,z+1],[x,z+1]],pts=[];for(let k=0;k<4;k++){const a=v[k],b=v[(k+1)%4],ha=world.heights[a[1]*(N+1)+a[0]],hb=world.heights[b[1]*(N+1)+b[0]];if((ha>.24)!==(hb>.24)){const t=(.24-ha)/(hb-ha);pts.push([mix(a[0],b[0],t)*STEP-SIZE/2,.22,mix(a[1],b[1],t)*STEP-SIZE/2])}}if(pts.length>=2)seg.push(...pts[0],...pts[1])}const lg=new THREE.BufferGeometry();lg.setAttribute('position',new THREE.Float32BufferAttribute(seg,3));group.add(new THREE.LineSegments(lg,new THREE.LineBasicMaterial({color:'#c0d6ab',transparent:true,opacity:.55})))
}
function scatter(){const r=world.rng;const points=[];for(let z=-58;z<58;z+=3.4)for(let x=-58;x<58;x+=3.4){const px=x+(r()-.5)*2.4,pz=z+(r()-.5)*2.4,y=world.ground(px,pz),mo=world.moisture(px,pz),s=world.slope(px,pz),road=world.roadAt(px,pz);if(y<1.6||s>1.05||road.d<3.8||world.landmarks.some(l=>Math.hypot(px-l.x,pz-l.z)<l.r+1)||Math.abs(pz-world.bz)<3&&Math.abs(px-world.bx)<10)continue;if(r()<state.density*(.25+mo*.95)){if(points.some(p=>Math.hypot(p.x-px,p.z-pz)<2.8))continue;tree(px,pz,.7+r()*.65,pz<-17||mo>.65);points.push({x:px,z:pz})}else if(r()<.24){put('ico','#8b9984',px,y+.3,pz,.5+r()*.9,.4+r()*.5,.5+r()*.7,r()*6);if(r()<.4)put('ico','#92aa68',px,y+.6,pz,.4,.25,.5)}}
 for(let i=0;i<1700;i++){const x=r()*114-57,z=r()*114-57,y=world.ground(x,z);if(y<1.6||y>17||world.slope(x,z)>.8||world.roadAt(x,z).d<2||world.landmarks.some(l=>Math.hypot(x-l.x,z-l.z)<l.r*.6))continue;if(r()<.22){put('trunk','#638f47',x,y+.24,z,.06,.48,.06);put('ico',r()>.5?'#e4ca79':'#d4bbbf',x,y+.5,z,.2,.14,.2)}else{for(let j=0;j<2;j++)put('cone',r()>.5?'#90af59':'#a1b767',x+j*.16,y+.24,z,.12,.5+r()*.2,.12,r()*6)}}
}
function makeClouds(){const rng=random(world.hash+8192);const mat=new THREE.MeshLambertMaterial({color:'#f2efdb',transparent:true,opacity:.7,depthWrite:false});for(let i=0;i<8;i++){const g=new THREE.Group();g.position.set(rng()*180-90,38+rng()*12,rng()*70-70);for(let k=0;k<4;k++){const m=new THREE.Mesh(geometries.crown,mat);m.position.set(k*3,Math.sin(k)*.9,0);m.scale.set(3.8,1.3,2.3);g.add(m)}group.add(g);clouds.push(g)}}
const hero=createHero(ramp),player=hero.root;scene.add(player);
const marker=new THREE.Mesh(new THREE.RingGeometry(.62,.72,32),new THREE.MeshBasicMaterial({color:'#ffe3a0',transparent:true,opacity:.42,side:THREE.DoubleSide,depthWrite:false}));marker.rotation.x=-Math.PI/2;scene.add(marker);
let yaw=.20,pitch=.78,distance=38,desiredDistance=38,focus=new THREE.Vector3(-20,4,15),keys=new Set(),stick=new THREE.Vector2(),aim=null,mouseAimUntil=0;
let game;let floating=[],toastTimer=0,shake=0;
const aimRay=new THREE.Raycaster(),aimPlane=new THREE.Plane(),aimPoint=new THREE.Vector3();
function pointAim(e){const rect=canvas.getBoundingClientRect();aimRay.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);aimPlane.set(new THREE.Vector3(0,1,0),-player.position.y-.7);if(aimRay.ray.intersectPlane(aimPlane,aimPoint)){aim={x:aimPoint.x,z:aimPoint.z};mouseAimUntil=performance.now()+1800}}
function notifyGame(e){if(e.type==='hit'){floating.push({text:String(e.value),p:e.position,age:0,color:'#fff0bd'});shake=.06;playSound('hit')}
 if(e.type==='hurt'){shake=.22;document.querySelector('#damage-flash').classList.add('flash');setTimeout(()=>document.querySelector('#damage-flash').classList.remove('flash'),180);playSound('hurt')}
 if(e.type==='action')playSound(e.action);
 if(e.type==='pickup'){toast(e.id==='potion'?'Healing draught +1':`${ITEMS[e.id].name} found · open Bag to equip`);playSound('pickup');renderInventory()}
 if(e.type==='equipment'){toast(`${ITEMS[e.id].name} equipped`);renderInventory()}
 if(e.type==='heal'){toast('Restored 45 health');playSound('heal')}
 if(e.type==='death')document.querySelector('#fallen').hidden=false;
 if(e.type==='reset'){document.querySelector('#fallen').hidden=true;renderInventory()}
 if(e.type==='victory')toast('The trails are clear. Explore the ruins, or start a new world.',7);
}
function toast(text,seconds=3.5){d3.select('#toast').text(text).classed('show',true);toastTimer=seconds}
let audioContext=null,soundOn=false;
function playSound(kind){if(!soundOn)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;const pitch={slash:310,cleave:180,roll:120,hit:90,hurt:66,pickup:760,heal:520}[kind]??220;oscillator.type=kind==='pickup'||kind==='heal'?'sine':'triangle';oscillator.frequency.setValueAtTime(pitch,now);oscillator.frequency.exponentialRampToValueAtTime(kind==='pickup'?1100:pitch*.45,now+.12);gain.gain.setValueAtTime(.045,now);gain.gain.exponentialRampToValueAtTime(.001,now+.15);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(now+.16)}catch{}}
function disposeWorld(){const shared=new Set(Object.values(geometries));group.traverse(o=>{if(o.geometry&&!shared.has(o.geometry))o.geometry.dispose();if(o.isInstancedMesh)o.dispose();if(o.material&&o.material!==propMaterial&&o.material!==terrainMaterial)o.material.dispose()});scene.remove(group);group=new THREE.Group();scene.add(group)}
function generate(){const start=performance.now();disposeWorld();batches={};colliders=[];mills=[];clouds=[];waters=[];forest=[];world=makeWorld(state.seed,state.ruggedness);makeTerrain();makeWater();village(world.landmarks[0]);mill(world.landmarks[1]);shrine(world.landmarks[2]);camp(world.landmarks[3]);bridge();addWorldDetails({world,put,box,colliders});scatter();addGroundShading();commitBatches();makeClouds();resetPlayer();game.reset();drawMap();setLight();terrainMaterial.wireframe=state.wireframe;document.querySelector('#seed-label').textContent=state.seed;document.querySelector('#seed').value=state.seed;document.querySelector('#stats').dataset.generationMs=Math.round(performance.now()-start);document.querySelector('#loading').style.display='none';document.body.dataset.ready='true';document.body.dataset.seed=state.seed;document.body.dataset.trees=forest.length;}
function resetPlayer(){const l=world.landmarks[0];player.position.set(l.x+1,world.walkHeight(l.x+1,l.z+5),l.z+5);game?.velocity.set(0,0);keys.clear();stick.set(0,0);if(state.mode==='explore')focus.copy(player.position)}
function setLight(){const t=state.time,n=smooth(17,21,t),morning=smooth(5,9,t),day=morning*(1-n);sun.intensity=mix(.22,2.5,day);hemi.intensity=mix(.6,1.65,day);sun.color.set(t>17?'#ffd18f':'#fff0c9');sun.position.set(Math.cos((t-6)/12*Math.PI)*60,15+Math.sin((t-6)/12*Math.PI)*55,30);scene.background.set(n>.3?'#5a7888':'#94beb5');scene.fog.color.copy(scene.background);hemi.color.set(n>.3?'#89a5d7':'#c4e5e6');waters.forEach(m=>m.uniforms.day.value=mix(.48,1,day))}
function drawMap(){const svg=d3.select('#minimap');svg.selectAll('*').remove();const scale=d3.scaleLinear().domain([-72,72]).range([0,180]);const defs=svg.append('defs');defs.append('clipPath').attr('id','map-clip').append('circle').attr('cx',90).attr('cy',90).attr('r',89);const g=svg.append('g').attr('clip-path','url(#map-clip)');const values=[];for(let z=0;z<=N;z++)for(let x=0;x<=N;x++)values.push(world.heights[z*(N+1)+x]);const contours=d3.contours().size([N+1,N+1]).thresholds([.5,3,7,13,20])(values);g.selectAll('path.land').data(contours).join('path').attr('class','land').attr('d',d3.geoPath(d3.geoIdentity().scale(180/(N+1)))).attr('fill',(_,i)=>['#a3b179','#86a260','#6d8f56','#657d60','#97a28c'][i]).attr('stroke','#d4dba433').attr('stroke-width',.6);const line=d3.line().x(d=>scale(d.x)).y(d=>scale(d.z));g.selectAll('path.road').data(world.routes).join('path').attr('d',line).attr('fill','none').attr('stroke','#e4ce8f').attr('stroke-width',1.6);g.append('line').attr('x1',scale(world.bx-7)).attr('x2',scale(world.bx+7)).attr('y1',scale(world.bz)).attr('y2',scale(world.bz)).attr('stroke','#e4ce8f').attr('stroke-width',2);g.selectAll('circle.landmark').data(world.landmarks).join('circle').attr('cx',d=>scale(d.x)).attr('cy',d=>scale(d.z)).attr('r',3).attr('fill','#f0d591').attr('stroke','#344f41').attr('stroke-width',1).append('title').text(d=>d.name);g.append('circle').attr('id','map-player').attr('r',3).attr('fill','#fff5dd').attr('stroke','#244d49').attr('stroke-width',1.5)}
function setMode(mode){state.mode=mode;desiredDistance=mode==='explore'?(innerWidth<600?48:38):137;pitch=mode==='explore'?.78:.65;d3.selectAll('[data-mode]').classed('active',function(){return this.dataset.mode===mode});document.body.dataset.mode=mode}
function resize(){const w=innerWidth,h=innerHeight;renderer.setPixelRatio(Math.min(devicePixelRatio,1.65)*state.resolution);renderer.setSize(w,h,false);canvas.style.imageRendering=state.resolution<.8?'pixelated':'auto';camera.aspect=w/h;camera.updateProjectionMatrix();if(w<600&&state.mode==='overview')desiredDistance=175}
const pointers=new Map();let pinch=0;
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{canvas.focus();canvas.setPointerCapture(e.pointerId);pointAim(e);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,touch:e.pointerType==='touch',button:e.button});if(e.pointerType!=='touch'&&e.button===0){if(state.mode!=='explore')setMode('explore');game.request('slash',aim)}if(pointers.size===2){const p=[...pointers.values()];pinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});
canvas.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')pointAim(e);if(!pointers.has(e.pointerId))return;const prev=pointers.get(e.pointerId);pointers.set(e.pointerId,{...prev,x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);desiredDistance=clamp(desiredDistance*pinch/Math.max(d,1),16,210);pinch=d}else if(prev.button===2||prev.button===1||prev.touch){yaw-=(e.clientX-prev.x)*.005;pitch=clamp(pitch+(e.clientY-prev.y)*.004,.38,1.28)}});
for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>pointers.delete(e.pointerId));canvas.addEventListener('wheel',e=>{e.preventDefault();desiredDistance=clamp(desiredDistance*Math.exp(e.deltaY*.001),16,210)},{passive:false});
function action(type,mouse=false){if(state.mode!=='explore')setMode('explore');game.request(type,mouse&&performance.now()<mouseAimUntil?aim:null)}
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SUMMARY'].includes(document.activeElement.tagName))return;const movement=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];if(movement.includes(e.code)){e.preventDefault();keys.add(e.code);if(state.mode!=='explore')setMode('explore')}if(e.repeat)return;if(e.code==='KeyJ'){e.preventDefault();action('slash')}if(e.code==='KeyK'){e.preventDefault();action('cleave')}if(e.code==='Space'){e.preventDefault();action('roll')}if(e.code==='KeyQ')action('potion');if(e.code==='KeyI'||e.code==='Tab'){e.preventDefault();toggleInventory(document.querySelector('#inventory').hidden)}if(e.code==='KeyV')setMode(state.mode==='explore'?'overview':'explore');if(e.code==='Escape'){toggleBuilder(false);toggleInventory(false)}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();stick.set(0,0)});document.addEventListener('visibilitychange',()=>{keys.clear();stick.set(0,0)});
const joy=document.querySelector('#joystick');let joyId=null;joy.addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;joy.setPointerCapture(e.pointerId);setMode('explore');mouseAimUntil=0;moveStick(e)});function moveStick(e){if(joyId!==e.pointerId)return;const r=joy.getBoundingClientRect();stick.set((e.clientX-r.left-r.width/2)/35,(e.clientY-r.top-r.height/2)/35);if(stick.length()>1)stick.normalize();joy.firstElementChild.style.transform=`translate(${stick.x*30}px,${stick.y*30}px)`}joy.addEventListener('pointermove',moveStick);for(const name of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(name,()=>{joyId=null;stick.set(0,0);joy.firstElementChild.style.transform=''});
function toggleBuilder(show){if(show)toggleInventory(false);if(game)game.paused=show;document.querySelector('#builder').hidden=!show;d3.select('#builder-toggle').attr('aria-expanded',String(show));document.querySelector('#cartography').style.visibility=show?'hidden':'visible'}d3.select('#builder-toggle').on('click',()=>toggleBuilder(document.querySelector('#builder').hidden));d3.select('#close-builder').on('click',()=>toggleBuilder(false));d3.select('#home').on('click',()=>{resetPlayer();game.reset();setMode('explore');toast('Rested at Hearthwick · encounters reset')});d3.selectAll('[data-mode]').on('click',function(){setMode(this.dataset.mode)});
d3.select('#regenerate').on('click',()=>{state.seed='BRAMBLE-'+Math.floor(Math.random()*99999);generate()});function applySeed(){const s=document.querySelector('#seed').value.trim();if(s){state.seed=s;generate()}}d3.select('#apply-seed').on('click',applySeed);d3.select('#seed').on('keydown',e=>{if(e.key==='Enter')applySeed()});
const sliders=[{key:'density',label:'Forest cover',min:.1,max:1,step:.05,fmt:v=>Math.round(v*100)+'%'},{key:'ruggedness',label:'Highlands',min:0,max:1,step:.05,fmt:v=>Math.round(v*100)+'%'},{key:'time',label:'Time of day',min:7,max:21,step:.25,fmt:v=>`${Math.floor(v).toString().padStart(2,'0')}:${Math.round(v%1*60).toString().padStart(2,'0')}`}];
for(const s of sliders){const row=d3.select('#sliders').append('div').attr('class','slider-row');const caption=row.append('div').attr('class','slider-caption');caption.append('label').attr('for',s.key).text(s.label);const out=caption.append('output').text(s.fmt(state[s.key]));row.append('input').attr('id',s.key).attr('type','range').attr('min',s.min).attr('max',s.max).attr('step',s.step).attr('value',state[s.key]).on('input',function(){state[s.key]=+this.value;out.text(s.fmt(state[s.key]));if(s.key==='time')setLight()}).on('change',()=>{if(s.key!=='time')generate()})}
d3.select('#resolution').append('label').text('Render resolution');d3.select('#resolution').append('div').attr('class','segmented').selectAll('button').data([{v:1,label:'Crisp'},{v:.65,label:'Soft'},{v:.4,label:'Retro'}]).join('button').classed('active',d=>d.v===state.resolution).text(d=>d.label).on('click',function(e,d){state.resolution=d.v;d3.select('#resolution').selectAll('button').classed('active',q=>q.v===d.v);resize()});
d3.select('#wireframe').on('click',function(){state.wireframe=!state.wireframe;terrainMaterial.wireframe=state.wireframe;d3.select(this).attr('aria-pressed',String(state.wireframe))});d3.select('#motion').on('click',function(){state.motion=!state.motion;d3.select(this).attr('aria-pressed',String(state.motion)).text(state.motion?'Wind on':'Wind off')});
function toggleInventory(show){if(show)toggleBuilder(false);document.querySelector('#inventory').hidden=!show;d3.select('#bag-toggle').attr('aria-expanded',String(show));if(game)game.paused=show;keys.clear();stick.set(0,0);if(show)renderInventory()}
function renderInventory(){if(!game)return;const labels={weapon:'Weapon',shield:'Shield',armor:'Body',head:'Head'};const slots=d3.select('#equipment-slots').selectAll('.equipment-slot').data(Object.entries(hero.equipment)).join('div').attr('class','equipment-slot');slots.html('');slots.append('small').text(d=>labels[d[0]]);slots.append('strong').text(d=>ITEMS[d[1]].name);const rows=d3.select('#bag-items').selectAll('button').data([...game.inventory].map(id=>ITEMS[id]),d=>d.id).join('button').attr('class',d=>'item-card '+(d.rarity??'common')).classed('equipped',d=>hero.equipment[d.slot]===d.id).attr('aria-pressed',d=>hero.equipment[d.slot]===d.id).on('click',(e,d)=>game.equip(d.id));rows.html('');rows.append('span').attr('class','item-slot').text(d=>(d.rarity??'common')+' · '+labels[d.slot]);rows.append('strong').text(d=>d.name);rows.append('small').text(d=>d.description);rows.append('em').text(d=>{if(hero.equipment[d.slot]===d.id)return 'Equipped';const old=ITEMS[hero.equipment[d.slot]],delta=(d.damage??d.defense??0)-(old.damage??old.defense??0);return 'Equip · '+(delta>=0?'+':'')+delta+(d.damage?' attack':' protection')});d3.select('#equipment-stats').text(`${game.weapon.damage} attack · ${game.defense} protection`)}
d3.select('#bag-toggle').on('click',()=>toggleInventory(document.querySelector('#inventory').hidden));d3.select('#close-inventory').on('click',()=>toggleInventory(false));d3.select('#restart').on('click',()=>{resetPlayer();game.reset()});d3.selectAll('[data-action]').on('pointerdown',function(e){e.preventDefault();action(this.dataset.action)});d3.select('#sound').on('click',function(){soundOn=!soundOn;d3.select(this).attr('aria-pressed',String(soundOn)).text(soundOn?'Sound on':'Sound off');playSound('pickup')});
function renderHUD(dt){if(!game)return;d3.select('#health-fill').style('width',game.hp+'%');d3.select('#health-value').text(Math.ceil(game.hp)+' / 100');d3.select('#stamina-fill').style('width',game.stamina+'%');d3.select('#potion-count').text(game.potions);d3.select('#gold-count').text(game.gold);d3.select('#kill-count').text(`${game.stats.kills} / ${game.enemies.length}`);d3.selectAll('[data-action]').classed('unavailable',function(){const type=this.dataset.action;return game.dead||(type==='cleave'&&game.stamina<28)||(type==='roll'&&game.stamina<22)||(type==='potion'&&(!game.potions||game.hp===100))});
 const view=e=>{const p=e.mesh.position.clone();p.y+=e.type==='sentinel'?4:2.7;p.project(camera);return {e,x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight,visible:p.z<1&&Math.abs(p.x)<1.1&&Math.abs(p.y)<1.1}};const near=game.enemies.filter(e=>!e.dead&&(e.engaged||e.hp<e.maxHp)&&e.mesh.position.distanceTo(player.position)<24).map(view).filter(p=>p.visible);d3.select('#enemy-labels').selectAll('.enemy-label').data(near,d=>d.e.id).join(enter=>{const el=enter.append('div').attr('class','enemy-label');el.append('span');el.append('div').append('i');return el}).style('transform',d=>`translate(${d.x}px,${d.y}px)`).each(function(d){d3.select(this).select('span').text(d.e.type==='sentinel'?'Mossbound sentinel':d.e.type==='raider'?'Bramble raider':'Ember slime');d3.select(this).select('i').style('width',Math.max(0,d.e.hp/d.e.maxHp*100)+'%')});
 const lootLabels=game.nearbyLoot().map(l=>{const p=l.mesh.position.clone();p.y+=1.9;p.project(camera);return {l,x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight}});d3.select('#enemy-labels').selectAll('.loot-label').data(lootLabels,d=>d.l.mesh.uuid).join('div').attr('class','loot-label').style('transform',d=>`translate(${d.x}px,${d.y}px)`).style('color',d=>ITEMS[d.l.id]?.rarity==='rare'?'#9bccee':ITEMS[d.l.id]?.rarity==='uncommon'?'#b7e5a1':'#f4dc9d').text(d=>d.l.id==='gold'?'5 gold':d.l.id==='potion'?'Healing draught':ITEMS[d.l.id]?.name);
 floating=floating.filter(f=>(f.age+=dt)<.7);d3.select('#damage-numbers').selectAll('span').data(floating).join('span').style('opacity',f=>1-f.age/.7).style('transform',f=>{const p=f.p.clone();p.y+=f.age*2;p.project(camera);return `translate(${(p.x*.5+.5)*innerWidth}px,${(-p.y*.5+.5)*innerHeight}px)`}).text(f=>f.text);
 if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)d3.select('#toast').classed('show',false)}
 document.body.dataset.combat=JSON.stringify({hp:Math.round(game.hp),stamina:Math.round(game.stamina),kills:game.stats.kills,hits:game.stats.hits,swings:game.stats.swings,action:game.action?.type??'idle',weapon:hero.equipment.weapon,inventory:[...game.inventory],enemies:game.enemies.filter(e=>!e.dead).length,paused:game.paused});
}
let last=performance.now(),fpsStart=last,frames=0,lastPlace='',accumulator=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.25);last=now;if(!world)return;elapsed+=dt;const input=new THREE.Vector2((keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x,(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stick.y);if(input.length()>1)input.normalize();const simulationStart=performance.now();const move=new THREE.Vector2(input.x*Math.cos(yaw)+input.y*Math.sin(yaw),-input.x*Math.sin(yaw)+input.y*Math.cos(yaw));accumulator+=dt;let ticks=0;while(accumulator>=1/60&&ticks++<15){game.update(1/60,move);accumulator-=1/60}marker.position.set(player.position.x,player.position.y+.06,player.position.z);marker.material.color.set(game.action?.type==='roll'?'#89eddd':'#ffe3a0');
 const desiredFocus=state.mode==='explore'?player.position.clone().add(new THREE.Vector3(move.x*.8,1,move.y*.8)):new THREE.Vector3(-4,3,-1);focus.lerp(desiredFocus,1-Math.exp(-dt*9));distance=mix(distance,desiredDistance,1-Math.exp(-dt*7));camera.position.set(focus.x+Math.sin(yaw)*Math.cos(pitch)*distance,focus.y+Math.sin(pitch)*distance,focus.z+Math.cos(yaw)*Math.cos(pitch)*distance);shake=Math.max(0,shake-dt*2);camera.position.x+=Math.sin(now*.08)*shake;camera.lookAt(focus);
 if(state.motion){mills.forEach(m=>m.rotation.z-=dt*.3);waters.forEach(m=>m.uniforms.time.value+=dt);clouds.forEach((c,i)=>{c.position.x+=dt*(.3+i*.025);if(c.position.x>110)c.position.x=-110})}
 renderHUD(dt);const renderStart=performance.now();if(renderer.render(scene,camera)!==false)frames++;document.body.dataset.frameCost=JSON.stringify({simulation:Math.round(renderStart-simulationStart),render:Math.round(performance.now()-renderStart)});if(now-fpsStart>750){const fps=Math.round(frames*1000/(now-fpsStart));d3.select('#stats').text(`${renderer.software?'CPU · ':''}${fps} fps · ${Math.round(renderer.info.render.triangles/1000)}k triangles`);fpsStart=now;frames=0;document.body.dataset.player=`${player.position.x.toFixed(2)},${player.position.z.toFixed(2)}`;document.body.dataset.height=player.position.y.toFixed(2);document.body.dataset.drawcalls=renderer.info.render.calls;document.body.dataset.fps=fps}
 if(frame++%6===0){d3.select('#map-player').attr('cx',(player.position.x+72)*1.25).attr('cy',(player.position.z+72)*1.25);d3.select('#minimap g').selectAll('circle.enemy-dot').data(game.enemies.filter(e=>!e.dead),e=>e.id).join('circle').attr('class','enemy-dot').attr('cx',e=>(e.mesh.position.x+72)*1.25).attr('cy',e=>(e.mesh.position.z+72)*1.25).attr('r',1.9).attr('fill','#d37859');let nearest=world.landmarks.reduce((a,b)=>Math.hypot(a.x-player.position.x,a.z-player.position.z)<Math.hypot(b.x-player.position.x,b.z-player.position.z)?a:b);let place=Math.hypot(nearest.x-player.position.x,nearest.z-player.position.z)<nearest.r+5?nearest.name:'The Bramblewild';if(place!==lastPlace){d3.select('#location').text(place);d3.select('#discovery strong').text(place);d3.select('#discovery span').text(place==='The Bramblewild'?'ON THE TRAIL':'YOU ARE IN');lastPlace=place}}
}
game=new Adventure({scene,hero,ramp,getWorld:()=>world,getColliders:()=>colliders,onEvent:notifyGame});
const ctx=document.modelContext;if(ctx?.registerTool){const controller=new AbortController();const register=tool=>{try{Promise.resolve(ctx.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}};register({name:'read_world',description:'Read the current world seed, controls, and player location.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state,player:{x:player.position.x,z:player.position.z},trees:forest.length,adventure:game.snapshot()})});register({name:'generate_world',description:'Regenerate the visible terrain and reset the player using a given seed.',inputSchema:{type:'object',properties:{seed:{type:'string',minLength:1,maxLength:40}},required:['seed'],additionalProperties:false},execute:input=>{if(!input||typeof input.seed!=='string'||!input.seed.trim()||input.seed.length>40)throw new Error('Seed must contain 1–40 characters');state.seed=input.seed.trim();generate();return {seed:state.seed,trees:forest.length}}});addEventListener('pagehide',()=>controller.abort(),{once:true})}
addEventListener('resize',resize);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();const box=document.querySelector('#error');box.hidden=false;box.textContent='The graphics context was interrupted. Reload this page to regrow your world.'});generate();setMode('explore');resize();requestAnimationFrame(animate);
