#!/usr/bin/env python3
"""Generate the former gallery's compatibility pages; never publish changes."""
import html
import json
from pathlib import Path, PurePosixPath
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
BASELINE = '8d38d42dfab8e99e70031a0a5831b5e18fc6fad5'
ORIGIN = 'https://actiondaveinri.github.io'
BASE = ORIGIN + '/spaceship/'
RUNTIME_SHA256 = 'bbcc4fc672ad90f38daaa9285163191a7a58216ef3b6b1756f6ad2b539809482'
MARKER = '<!-- Generated by scripts/compatibility.py; edit pages-redirects.json. -->'


def validate_route(source, destination):
    path = PurePosixPath(source)
    if (not source or path.is_absolute() or str(path) != source or
            any(part in ('.', '..') for part in path.parts) or
            '\\' in source or not source.endswith('.html') or source == 'index.html'):
        raise ValueError(f'Unsafe compatibility path: {source}')
    url = urlsplit(destination)
    if (url.scheme != 'https' or url.netloc != 'actiondaveinri.github.io' or
            url.query or url.fragment or
            not (url.path in ('/', '/versions.html', '/spaceship/') or
                 url.path.startswith('/projects/')) or
            any(part in ('.', '..') for part in url.path.split('/')) or
            '%' in url.path or '\\' in url.path):
        raise ValueError(f'Unexpected compatibility destination: {destination}')


def redirect_page(source, destination):
    validate_route(source, destination)
    escaped = html.escape(destination, quote=True)
    script_target = json.dumps(destination).replace('<', '\\u003c')
    return f'''<!doctype html>
{MARKER}
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Project moved</title><link rel="canonical" href="{escaped}">
<script>location.replace({script_target} + location.search + location.hash);</script>
<meta http-equiv="refresh" content="0;url={escaped}"></head>
<body><p>This project has moved. <a href="{escaped}">Open project</a>.</p>
<p><a href="{ORIGIN}/">All games and experiments</a></p></body></html>
'''


def read_routes(root=ROOT):
    routes = json.loads((Path(root) / 'pages-redirects.json').read_text())
    if not isinstance(routes, dict):
        raise ValueError('Compatibility manifest must be a route object')
    for source, destination in routes.items():
        validate_route(source, destination)
    return routes


def build_redirects(root=ROOT):
    root = Path(root).resolve()
    pending = {}
    for source, destination in read_routes(root).items():
        page = root / source
        if not page.resolve().is_relative_to(root):
            raise ValueError(f'Compatibility path escapes repository: {source}')
        if any(parent.is_symlink() for parent in (page, *page.parents) if parent != root.parent):
            raise ValueError(f'Symlink compatibility path: {source}')
        if page.exists() and MARKER not in page.read_text():
            raise ValueError(f'Refusing to overwrite unmanaged page: {source}')
        pending[page] = redirect_page(source, destination)
    for page, content in pending.items():
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(content)
    return len(pending)


if __name__ == '__main__':
    print(f'Generated {build_redirects()} compatibility pages.')
