"""Canonical source directories and checked-in GitHub Pages compatibility routes."""
import html
import json
from pathlib import Path, PurePosixPath
import posixpath

ROOT = Path(__file__).resolve().parents[1]
MARKER = '<!-- Generated by scripts/project_layout.py; edit pages-redirects.json. -->'


def local_path(name):
    path = PurePosixPath(name)
    if (not name or path.is_absolute() or str(path) != name or
            any(part in ('.', '..') for part in path.parts) or '\\' in name):
        raise ValueError(f'Unsafe project path: {name}')
    return path


def project_directory(root, project):
    """Use catalog ownership and location, never an old root-level slug."""
    path = local_path(project['directory'])
    if project.get('repo') != 'spaceship' or path.parts[0] != 'projects' or len(path.parts) < 2:
        raise ValueError(f'Expected a spaceship-owned directory under projects/: {path}')
    directory = Path(root) / path
    for parent in (directory, *directory.parents):
        if parent == Path(root).parent:
            break
        if parent.is_symlink():
            raise ValueError(f'Symlink project directory is unsafe: {parent}')
    return directory


def redirect_page(source, destination):
    """Relative routes work on Pages and local servers; JS keeps search/hash."""
    local_path(source)
    local_path(destination)
    target = posixpath.relpath(destination, posixpath.dirname(source) or '.')
    escaped = html.escape(target, quote=True)
    script_target = json.dumps(target).replace('<', '\\u003c')
    # Put JavaScript before the no-script refresh so parameters survive navigation.
    return f'''<!doctype html>
{MARKER}
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Project moved</title><link rel="canonical" href="{escaped}">
<script>location.replace({script_target} + location.search + location.hash);</script>
<meta http-equiv="refresh" content="0;url={escaped}"></head>
<body><p>This project has moved. <a href="{escaped}">Open project</a>.</p></body></html>
'''


def build_redirects(root=ROOT):
    root = Path(root)
    routes = json.loads((root / 'pages-redirects.json').read_text())
    pending = {}
    for source, destination in routes.items():
        local_path(source)
        local_path(destination)
        if source == destination or destination in routes:
            raise ValueError(f'Redirect loop or chain: {source} -> {destination}')
        if not (root / destination).is_file():
            raise ValueError(f'Missing redirect target: {destination}')
        page = root / source
        if page.exists() and MARKER not in page.read_text():
            raise ValueError(f'Refusing to overwrite an unmanaged page: {source}')
        pending[page] = redirect_page(source, destination)
    for page, content in pending.items():
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_text(content)
    return len(routes)
