import {cinderDaylight} from './cinder-lighting.js';
import {PORT_ORIGINS,CRUISE_HEIGHT,shipPose,actorFrame,actorPointToWorld,worldPointToActor,worldPointToLocal,flightPointToWorld,worldPointToFlight,atmosphere,exteriorCameraSpan,relayExteriorView} from './voyage-frame.js';
import {relayEnclosure} from './relay-lighting.js';
import {isLocalFlight,localPort} from './flight-operations.js';
import {updateScaledGait} from './actor-scale.js';
import {contactFootHeight,projectContactFoot} from './engine.js';
import * as T from 'three';
import {SoftwareRenderer} from './software-renderer.js';
import {CrewModel} from './crew-model.js';
import {ground,fixtures,slots,ports,rocks,dist,flightBody,turn} from './engine.js';
import {V,up,geo,mat,mesh,box,ring,label,chamfer,pipe,surface,batchStatic} from './scene-kit.js';
import {WorldView} from './world-view.js';
import {fixture} from './vessel-view.js';
import {surfaceHeight,worldSupport,vesselAt,sceneFrame,footSupportHeight} from './world.js';
export class View{
 constructor(canvas){this.canvas=canvas;this.scene=new T.Scene();this.scene.background=new T.Color('#0a1421');this.hemi=new T.HemisphereLight('#bdd8e2','#5c5950',1.2);this.scene.add(this.hemi);const sun=new T.DirectionalLight('#ffead0',2.6);sun.position.set(-30,55,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40});sun.shadow.bias=-.001;this.scene.add(sun);this.sun=sun;this.scene.add(sun.target);this.zoom={foot:1,flight:1};this.yaw=0;try{const pref=JSON.parse(localStorage.getItem('wayfarer-camera'));if(pref){for(const k of ['foot','flight'])if(Number.isFinite(pref.zoom?.[k]))this.zoom[k]=T.MathUtils.clamp(pref.zoom[k],k==='foot'?.16:.34,k==='foot'?7.5:4.5);if(Number.isFinite(pref.yaw))this.yaw=pref.yaw;}}catch{}this.shake=0;this.rampOpen=1;this.bulkheads=[];this.jets=[];this.engineCores=[];this.innerFlames=[];this.liftJets=[];
 const context=canvas.getContext('webgl2',{antialias:true,alpha:false});this.renderer=context?new T.WebGLRenderer({canvas,context,antialias:true}):new SoftwareRenderer({canvas});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.03;
 this.camera=new T.PerspectiveCamera(42,1,.12,2200);this.camera.position.set(0,43,50);this.target=V(0,0,4);this.ray=new T.Raycaster();this.plane=new T.Plane(V(0,1,0),-1.4);this.ship=new T.Group();this.scene.add(this.ship);this.portRoot=new T.Group();this.scene.add(this.portRoot);this.spaceRoot=new T.Group();this.scene.add(this.spaceRoot);this.rigRoot=new T.Group();this.scene.add(this.rigRoot);this.buildShip();this.ship.traverse(o=>o.userData.animated=true);this.skinMaterials=[];this.skin.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;this.skinMaterials.push(o.material);}});this.roofOpen=0;this.world=new WorldView(this);this.targetMeshes=this.world.targets;this.buildSpace();this.rigs=[];this.dynamic=new T.Group();this.scene.add(this.dynamic);this.pool=[];this.enemyMeshes=[];this.marker=ring(this.scene,0,.04,0,.65,'#70dbc2');this.navRing=ring(this.scene,0,.03,0,1.1,'#e6b76b');this.cabinLights=[[-1.4,3.6,-3.6,'#ffc981',10],[1.4,3.5,6,'#ffc981',9],[0,3.5,-9.7,'#75e4d3',7]].map(([x,y,z,c,intensity])=>{const l=new T.PointLight(c,intensity,9,2);l.position.set(x,y,z);l.userData={staticBake:true,baseIntensity:intensity};l.userData.localPosition=[x,y,z];this.scene.add(l);return l;});this.scene.fog=new T.Fog('#789ea9',420,1350);this.resize();}
 resize(){this.w=innerWidth;this.h=innerHeight;this.camera.aspect=this.w/this.h;this.camera.updateProjectionMatrix();this.renderer.setSize(this.w,this.h);}
 changeZoom(factor){const mode=this.lastFlight?'flight':'foot';this.zoom[mode]=T.MathUtils.clamp(this.zoom[mode]*factor,mode==='foot'?.16:.34,mode==='foot'?7.5:4.5);this.saveCamera();}
 orbit(delta){this.yaw=(this.yaw||0)+delta;this.saveCamera();}
 screenVector(x,z){const angle=(this.yaw||0)-(this.game?.mode==='foot'&&!this.game.docked?this.game.ship.heading-Math.PI:0),c=Math.cos(angle),s=Math.sin(angle);return {x:x*c+z*s,z:z*c-x*s};}
 saveCamera(){try{localStorage.setItem('wayfarer-camera',JSON.stringify({zoom:this.zoom,yaw:this.yaw||0}));}catch{}}
 resetZoom(){this.zoom[this.lastFlight?'flight':'foot']=1;this.yaw=0;this.saveCamera();}
 shadow(parent,x,y,z,w,d){const group=new T.Group();parent.add(group);group.position.set(x,y,z);for(let i=0;i<3;i++){const m=new T.Mesh(new T.CircleGeometry(1,20),new T.MeshBasicMaterial({color:'#081622',transparent:true,opacity:[.055,.08,.12][i],depthWrite:false,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.scale.set(w*(1-i*.17),d*(1-i*.17),1);m.position.y=i*.002;group.add(m);}return group;}
 feedback(event){if(event.type==='hull')this.shake=Math.max(this.shake,.22);if(event.type==='shield')this.shake=Math.max(this.shake,.10);if(event.type==='pulse')this.shake=Math.max(this.shake,.022);}
 buildShip(){const s=this.ship;for(const x of [-2.5,2.5])for(const z of [-8,7.5]){const jet=mesh(s,'cone',x,-.65,z,.3,1.6,.3,'#a4f5e4',true);this.liftJets.push(jet);}this.skin=new T.Group();s.add(this.skin);this.deck=new T.Group();s.add(this.deck);
 box(s,0,.9,-.2,6.65,.85,23.3,'#617173');const floor=box(s,0,1.32,-.1,6.15,.18,22.9,'#34484e');floor.geometry=new T.BoxGeometry(1,1,1,3,1,12);
 for(const side of [-1,1]){box(s,side*3.18,1.7,-.2,.28,.72,23,'#b9a07a');box(s,side*3.24,1.98,-.2,.12,.1,22.5,'#e0c596');box(this.skin,side*3.1,2.8,-.6,.24,2.2,20.7,'#788481');box(s,side*4.7,1.3,1.2,3.2,.7,2.2,'#777962');box(s,side*4.7,1.75,1.2,2.6,.15,1.4,'#c3a062');
 const pod=mesh(s,'cyl',side*6.4,1.6,1.3,1.1,7.8,1.1,'#9a9b88');pod.rotation.x=Math.PI/2;
 box(s,side*6.4,2.12,.5,1.65,.8,4.7,'#767f7a');box(s,side*6.4,2.56,-1,1.45,.1,1.35,'#c89f59');
 const exhaust=mesh(s,'cyl',side*6.4,1.6,5.3,.8,.22,.8,'#283c44');exhaust.rotation.x=Math.PI/2;
 const core=mesh(s,'cyl',side*6.4,1.6,5.47,.57,.12,.57,'#6deddb',true);core.rotation.x=Math.PI/2;this.engineCores.push(core);
 const flame=mesh(s,'cone',side*6.4,1.6,6.7,.55,2.4,.55,'#6ee9dc',true);flame.rotation.x=Math.PI/2;this.flames??=[];this.flames.push(flame);
 const inner=mesh(s,'cone',side*6.4,1.6,6.4,.29,1.5,.29,'#d7fff1',true);inner.rotation.x=Math.PI/2;this.innerFlames.push(inner);
 for(const z of [-1.5,3]){const collar=mesh(s,'cyl',side*6.4,1.6,z,1.14,.14,1.14,'#40545e');collar.rotation.x=Math.PI/2;}
 for(const z of [-.4,.1,.6,1.1])box(s,side*6.4,2.56,z,1.2,.06,.12,'#3a4f5a');
 for(const z of [-1.5,3.2]){box(s,side*7.43,1.6,z,.28,.35,.38,'#263f4d');const jet=mesh(s,'cone',side*7.8,1.6,z,.22,1,.22,'#a9f4eb',true);jet.rotation.z=-side*Math.PI/2;this.jets.push({mesh:jet,side,z,type:'side'});}
 box(s,side*6.4,1.6,-2.9,.46,.42,.3,'#263f4d');const retro=mesh(s,'cone',side*6.4,1.6,-3.5,.24,1,.24,'#a9f4eb',true);retro.rotation.x=-Math.PI/2;this.jets.push({mesh:retro,side,type:'retro'});
 const flash=mesh(s,'sphere',side*3.7,1.8,-9.8,.45,.4,1.1,'#ccffe4',true);this.muzzles??=[];this.muzzles.push(flash);
 box(s,side*3.7,1.8,-7,.4,.45,3.4,'#243b44');box(s,side*3.7,1.8,-9,.18,.22,1,'#a2b7b6');
 box(s,side*2.5,.25,7.5,.5,.5,2,'#36494d');box(s,side*2.4,.25,-8,.5,.5,2,'#36494d');}
 // Cockpit glazing and a removable roof expose one continuous, navigable deck.
 const noseGeo=new T.BufferGeometry(),nv=[[-2.5,1,-13],[2.5,1,-13],[3.1,1,-9.6],[-3.1,1,-9.6],[-2.5,2.55,-13],[2.5,2.55,-13],[3.1,3.8,-9.6],[-3.1,3.8,-9.6]],np=[];for(const f of [[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0],[4,7,6,5],[0,1,2,3]])for(const i of [f[0],f[1],f[2],f[0],f[2],f[3]])np.push(...nv[i]);noseGeo.setAttribute('position',new T.Float32BufferAttribute(np,3));noseGeo.computeVertexNormals();const bow=new T.Mesh(noseGeo,mat('#71878a'));this.skin.add(bow);
 box(this.skin,0,3.8,-1.8,6.2,.35,19,'#b1ad96');box(this.skin,0,4.02,0,2.4,.14,9,'#caaa6b');for(let z=2;z<=7;z+=1)box(this.skin,2,4.03,z,.8,.07,.15,'#455c64');box(this.skin,-1.8,4.12,5,1.3,.4,1.8,'#728584');mesh(this.skin,'cyl',-2,4.8,6,.045,1.5,.045,'#c4c5ac');label(this.skin,'WF–07',0,4.18,-2,'#364c58',.75);box(this.skin,0,2.65,-11.7,5.7,2,.25,'#426878');box(this.skin,0,3.6,-10.3,5.7,.2,2.8,'#708d92');
 box(s,0,1.8,-11.6,6.2,.8,.5,'#b1ad96');
 for(let z=-10;z<11;z+=1.5)box(this.deck,0,1.43,z,1.35,.025,1.43,'#657270');
 for(const z of [-7,0,3])for(const side of [-1,1]){this.bulkheads.push(box(this.deck,side*2.04,2.45,z,1.85,2.05,.16,'#596e71'));this.bulkheads.push(box(this.deck,side*1.08,2.4,z,.09,2,.2,'#b3b3a0'));}
 for(const f of fixtures){this.shadow(this.deck,f.x,1.445,f.z,f.w*.65,f.d*.62);fixture(this.deck,f,1.4);}
 for(const side of [-1,1])fixture(this.deck,{type:'chair',x:side*.85,z:-8.8},1.4);
 for(const side of [-1,1]){for(let z=-9;z<10;z+=2.5){chamfer(this.skin,side*3.25,2.8,z,.18,1.72,2.32,'#798b87','paint');box(this.skin,side*3.36,2.28,z,.04,.04,1.78,'#d0b276');}pipe(this.deck,[side*2.96,3.25,-10],[side*2.96,3.25,10],.065,'#c4ac7e');for(let z=-8;z<10;z+=3){box(this.deck,side*2.93,3.05,z,.08,.055,1.2,'#dfd9b0',true);chamfer(this.deck,side*2.88,1.63,z,.19,.35,.75,'#4b6366','metal');}for(let z=-1.5;z<3.2;z+=.8){chamfer(s,side*7.26,1.6,z,.14,1.1,.18,'#3b5259','metal');}pipe(s,[side*4.4,2.25,.5],[side*6.4,2.65,.5],.10,'#a68f69');}
 for(let z=-10;z<10.5;z+=1.45){box(this.deck,0,1.431,z,6,.018,.026,'#253c45');for(const side of [-1,1])box(this.deck,side*.82,1.447,z,.045,.018,.50,'#d2b477');}
 for(const z of [4,9])for(const side of [-1,1])chamfer(this.deck,side*2.6,1.44,z,.23,.05,.35,'#b7bbaa','metal');
 this.crates=slots.map((p,i)=>{const c=new T.Group();this.deck.add(c);c.position.set(p.x,1.4,p.z);this.shadow(c,0,.045,0,.82,1);box(c,0,.7,0,1.3,1.4,1.6,i%2?'#b7935c':'#7c9b91');for(const x of [-.45,.45])box(c,x,.74,0,.09,1.5,1.64,'#d0c5a5');box(c,0,.8,.81,.5,.3,.02,'#e7d6ad');return c;});
 this.ramp=new T.Group();this.ramp.position.set(0,1.4,10.5);s.add(this.ramp);const ramp=box(this.ramp,0,-.71,3,2.9,.13,6.16,'#899086');ramp.rotation.x=Math.atan(1.4/6);for(let i=0;i<10;i++)box(this.ramp,0,-i*.14+.03,.2+i*.58,2.7,.06,.07,'#bbae87');
 this.rampDoor=box(s,0,2.7,10.8,2.9,2.6,.2,'#8b9488');this.rampDoor.visible=false;
 label(this.deck,'FLIGHT',0,1.7,-7.3,'#dcc89c',.55);label(this.deck,'HABITAT',0,1.6,-.7,'#b4c7c6',.55);label(this.deck,'CARGO',0,1.65,9.8,'#dcc89c',.55);
 }
 buildSpace(){const p=this.spaceRoot;const dummy=new T.Object3D(),stars=new T.InstancedMesh(geo.sphere,mat('#ffffff',true),340);for(let i=0;i<340;i++){const a=Math.sin(i*981.17)*43758.54,b=Math.sin(i*17.4)*19348.2,c=Math.sin(i*35.14)*29348.2;dummy.position.set((a-Math.floor(a)-.5)*1600,-60-(c-Math.floor(c))*90,(b-Math.floor(b)-.5)*1400);dummy.scale.setScalar(.35+(i%4)*.15);dummy.updateMatrix();stars.setMatrixAt(i,dummy.matrix);stars.setColorAt(i,new T.Color(i%3===0?'#708ea5':'#b9c4c8'));}p.add(stars);
 const planet=mesh(p,'sphere',180,-155,-360,125,125,125,'#446775');planet.rotation.z=.4;mesh(p,'sphere',-420,-80,-240,30,30,30,'#a2836b');
 for(const r of rocks){const m=mesh(p,'sphere',r.x,CRUISE_HEIGHT,r.z,r.r,r.r*.85,r.r,'#65727a');m.rotation.set(r.x,r.z,0);}

 }
 createRig(a,index){const model=new CrewModel(a,index),r={model,group:model.group,gait:model.gait};this.rigRoot.add(r.group);r.shadow=this.shadow(this.rigRoot,0,.03,0,.45,.31);this.rigs[index]=r;return r;}
 ensureRig(a,index,g){const r=this.rigs[index]||this.createRig(a,index),frame=sceneFrame(g);if(r.actorRef!==a||r.epoch!==a.poseEpoch||r.frame!==frame){r.actorRef=a;r.epoch=a.poseEpoch;r.frame=frame;r.bodyHeading=a.heading;r.model.setIdentity(a);r.gait.reset();r.model.motion.reset();updateScaledGait(r.gait,a,0,(x,z)=>contactFootHeight(g,a,x,z)??footSupportHeight(g,a,x,z),0,p=>projectContactFoot(g,a,p),r.model.profile.scale);if(r.nameText!==a.name){if(r.name){this.rigRoot.remove(r.name);r.name.material.map?.dispose();r.name.material.dispose();}r.name=label(this.rigRoot,a.name.toUpperCase(),0,2.85,0,index?'#b3cfc7':'#eed1a0',.37);r.name.material.depthTest=true;r.name.userData.actorLabel=true;r.nameText=a.name;}}return r;}
 bodies(g){return [g.player,...g.crew,...(g.docked?g.residents.filter(a=>a.port===g.port):[]),...(g.docked&&g.port===1?(g.robbery?.actors||[]).filter(a=>a.state!=='escaped'):[])];}
 simulateActors(g,dt){for(const [i,a] of this.bodies(g).entries()){const r=this.ensureRig(a,i,g),contacts=r.gait.contacts,dx=a.x-(r.gait.last?r.gait.last.x*r.model.profile.scale:a.x),dz=a.z-(r.gait.last?r.gait.last.z*r.model.profile.scale:a.z),moving=Math.hypot(dx,dz)>.001,armed=i===0&&g.weaponDraw>.01||a.outlaw&&a.weaponDraw>.01;let desired=a.heading;
 if(armed){const delta=Math.atan2(Math.sin(a.heading-r.bodyHeading),Math.cos(a.heading-r.bodyHeading));desired=moving?Math.atan2(dx,dz):Math.abs(delta)>.65?a.heading-Math.sign(delta)*.45:r.bodyHeading;const offset=Math.atan2(Math.sin(desired-a.heading),Math.cos(desired-a.heading));desired=a.heading+T.MathUtils.clamp(offset,-.85,.85);}
 r.bodyHeading=a.contactAction?a.heading:turn(r.bodyHeading,desired,dt*(armed?22:moving?10:7));if(armed)r.bodyHeading=a.heading+T.MathUtils.clamp(Math.atan2(Math.sin(r.bodyHeading-a.heading),Math.cos(r.bodyHeading-a.heading)),-.85,.85);const proxy={...a,heading:r.bodyHeading,aimHeading:a.heading};updateScaledGait(r.gait,proxy,dt,(x,z)=>contactFootHeight(g,a,x,z)??footSupportHeight(g,a,x,z),armed?.08:0,p=>projectContactFoot(g,a,p),r.model.profile.scale);r.model.advanceMotion(proxy,g,i,dt);if(!a.contactAction&&g.time>(a.contactQuietUntil||0)&&r.gait.contacts>contacts&&g.started&&g.mode==='foot')g.events.push({type:'step',actor:a.id??i,x:a.x,z:a.z,space:false,deck:worldSupport(g,a.x,a.z,a.level||0)?.material==='deck'});}}
 actor(a,index,dt,g){const r=this.ensureRig(a,index,g),scale=r.model.profile.scale;
 const wp=actorPointToWorld(g,{x:a.x,y:a.y,z:a.z}),center=V(wp.x,wp.y+1.2*scale,wp.z).project(this.camera),visible=center.z>-1&&center.z<1&&Math.abs(center.x)<1.18&&Math.abs(center.y)<1.25;
 r.group.visible=r.shadow.visible=visible;if(!visible){r.name.visible=false;return;}
 r.group.scale.setScalar(scale);r.group.position.set(a.x,a.y,a.z);r.group.rotation.y=r.bodyHeading;r.shadow.position.set(a.x,a.y+.037,a.z);r.shadow.scale.setScalar(scale);r.name.position.set(a.x,a.y+2.87*scale,a.z);
 const distance=this.camera.position.distanceTo(V(wp.x,wp.y,wp.z)),pixels=2.4*scale*this.h/(2*Math.tan(this.camera.fov*Math.PI/360)*Math.max(1,distance));r.name.visible=!a.outlaw&&pixels>22&&pixels<120&&(!a.civilian||dist(a,g.player)<6);r.model.setDetail?.(pixels>95);r.model.pose({...a,heading:r.bodyHeading,aimHeading:a.heading},g,index,dt);
 }

 projection(x,y,z){const q=this.game?(this.game.mode==='helm'&&!this.game.docked?flightPointToWorld(this.game,{x,y,z}):actorPointToWorld(this.game,{x,y,z})):{x,y,z},p=V(q.x,q.y,q.z).project(this.camera);return {x:(p.x*.5+.5)*this.w,y:(-.5*p.y+.5)*this.h,visible:p.z<1&&p.z>-1};}
 aimPoint(x,y,space=false){if(!space&&this.game?.docked&&this.game.port===1&&this.game.robbery?.stage==='active'){let chosen=null,near=22;for(const a of this.game.robbery.actors){if(!['fighting','fleeing'].includes(a.state))continue;const p=this.projection(a.x,a.y+1.65,a.z),d=Math.hypot(p.x-x,p.y-y);if(p.visible&&d<near){near=d;chosen=a;}}if(chosen)return {x:chosen.x,y:chosen.y+1.65,z:chosen.z};}this.ray.setFromCamera(new T.Vector2(x/this.w*2-1,1-y/this.h*2),this.camera);const g=this.game;const offset=g?(space?shipPose(g).y:actorFrame(g).y):0;this.plane.constant=-(offset+(space?1.8:(g?worldSupport(g,g.player.x,g.player.z,g.player.level||0)?.height??g.player.y:0)+1.75));const p=this.ray.ray.intersectPlane(this.plane,V());return p?(g?(space?worldPointToFlight(g,p):worldPointToActor(g,p)):{x:p.x,y:p.y,z:p.z}):null;}
 pick(x,y){this.ray.setFromCamera(new T.Vector2(x/this.w*2-1,1-y/this.h*2),this.camera);const g=this.game,a=g?.player;if(!a)return null;let best=null,bestDistance=Infinity;for(const level of a.level?[1,0]:[0])for(const initial of [a.y||0,0,1.2,1.4,5]){let h=initial;for(let i=0;i<8;i++){this.plane.constant=-(h+actorFrame(g).y);const p=this.ray.ray.intersectPlane(this.plane,V());if(!p)break;const local=worldPointToActor(g,p),support=worldSupport(g,local.x,local.z,level);if(!support)break;if(Math.abs(support.height-h)<.03){const d=this.ray.ray.origin.distanceTo(p);if(d<bestDistance){bestDistance=d;best={x:local.x,z:local.z,level};}break;}h=support.height;}}return best;}

 dynamicMesh(type,index,c){let m=this.pool[index];if(!m){m=mesh(this.dynamic,type,0,0,0,1,1,1,c,true);this.pool[index]=m;}m.geometry=geo[type];m.material=mat(c,true);m.visible=true;return m;}
 update(g,dt){const flight=g.mode==='helm',deck=g.mode==='foot',s=g.ship,b=shipPose(g),local=isLocalFlight(g),surface=local&&localPort(g)===0;this.game=g;this.world.update(g,dt,this.yaw);
 this.muzzles.forEach(m=>m.visible=flight&&!g.docked&&g.shot>.13);
 this.portRoot.visible=false;this.spaceRoot.visible=true;this.rigRoot.visible=deck;const frame=actorFrame(g);this.rigRoot.position.set(frame.x,frame.y,frame.z);this.rigRoot.rotation.y=frame.heading-Math.PI;
 const playerAboard=deck&&(!g.docked||['wayfarer','ramp'].includes(worldSupport(g,g.player.x,g.player.z,g.player.level||0)?.id));this.roofOpen=T.MathUtils.damp(this.roofOpen,playerAboard?1:0,6,dt);this.deck.visible=playerAboard||this.roofOpen>.005;this.skin.visible=this.roofOpen<.995;this.skinMaterials.forEach(m=>{m.opacity=1-this.roofOpen;m.depthWrite=this.roofOpen<.1;});this.rampOpen=T.MathUtils.damp(this.rampOpen,g.docked?1:0,4,dt);this.ramp.visible=this.rampOpen>.01;this.ramp.rotation.x=-(1-this.rampOpen)*1.79;this.ramp.scale.z=.45+this.rampOpen*.55;this.rampDoor.visible=this.rampOpen<.04;
 const drive=s.drive||{},spool=drive.spool??.06;
 this.flames.forEach((m,i)=>{const power=Math.max(.02,drive.forward||0),length=.5+power*3.4+(s.boost?spool*2:spool*.3),flicker=1+Math.sin(g.time*(i?43:37))*.06;m.visible=!g.docked&&!g.over&&(drive.forward||0)>.025;m.scale.set((.28+power*.28)*flicker,length,.28+power*.28);m.position.z=5.5+length/2;const inner=this.innerFlames[i];inner.visible=m.visible;inner.scale.set(.15+power*.14,length*.7,.15+power*.14);inner.position.z=5.5+length*.35;this.engineCores[i].scale.x=this.engineCores[i].scale.z=.40+spool*.17;});
 this.liftJets.forEach(m=>{m.visible=local&&g.approach.phase!=='capture'&&(drive.lift||0)>.05;const h=Math.min(Math.max(.1,flightBody(g).y||0),.5+(drive.lift||0)*2);m.scale.y=h;m.position.y=-h/2;});
 for(const j of this.jets){const amount=j.type==='retro'?Math.max(drive.reverse||0,(drive.braking||0)*.5):Math.max(0,(drive.lateral||0)*j.side+(drive.turning||0)*j.side*(j.z<0?-.38:.38));j.mesh.visible=!g.docked&&!g.over&&amount>.05;j.mesh.scale.y=.3+amount*2.5;if(j.type==='side')j.mesh.position.x=j.side*(7.55+j.mesh.scale.y/2);else j.mesh.position.z=-3-j.mesh.scale.y/2;}
 this.cabinLights.forEach(l=>{l.visible=playerAboard;const q=actorPointToWorld({...g,docked:false},{x:l.userData.localPosition[0],y:l.userData.localPosition[1],z:l.userData.localPosition[2]});l.position.set(q.x,q.y,q.z);});this.bulkheads.forEach(m=>{const dx=m.position.x-g.player.x,dz=m.position.z-g.player.z,low=deck&&dx*Math.sin(this.yaw-(b.heading-Math.PI))+dz*Math.cos(this.yaw-(b.heading-Math.PI))>0&&Math.hypot(dx,dz)<6;m.scale.y=T.MathUtils.damp(m.scale.y,low?.52:2.05,10,dt);m.position.y=1.4+m.scale.y/2;});
 this.ship.position.set(b.x,b.y,b.z);this.ship.rotation.y=b.heading-Math.PI;this.ship.rotation.z=0;this.crates.forEach((m,i)=>m.visible=i<g.job.cargo);this.targetMeshes.forEach((m,i)=>{m.visible=g.targets[i].hp>0;m.rotation.y=Math.sin(g.time)*.15;});
 this.rigs.forEach(r=>{r.group.visible=false;r.shadow.visible=false;if(r.name)r.name.visible=false;});if(deck)this.bodies(g).forEach((a,i)=>{const own=vesselAt(g,a),occupied=vesselAt(g,g.player);if(own&&own.id===occupied?.id&&(a.level||0)!==(g.player.level||0))return;this.actor(a,i,dt,g);});
 this.marker.visible=deck;this.marker.scale.setScalar(T.MathUtils.clamp((this.span||24)/70,1,2.5));const marker=actorPointToWorld(g,{x:g.player.x,y:g.player.y+.035,z:g.player.z});this.marker.position.set(marker.x,marker.y,marker.z);const next=g.player.path.at(-1);this.navRing.visible=deck&&!!next;if(next){const q=actorPointToWorld(g,{...next,y:(worldSupport(g,next.x,next.z,next.level||0)?.height||0)+.04});this.navRing.position.set(q.x,q.y,q.z);}
 const speed=Math.hypot(b.vx,b.vz),aim=this.aim?flightPointToWorld(g,this.aim):null,lead=flight&&aim?V(aim.x-b.x,0,aim.z-b.z).clampLength(0,45).multiplyScalar(.10):V();
 if(flight){const weight=relayExteriorView(g);lead.add(V(PORT_ORIGINS[1].x-b.x,0,PORT_ORIGINS[1].z+28-b.z).clampLength(0,30).multiplyScalar(weight));}
 const captain=actorPointToWorld(g,{x:g.player.x,y:g.player.y+T.MathUtils.clamp((.7-this.zoom.foot)*2.3,0,1.25),z:g.player.z});
 const focus=flight?V(b.x,b.y,b.z).add(V(b.vx*.18,0,b.vz*.18)).add(lead):!g.started?V(PORT_ORIGINS[0].x+(innerWidth<700?0:-8),PORT_ORIGINS[0].y,PORT_ORIGINS[0].z+5):V(captain.x,captain.y,captain.z);
 const wanted=flight?(exteriorCameraSpan(g)*Math.max(1,.95/this.camera.aspect)*this.zoom.flight):g.started?((innerWidth<700?30:24)*this.zoom.foot):43;
 if(!this.cameraInitialized){this.target.copy(focus);this.span=wanted;this.cameraInitialized=true;}this.lastFlight=flight;this.target.lerp(focus,1-Math.exp(-dt*5));this.span=T.MathUtils.damp(this.span||wanted,wanted,3,dt);this.shake*=Math.exp(-dt*13);
 const angleScale=flight?.85:T.MathUtils.lerp(1.28,.75,T.MathUtils.clamp((this.zoom.foot-.16)/.8,0,1));this.cameraTilt=T.MathUtils.damp(this.cameraTilt??angleScale,angleScale,5,dt);this.camera.position.copy(this.target).add(V(Math.sin(this.yaw)*this.span*this.cameraTilt+Math.sin(g.time*57)*this.shake,this.span,Math.cos(this.yaw)*this.span*this.cameraTilt));this.camera.lookAt(this.target);this.camera.updateMatrixWorld();
 const air=atmosphere(g),daylight=this.renderer.software?Math.round(air*16)/16:air;
 this.sun.color.set('#ffead0').lerp(new T.Color(cinderDaylight.sun),daylight);this.hemi.color.set('#bdd8e2').lerp(new T.Color(cinderDaylight.sky),daylight);this.hemi.groundColor.set('#5c5950').lerp(new T.Color(cinderDaylight.ground),daylight);
 const sunOffset=V(-120,220,88).lerp(V(...cinderDaylight.sunOffset),daylight);
 const coverage=T.MathUtils.clamp(this.span*1.35,12,140),sc=this.sun.shadow.camera;sc.left=sc.bottom=-coverage;sc.right=sc.top=coverage;sc.far=1000;sc.updateProjectionMatrix();const texel=coverage*2/2048,lightFocus=this.target.clone();lightFocus.x=Math.round(lightFocus.x/texel)*texel;lightFocus.z=Math.round(lightFocus.z/texel)*texel;this.sun.position.copy(lightFocus).add(sunOffset);this.sun.target.position.copy(lightFocus);this.scene.traverse(o=>{if(o.userData.detail)o.visible=this.span<65;if(o.isSprite&&o.userData.worldLabel&&!o.userData.actorLabel)o.visible=this.span>13&&this.span<190;});
 this.scene.background.set('#081423').lerp(new T.Color(cinderDaylight.haze),air);this.scene.fog.color.copy(this.scene.background);
 const localFocus=worldPointToLocal(deck?captain:b,1),enclosed=relayEnclosure(localFocus),lightBlend=this.renderer.software?Math.round(enclosed*16)/16:enclosed;
 this.hemi.intensity=T.MathUtils.lerp(T.MathUtils.lerp(1.05,cinderDaylight.skyIntensity,daylight),.28,lightBlend);this.sun.intensity=T.MathUtils.lerp(2.15,cinderDaylight.sunIntensity,daylight)*(1-lightBlend);if(air>.01)this.world.lightCinder();else this.world.lightRelay(localFocus);
 for(let i=0;i<g.enemies.length;i++){let m=this.enemyMeshes[i];const e=g.enemies[i];if(!m){m=new T.Group();this.scene.add(m);box(m,0,1,0,2.8,1.4,6,'#b07566');box(m,0,1,-1.8,7,.45,2,'#8d6863');box(m,0,1.8,1,1.8,.2,1.5,'#edab7a');mesh(m,'sphere',0,1,-3,.5,.5,.6,'#ed735b',true);this.enemyMeshes[i]=m;}m.visible=!g.docked&&e.hp>0;m.position.set(e.x,CRUISE_HEIGHT,e.z);m.rotation.y=e.heading;}
 for(let i=g.enemies.length;i<this.enemyMeshes.length;i++)this.enemyMeshes[i].visible=false;
 let n=0;for(const b of g.bolts){const foot=b.team==='foot'||b.team==='outlaw';if(foot!==g.docked)continue;const color=b.team==='enemy'||b.team==='outlaw'?'#ff8265':b.type==='missile'?'#ffe3a5':'#82ffee',m=this.dynamicMesh('box',n++,color);const p=foot?actorPointToWorld(g,{x:b.x,y:b.y??1.8,z:b.z}):{x:b.x,y:(b.y??CRUISE_HEIGHT+1.8),z:b.z};m.position.set(p.x,p.y,p.z);m.scale.set(b.type==='missile'?.5:.16,.15,b.type==='missile'?2.8:2);m.rotation.set(-Math.atan2(b.vy||0,Math.hypot(b.vx,b.vz)),b.angle,0,'YXZ');}
 for(const e of g.effects){for(let j=0;j<(e.type==='boom'?8:4);j++){const a=j*2.399+e.seed,spread=e.age*(e.type==='boom'?17:8),m=this.dynamicMesh('sphere',n++,e.type==='shield'?(j%2?'#72cadc':'#c6fff2'):e.type==='hull'?(j%2?'#f7a861':'#db7951'):(j%2?'#eab978':'#b5ffe0'));const p=g.docked?actorPointToWorld(g,e):e;m.position.set(p.x+Math.sin(a)*spread,p.y+Math.sin(j*3)*spread*.5,p.z+Math.cos(a)*spread);m.scale.setScalar((e.type==='boom'?1.5:.65)*(1-e.age/(e.type==='boom'?1:.45)));m.rotation.set(0,0,0);}}
 for(let i=n;i<this.pool.length;i++)this.pool[i].visible=false;
 this.renderer.render(this.scene,this.camera);
 }
}
