// @ts-nocheck
'use client';
import {useState} from 'react';
import {ModelPortrait} from './game-action';
import {regionPatch,regionById,regionAt,siteInfo,WORLDS,longitudeDelta,TILE_RADIUS} from '@/lib/world.js';
import {tileOccupants,surfaceOccupants} from '@/lib/occupancy.js';
import {REGIONAL_PROJECTS,regionalAllowed,improveRegion,inventory} from '@/lib/game.js';
export function TileInspector({state,world,site,region,setRegion,showTiles,setShowTiles,setView,apply,occupant,setOccupant}){
 const [focus,setFocus]=useState(''),[choice,setChoice]=useState('');
 const a=siteInfo(world,site,state.universe.seed),selected=regionById(world,region,state.universe.seed)||regionAt(world,a.x,a.z,site,state.universe.seed),cells=regionPatch(world,site,state.universe.seed,selected),all=surfaceOccupants(state,world,site),items=tileOccupants(state,world,selected),chosen=items.find(o=>o.id===(focus||occupant))||items.find(o=>o.id===occupant)||items[0],installation=state.improvements[selected.id],hasColony=!!state.colonies[world]||world==='hearth';
 const options=Object.entries(REGIONAL_PROJECTS).filter(([key])=>regionalAllowed(selected,key)&&!(key==='garden'&&!state.colonies[world])),build=options.find(([key])=>key===choice)||options[0],blocked=!hasColony?'Establish a foothold first':all.some(o=>Math.hypot(longitudeDelta(o.x,selected.x),o.z-selected.z)<o.radius+3)?'A structure occupies this building footprint':null;
 const visit=o=>{const r=regionAt(world,o.x,o.z,site,state.universe.seed);setRegion(r.id);setFocus('');setOccupant(o.id);setShowTiles(true);setView('surface');};
 const pick=id=>{setRegion(id);setFocus('');setOccupant(null);setShowTiles(true);setView('surface');};
 return <section className="tile-inspector" data-world={world}>
 <div className="atlas-heading"><div><p className="eyebrow">TILE INSPECTOR</p><h3>{selected.name}</h3></div><button aria-pressed={showTiles} onClick={()=>{setShowTiles(!showTiles);setView('surface');}}>{showTiles?'Hide grid':'Show grid'}</button></div>
 <div className="terrain-facts"><span>{selected.q}, {selected.r}</span><span>{selected.water?'Water':selected.reserved?'Landing reserve':'Dry ground'}</span>{[['fertile','Fertile soil'],['clay','Clay'],['ore','Metal seam'],['lithium','Lithium'],['silica','Silica']].filter(([k])=>selected[k]).map(([k,n])=><span className={'deposit '+k} key={k}>{n}</span>)}</div>
 <div className="tile-occupancy"><div className="section-label">{items.length?`${items.length} ${items.length===1?'STRUCTURE':'STRUCTURES'} ON THIS TILE`:'NO STRUCTURES ON THIS TILE'}</div>{items.length?<><div className="occupant-list">{items.map(o=><button key={o.id} aria-pressed={chosen?.id===o.id} onClick={()=>{setFocus(o.id);setOccupant(o.id);}}><ModelPortrait asset={o.asset} config={o.config||{}}/><span><b>{o.name}</b><small>{o.status}</small></span></button>)}</div><p className="occupant-purpose">{chosen.purpose}</p>
 {chosen.origin&&<div className="building-story"><span className="section-label">WHY THIS PLACE EXISTS · S{chosen.plot.built+1}</span><p>{chosen.origin.reason}</p>
 {chosen.plot.remaining>0&&<div className="build-stages" aria-label="Construction progress"><span className="done">Foundations</span><span className={chosen.plot.remaining===1?'done':''}>Walls</span><span>Open</span></div>}
 {!!chosen.links?.suppliers.length&&<><small className="connection-key supplier">SUPPLIERS &amp; WORKPLACES</small><div className="building-connections">{chosen.links.suppliers.map(o=><button key={o.id} onClick={()=>visit(o)}><ModelPortrait asset={o.asset}/><span><b>{o.name}</b><small>{o.active?'Activity present':'Activity paused'}</small></span></button>)}</div></>}
 {!!chosen.links?.customers.length&&<><small className="connection-key customer">SERVES LOCAL HOUSEHOLDS</small><div className="building-connections">{chosen.links.customers.map(o=><button key={o.id} onClick={()=>visit(o)}><ModelPortrait asset={o.asset}/><span><b>{o.name}</b><small>Resident customers</small></span></button>)}</div></>}
 {chosen.links?.suppliers.length>0&&<small className="network-note">Amber: workplaces · blue: customers. Supplies use the colony’s shared stores.</small>}
 </div>}</>:<p className="hint">{selected.water?'Open water.':selected.reserved?'Reserved for the founding settlement.':'Undeveloped ground.'}</p>}</div>
 {!installation&&build&&hasColony&&!blocked&&<div className="tile-development"><div className="section-label">DEVELOP THIS GROUND</div><div className="tile-build-options">{options.map(([key,p])=><button key={key} aria-pressed={key===build[0]} onClick={()=>setChoice(key)}><ModelPortrait asset={p.asset||{garden:'greenhouse',extractor:'mine',beacon:'beacon'}[key]}/><b>{p.name}</b></button>)}</div><p>{build[1].description}</p><button className="tile-build-commit" disabled={inventory(state,world).materials<build[1].cost} onClick={()=>apply(s=>improveRegion(s,world,selected.id,build[0]))}>Build · {build[1].cost} materials · {build[1].work} seasons</button></div>}
 <details className="city-explanation tile-chart" open={!region}><summary>Nearby tiles <span>Choose ground or click the planet</span></summary><svg className="atlas-map" viewBox="-65 -58 130 116" role="group" aria-label={WORLDS[world].name+' regional map'}>{cells.map(r=>{const x=(r.q-selected.q)*Math.sqrt(3)*TILE_RADIUS+(r.r-selected.r)*Math.sqrt(3)*TILE_RADIUS/2,z=(r.r-selected.r)*1.5*TILE_RADIUS,coords=Array.from({length:6},(_,i)=>`${x+Math.cos(Math.PI/3*i+Math.PI/6)*TILE_RADIUS},${z+Math.sin(Math.PI/3*i+Math.PI/6)*TILE_RADIUS}`).join(' '),count=tileOccupants(state,world,r).length;return <g key={r.id} role="button" tabIndex={0} aria-label={`${r.name} ${r.q},${r.r} · ${count} structures${r.clay?' · clay':''}${r.lithium?' · lithium':''}${r.silica?' · silica':''}`} aria-pressed={selected.id===r.id} onClick={()=>pick(r.id)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();pick(r.id);}}}><polygon points={coords} className={(r.water?'water':r.ore?'mineral':r.fertile?'fertile':'rock')+(selected.id===r.id?' chosen':'')}/>{count>0&&<text x={x} y={z+2}>{count}</text>}</g>;})}</svg><button onClick={()=>pick(regionAt(world,a.x,a.z,site,state.universe.seed).id)}>Back to landing site</button></details>
 </section>;
}
